### ISSUE TITLE
Make it possible to constrain/filter the input reference field search results

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1007]
Sometimes you want to constrain or filter an input field for references for a subset of a document type. It seems like being able to set a GROQ-filter could be a sensible way to do this.

**Comment by joltmode** [comment]
_Now you will know how to find me on Github._

**Comment by kmelve** [comment]
This feature request comes from @joltmode in the community slack 😄

**Comment by andersnielsendk** [comment]
I agree, this is very important to have, to avoid huge lists of mostly irrelevant reference-options and should be very high priority in my opinion :-)

For example for choosing which documents to highlight, you would often to only have options that are set to active/published, also that are not set to be published on a date in the future and a number of other things. 

But it goes way beyond just choosing highlight items - in my specific project, I currently have to choose ticket category when creating new tickets for an event. And all tickets are named something like Category A, Category B etc. but have a venue reference as well as other info. 
The Categories are always the same at each specific venue, so it doesn't make sense to create new ticket categories for every ticket at every event.
Without the filtering, when choosing a category on a ticket, I have ticket categories for all venues listed, which makes for a very long list, all with the same/very similar names.
I would have to change the preview in order to see which venue they belong to (And preview can't do references, so the name of the venue would also have to be in the ticket_category document) and then from that, find the correct set of tickets in a very long list.

There may be other ways to structure it, to help with this issue, whether for highlight or tickets or any number of other cases. But as I see it, currently the data structure/schema would basically have to be build specifically to avoid issues like this, especially with big datasets, but even in smaller projects. (if using the content studio of course)

I suppose the best way would be to implement a full query (without projections), so the options are not limited by the system:

{
 title: 'highlighted_old_oscar_movies',
 name: 'Highlighted old Oscar winning movies',
 type: 'array',
 of: [
   {type: 'reference', to: {type: 'movie', query: '*[_type == "movie" && releaseYear <= 1979 && oscarsWon >= 1] | order(releaseYear, title) '}}
 ]
}

Or maybe like in the Structure Builder with params, filters and sort order.

In case it is simpler to implement the, although it is a bit limited, an array of filters could also work. It can't handle joins, but would still solve most use cases.

{
 title: 'Higlighted old movies',
 name: 'Highlighted old movies',
 type: 'array',
 of: [
   {type: 'reference', to: {type: 'movie', filters: [
        {'field': 'releaseYear', operator='<', value: '1979'},
        {'field': 'status', operator='==', value: 'published'},
        {'field': 'oscarsWon', operator='>=', value: 1}  
      ], order: 'releaseYear, title'}}
 ]
}

**Comment by bjornwang** [comment]
As an input to this: Maybe the sort order could be specified as well?

I have several cases now where we use reference fields for different types of "tagging" or "typing" of documents where there is typically one default document instance that is used in most of the cases. It would be great to have this document appear at the top of the list when selecting the value for a reference field. Currently editors have to search for it.

Defining this by specifying GROQ ordering might be one option (thus the link to this issue and GROQ filters), but this request should possibly be another issue altogether. Defining a standard ordering of document types (which is also heeded in reference fields) might be another possible solution. Allowing setting a default value for reference fields might be another.

**Comment by dylanjharris** [comment]
Big thumbs on this, both for filtering and sort order. Control by GROQ filter on any input field or dropdown seems like it would cover the most use cases? 

I'm building eCommerce for a large catalog of complex/configurable products. Many-to-many relationships between documents/objects will be such that some level of pre-filtering input fields is required to prevent my shop admins from completely losing their mind — and to strengthen my case for Sanity over WordPress custom post types!

**Comment by malthemilthers** [comment]
Another huge thumbs up on this. This would also be useful in the case of "connecting" translations of documents to each other, filtering by language.

**Comment by readeral** [comment]
Another potentially keen user for this. To be able to 'close out' a reference, so it's still historically attached to documents, but for future documents the 'closed' boolean on the reference means it won't show up in the choices would be ace

**Comment by rexxars** [comment]
v0.147.6 is now released and has support for additional filters for references.
Note that it only reduces the number of documents returned when searching, it does _not_ enforce that the referenced documents will match the given filter after the reference has been set up.

**Comment by rexxars** [comment]
If you have further requests for improvements (such as custom ordering of results), please open a new and more specific feature request. Closing this.
