### ISSUE TITLE
Make preview implementation work for both the document list and text editor

### ISSUE THREAD

**Issue by TurboTobias** [sanity-io/sanity#1096]
**Background**
The `prepare` function creates a preview icon for the document list and text editor
The `component` property handles a custom preview component for a type (i.e video) in the text editor, but not in the document list.

**Solution**
It would be great if the `component` also worked for the document list. So that making one preview - either with the `prepare` or `component` affects both the document list and the text editor.

**Comment by miracle2k** [comment]
Ideally, there would either be two different components, or the component  would receive, as a prop, the context so I can render different things in both contexts.

**Comment by TurboTobias** [comment]
Yes that would be ideal to have the flexibility to choose different components for different previews. In addition, good defaults make life easier. It would be nice if the default preview component worked for all previews, unless configured for a specific preview.

**Comment by tyx** [comment]
Hi ! Definitively a needed feature !

**Comment by shouze** [comment]
Would be that great!

**Comment by miracle2k** [comment]
Even many years later I keep desiring a way to customize the way the list previews are rendered beyond simple text; note that it's not possible to use custom components for the subtitle or title fields either :/

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
