### ISSUE TITLE
Image name renames on upload

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1139]
![5228dfc3-c273-4faf-a666-bc2603bbe193](https://user-images.githubusercontent.com/1131579/50371694-618cfc00-05c0-11e9-9574-4d5e8c7e36fc.gif)

I suspect this happens because of the hash matching thing. But i can see how it’s confusing for users. Not sure how to best go about it? Should we have some feedback telling what happened. Should it be overwritten with new file name?

**Comment by edison-burnkit** [comment]
Is there any update on this? I just came across this issue and it doesn't make sense at all. Once the new file is uploaded, it should replace the old one.

**Comment by JobiJoba** [comment]
This rename process is very annoying for me as I'm uploading file in "Thai"  script. 

The issue is that he rename them in "non-thai" script and it happens that sometimes the filename contain ' (in  the  rename process) 

So it leads to a broken download link 

I don't get it as it was working fine but it start bugging  recently (maybe 4-5  months) 
Is there a way for me to "rename" all the files (should they have  a unique name?)  or disabled that renaming thing? 

Thanks
