### ISSUE TITLE
BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by maxmoeschinger** [sanity-io/sanity#1237]
**Describe the bug**

I'm trying to setup sanity for the first time but when I run yarn start(sanity start) I get `BrowserslistError: Unknown browser query dead`

**To Reproduce**

Run `yarn start`

**Which versions of Sanity are you using?**

@sanity/cli             0.140.9 (up to date)
@sanity/base            0.140.9 (up to date)
@sanity/components      0.140.9 (up to date)
@sanity/core            0.140.9 (up to date)
@sanity/default-layout  0.140.9 (up to date)
@sanity/default-login   0.140.3 (up to date)
@sanity/desk-tool       0.140.9 (up to date)

**What operating system are you using?**

MacOS 10.14.3

**Which versions of Node.js / npm are you running?**

6.8.0
v10.15.1

**Comment by rexxars** [comment]
I'm not able to reproduce this - is this from a fresh setup?
```
~/webdev  $ sanity init
You're setting up a new project!
We'll make sure you have an account with Sanity.io. Then we'll
install an open-source JS content editor that connects to
the real-time hosted API on Sanity.io. Hang on.
Press ctrl + C at any time to quit.

Looks like you already have a Sanity-account. Sweet!

? Select project to use EspenTest [~~~~~~]
? Select dataset to use blog
? Output path: /Users/espenh/webdev/eek
? Select project template Blog (schema)
✔ Bootstrapping files from template
✔ Resolving latest module versions
✔ Creating default project files

✔ Saved lockfile

Success! Now what?

▪ cd /Users/espenh/webdev/eek, then:
▪ sanity docs to open the documentation in a browser
▪ sanity manage to open the project settings in a browser
▪ sanity help to explore the CLI manual
▪ sanity start to run your studio

~/webdev  $ cd eek
~/webdev/eek  $ yarn start
yarn run v1.13.0
$ sanity start
✔ Checking configuration files...
✔ Compiling...
Content Studio successfully compiled! Go to http://localhost:3333
```

Are you running this inside of a monorepo or similar?

**Comment by maxmoeschinger** [comment]
I'm running it inside an existing frontend project as a sub-repository. Below is a screenshot of the error. Maybe it's worth mentioning that I first tried to run sanity deploy and then got the same error when I ran yarn start.

![Skjermbilde 2019-03-14 kl  13 37 22](https://user-images.githubusercontent.com/15786838/54358980-e9cfea00-4661-11e9-903a-eb90a405b9bb.png)

**Comment by rexxars** [comment]
It seems to me like there are conflicting version os `browserlist`/`caniuse-api` - I am not sure why this is happening, as I assume you are running lerna or yarn workspaces, which shouldn't mix incompatible versions of dependencies...

**Comment by runeb** [comment]
Info from one of our users on this issue

> turns out pixrem (which is used by postcss-cssnext) is using a super old version of browserslist which was clashing with a version used in the project. Used yarn resolution to fix it to latest version.

**Comment by torbjokv** [comment]
I had the same issue and after looking for a while, I found out what the bug was caused by. I'll leave my finding here in case someone else have the same issue (maybe a bug in sanity cli?).

If you do `sanity init` in an exsisting project and this project have a "browserslist" section with "dead" or "not dead" in the package.json, you will get the _Unknown browser query \`dead\`_ error when running `sanity start`. When running init, it detects the package.json and automatically suggests to place sanity studio in a subfolder. I would expect the sanity studio project to be self contained and not influenced by files higher in the file hierarchy, but the error happens even if sanity studio is located in a subfolder.

Not sure if it is by intention or not to read the parent project package.json, but if it is, I guess the solution is to replace or remove the depricated postcss-cssnext that causes browserslist to run with version 2.0.

**Workaround:** Remove or replace _browserslist -> dead/not dead_ with something else in your package.json
