### ISSUE TITLE
Sanity Deploy fails after installing @sanity/code-input

### ISSUE THREAD

**Issue by jameshowelldev** [sanity-io/sanity#1301]
Hi, I've been using Sanity for the back-end of a web development blog. In order to include code snippets in my blog posts I have today installed the code-input plugin for Sanity. This appeared to be working fine as the code snippet widget was appearing in my posts. However when I've come to deploy it to my site, the build is failing with an error:

"WebpackError: Unknown block type "codeSnippet", please specify a serializer for it in the `serializers.types` prop'

Does anyone know what I've done wrong? Where is the serializers.types prop?

**Comment by kmelve** [comment]
Hi @jameshowelldev!

This happens because you haven't included the new `code` type in your rich text field to the [`serializers.js`](https://github.com/sanity-io/sanity-template-gatsby-blog/blob/master/template/web/src/components/serializers.js) file.

For example:

```javascript
const serializers = {
  types: {
    authorReference: ({node}) => <span>{node.author.name}</span>,
    mainImage: Figure,
    code: ({node}) => <pre className={`language-${node.language}`}><code>{node.code}</code></pre>
  }
}
```

You can also watch this tutorial on how to implement it in the Gatsby frontend: https://www.youtube.com/watch?v=asENbq3s1m8&t=1s

I'll close this issue, if you need more help, you're welcome to join our [community](https://slack.sanity.io), or post a question on [StackOverflow](https://stackoverflow.com/questions/tagged/sanity).
