### ISSUE TITLE
Remember the current structure location when adding new documents

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#1358]
**Is your feature request related to a problem? Please describe.**
I'm using the structure builder to group "configuration" type documents together in a hierarchy of panes. This works great to hide complexity, but comes at a cost.

When clicking 'Add' (plus) to create a new document within one of these panes, Sanity Studio looses track of the current pane, so I cannot easily create another document of the same type. I have to navigate from the top back to the same pane again to find the 'Add' button again.

An example flow illustrated by Studio URLs:
1. I want to create a bunch of Tag documents, used to tag Articles etc. I navigate through my configured pane hierarchy to find tags; **Settings > Categorization > Tags**, and end up here: http://localhost:3333/desk/settings;categorization;tags
2. I click 'Add' (plus) to create a new Tag document, which takes me to the edit page: http://localhost:3333/desk/edit/tag/9ba9a37a-1262-4123-b6f8-3fcc0d2158ad
I've now lost the pane context, **Settings > Categorization > Tags**, and the panes on the left hand side have disappeared from the Studio. (The document type "tag", referenced in the edit URL, is of course hidden in the left pane following your suggested hiddenDocTypes pattern from the [Structure builder How it works](https://www.sanity.io/docs/structure-builder/how-it-works) documentation.)
3. Saving my newly created Tag document, wanting to continue adding tags, I have to navigate back to the same location I came from;  **Settings > Categorization > Tags**.
4. Repeat this for all the tags I want to create.

**Describe the solution you'd like**
Using panes configured with Structure builder should keep "navigation state" just as whan navigating document types populated in the left menu automatically.

**Comment by evenwestvang** [comment]
This is a completely reasonable suggestion. When arriving directly to a document it can be non-trivial to establish a path to it, but when you already have an established path you should not use it when creating a new document.

**Comment by hansarnevartdal** [comment]
Was searching for a way to do the exact same thing, and arrived here. I assume there is no way to work around this yet?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
