### ISSUE TITLE
Control of "fit" for preview images

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#1365]
**Is your feature request related to a problem? Please describe.**
When configuring preview for document types, it's not always convenient to have the preview media image being cropped. For example, we model companies with logos. Cropped logos don't look too great. Changing the "fit" to for example `clip` would be more apropriate.

**Describe the solution you'd like**
Ability to specify the "fit" for preview images:
`fit: <clip, crop, fill, fillmax, max, scale, min>`

**Comment by bjornwang** [comment]
@vicbergquist 

Trying to bring this to life again with an example. Here's a list of the preview images for a list of company information where the image is their logo. I guess you can see the problem.

![image](https://user-images.githubusercontent.com/5180175/203840457-e8363cf6-8ac1-41fe-b814-c1028a0fb369.png)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
