### ISSUE TITLE
Enable use of previews for inlined objects in documents, just like for arrays

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#1398]
**Is your feature request related to a problem? Please describe.**
Sanity documents grow very long, and endless scrolling in forms doesn't give a good overview. Optional fields in particular take up valuable space.

Consider the following example of an inlined product summary object, which steals a lot of vertical space in an otherwise long document, and where the image field is also optional.

![image](https://user-images.githubusercontent.com/5180175/60201205-0aeecc00-9848-11e9-9046-8b3017f7b336.png)

To optimize use of space, we've wrapped the image in collapsed fieldset, but this poses another problem, as the editor can no longer see if an image is present without expanding the fieldset.

**Describe the solution you'd like**
To save space, make forms more scannable and give a quicker overview of contwnt, enable collapsing inlined objects like the product summary in the example into "previews" just like for arrays.

For our example, we could get away with something as short and sweet as this:

![image](https://user-images.githubusercontent.com/5180175/60201949-d7ad3c80-9849-11e9-9ea5-e1483d43cf2b.png)

This is brief, scannable, helps with the overview of the document and gets out of the way if fields are left empty, like the optional image.

Also builds on your already great preview functionality, so should hopefully not be too hard to implement. :-)

**Comment by evenwestvang** [comment]
This is a great suggestion and incidentally something I was discussing with @mariuslundgard just the other day. We should make sure we capture this for future rework of the form builder.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
