### ISSUE TITLE
Ability to add arbitrary items to the edit dropdown menu

### ISSUE THREAD

**Issue by mshick** [sanity-io/sanity#1410]
**Is your feature request related to a problem? Please describe.**
Similar to the `productionPreviewUrl` implementation, I would like the ability to add arbitrary items to the edit dropdown menu to provide other helpful links — in particular links to alternative publish locations (e.g., staging, production, live preview).

**Describe the solution you'd like**
A builder part that returns an array of well-structured objects, suitable for rendering as menu items, allowing me to specify the menu item display text, the link destination and an icon. 

**Describe alternatives you've considered**
Custom input plugins. Does the job, but the UX is not as great, and the implementation is more cumbersome.

**Comment by vicbergquist** [comment]
Thank you for your feature request! This does indeed sound very useful and something that we would like to explore in the future 👍

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
