### ISSUE TITLE
[vision] Query favorites and history

### ISSUE THREAD

**Issue by mrkolby** [sanity-io/sanity#1414]
Vision is useful to quickly test GROQ queries and it would be nice to be able to save specific queries and to see a history of earlier ones.

Example from [Sequel Pro for MySQL](https://www.sequelpro.com):

<img width="771" alt="Screenshot 2019-07-06 at 17 37 25" src="https://user-images.githubusercontent.com/300595/60758206-d54e9d80-a014-11e9-9195-445569182f1d.png">

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
