### ISSUE TITLE
yarn.lock file superfluously generated

### ISSUE THREAD

**Issue by aronhoyer** [sanity-io/sanity#1510]
**Describe the bug**

Installing a dependency with `sanity install` generates a `yarn.lock` file. I don't have Yarn installed anywhere.

**To Reproduce**

1. Uninstall Yarn. Like completely.
2. Create a Sanity project with `npx` (this also generates a `yarn.lock` file)
3. Install `@sanity/cli` as a dev dependency
3. Install a Sanity plugin
4. `yarn.lock` file should be generated in your project root

**Expected behavior**

I was hoping the Sanity CLI would be able to pick up which package manager was accessible, and make a decision on which one to use, maybe even ask which one to use if multiple package managers are available.

**Which versions of Sanity are you using?**

```
@sanity/cli             0.142.2 (up to date)
@sanity/base            0.142.2 (up to date)
@sanity/cli             0.142.2 (up to date)
@sanity/color-input     0.142.0 (up to date)
@sanity/components      0.142.5 (up to date)
@sanity/core            0.142.5 (up to date)
@sanity/dashboard       0.142.5 (up to date)
@sanity/default-layout  0.142.5 (up to date)
@sanity/default-login   0.142.1 (latest: 0.142.3)
@sanity/desk-tool       0.142.5 (up to date)
```

**What operating system are you using?**

macOS Mojave 10.14.5 (18F203)

**Which versions of Node.js / npm are you running?**

NPM 6.9.0, Node.js v10.16.3

**Comment by rexxars** [comment]
We're currently not shelling out to yarn/npm directly when installing dependencies, but instead calling a prepackaged version of yarn with a `--json` flag in order to shape the messages it outputs. Using the globally available npm/yarn would make it hard to do this, so we'd have to resort to just dumping the output of npm directly to the terminal. This _may_ be acceptable, but we have to give it some more thought first.

Thanks for reporting, though :)

**Comment by Svish** [comment]
> We're currently not shelling out to yarn/npm directly when installing dependencies, but instead calling a prepackaged version of yarn with a --json flag

Well, that explains why `npm` doesn't seem to like the generated `node_modules` folder either... Had to delete the `node_modules` folder (and `yarn.lock`) and "rerun" `npm install` to be able to run npm properly again.

Why do you do this? Could you maybe not? I'd much prefer a guide on setting up sanity _without_ `sanity init` and/or at least without my dev environment being polluted with `yarn` stuff...

**Comment by apennell** [comment]
I'd like to +1 on this, and if there aren't plans to change it then the docs should be updated to reflect the fact that yarn is expected and required. I deleted the yarn.lock when it was called out in a pr as unnecessary, since we use npm. Playing around later, I realized the it had been generated whenever I used the `sanity` command, like `sanity install` for a plugin. If you delete `yarn.lock` then try to run `sanity uninstall x-plugin`, it will error because it can't find a yarn.lock.

The docs don't mention yarn anywhere, they actually seem to encourage using npm in Getting Started. But this inevitably results in both a yarn.lock and package-lock.json, which as far as I can tell is discouraged to do. If `sanity` is going to continue to generate a yarn.lock and also require that same file later, then Sanity docs should be clear and upfront that yarn is required, and _not_ include steps that use npm.

**Comment by franzwilhelm** [comment]
I'm also +1ing this. 

I'm not using yarn, but npm for package management. Couldn't sanity make it possible to chose whether to use npm or yarn, so that the respective `package-lock.json` or `yarn.lock` will be used when running the `sanity install` command.

I've actually had to stop using `sanity install`, since it generates a yarn.lock file in my project. I've fallen back to using `npm install package-name` which is cumbersome as all the sanity official docs are using `sanity install`.
