### ISSUE TITLE
Configurable order and/or searchable list when browsing assets

### ISSUE THREAD

**Issue by thomax** [sanity-io/sanity#1518]
When you choose "browse" instead of "upload" when wanting to reference an image or file, the list can be quite unwieldy if you have a lot of assets. It would be useful to either

- Let the Studio dev provide an order (in the schema or elsewhere)
- Include some UI affordance to allow the user select ordering
- Let images be searchable (via a text field)

**Comment by KimPaow** [comment]
Also having access folders or something similar to really separate the content would be really nice.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
