### ISSUE TITLE
GROQ Query that returns targetable data

### ISSUE THREAD

**Issue by dane-brown** [sanity-io/sanity#1523]
**Is your feature request related to a problem? Please describe.**
So currently I am trying to take data from sanity that looks like this : 

```
    {
      "_type": "depositMethod",
      "slug": {
        "_type": "slug",
        "current": "sid-secure-eft"
      }
    },
    {
      "_type": "depositMethod",
      "slug": {
        "_type": "slug",
        "current": "lottostar-voucher"
      }
    }
```

And create a targetable key for each item of data. Example: 
```
{
	"sid-secure-eft": {
		"_type": "depositMethod",
		"slug": {
			"_type": "slug",
			"current": "sid-secure-eft"
		}
	},
	"lottostar-voucher": {
		"_type": "depositMethod",
		"slug": {
			"_type": "slug",
			"current": "lottostar-voucher"
		}
	}
}
```

In doing this we gain the power to do data['lottostar-voucer'] within the frontend to target a specific item of data returned from sanity.
 
**Describe alternatives you've considered**
The way above just seems to make the most sense to me, if there are any other ways of doing this sort of thing I would be very grateful.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
