### ISSUE TITLE
DateTimeOriginal incorrectly stored as zulu time in sanity.imageExifMetadata

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#1538]
Enabling `exif` metadata for `image` types will append an object where the `DateTimeOriginal` is stored as a ISO string in zulu time. AFAIK the EXIF specification doesn't include timezones, and the DateTimeOriginal is always set to local time without any timezone specified (basically whatever the device's clock is set to) thus a string value in zulu time is misleading.

One proposal would be to include GPS data like `GPSDateStamp` and `GPSTimeStamp` whenever possible, which are localized.

Also related to exif metadata but perhaps not as critical, the `exif` doesn't show as part of the schema:

![image](https://user-images.githubusercontent.com/6848068/66572733-c296b800-eb71-11e9-9a95-c281df3dbcf6.png)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
