### ISSUE TITLE
Allow use of `slug` with `source` option in an `object` type field

### ISSUE THREAD

**Issue by coreyward** [sanity-io/sanity#1571]
Currently the `slug` type allows you to specify a `source` option pointing to the field that the slug should be derived from when the “Generate” button is clicked. Currently this `source` field is only looked up at the document level. 

For example, in the following schema, the `slug` field on `contentBlock` will fail to resolve, resulting in a disabled “Generate” button in the Studio.

```js
[
  {
    name: "page",
    type: "document",
    fields: [
      {
        name: "content",
        type: "array",
        of: [{ type: "contentBlock" }],
      },
    ],
  },

  {
    name: "contentBlock",
    type: "object",
    fields: [
      {
        name: "title",
        type: "string",
      },
      {
        name: "slug",
        type: "slug",
        options: {
          source: "title",
        },
      },
    ],
  }
]
```

This is also true when providing a function as a value to `source`: The first param is the entire `document`, and the second param, ([specced as `options`](https://www.sanity.io/docs/slug-type#source-9a89f442eaea)) only has a `parentPath` property:

https://github.com/sanity-io/sanity/blob/b28758cdacb9f684095d5a5e276ac31e31487916/packages/%40sanity/form-builder/src/inputs/Slug/SlugInput.tsx#L120-L125

As a result, developers integrating with Sanity need to do a fair amount of work to have a slug field on an `object` that sources from the object (rather than the `document`):

```js
const source = (document, opts) => {
  const obj = opts.parentPath.reduce((doc, path) => {
    if (typeof path === "object") {
      const [[property, value]] = Object.entries(path)
      return doc.find(d => d[property] === value)
    } else {
      return doc[path]
    }
  }, document)

  return obj[options.source]
}
```

**Describe the solution you'd like**
I'd like to see the `source` option support relative references (e.g. referencing the parent `object`) rather than reaching up to the `document` level.

**Additional context**
There's a fairly lengthy [conversation about this in the Slack #help channel](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1571969953158600).

**Comment by rexxars** [comment]
This should hopefully solve this: https://github.com/sanity-io/sanity/pull/1646
Will be released early next week.

**Comment by BarkatKhan-TP** [comment]
how to auto slugify the slug without using generate button click.
My scenario: Slug field is hidden - on selection of string field which is dropdown, slug should be auto generated. However, yet I need to value for source field of slug and on generate click it gives slug --- I need slug to be generated when I change source field value.

**Comment by bigidea-kz** [comment]
@rexxars 

Hello!
You said - Will be released early next week ( 7 Dec 2019)

This problem is still present today.

**Comment by KenEucker** [comment]
I have the same scenario as @BarkatKhan-TP that I would like to resolve. Autogenerate seems like the right option here. Did I miss somewhere in the documentation there being a way to autogenerate the slug?

**Comment by connorlindsey** [comment]
Running into the same issue. I have a "Unit" document which has an array of "Module" objects (for a course platform) where each module is a page and thus needing a slug. Both Unit and Module have a title field which I'm using for both of their slug properties. 

Any update on how to do this? Can't read the original slack help thread because of the message limit.

**Comment by mig-hub** [comment]
@rexxars , yes like @bigidea-kz I don't understand how it fixes the issue. As far as I can tell the commit gives access to the parent document. It seems the problem here is the opposite: we get access to the main top level document where what we want is be able to reference the "real" current document.

I have a similar case where I have a single document with a list of embedded documents. I want to give these a slug. But the source field I give does not work because it is trying to find this field on the main document instead of the current child/embeded document.

Is there a way to achieve this?
