### ISSUE TITLE
Feature Request: Ability to provide value to Studio "sortings" similar to preview

### ISSUE THREAD

**Issue by treechime** [sanity-io/sanity#1585]
**Is your feature request related to a problem? Please describe.**
I'm able to customise the way a document is previewed in the Studio but I can't create a sort order that reflects the preview.

I'm creating an internal slideshow application with playlists & slides. 99% of the time the content on the slides will be dynamic, but sometimes it will just be an image. So I have a `title` field which will be displayed on the slide frontend, but if the slide is just supposed to be an image, then I enter  the title into `adminTitle` field to just be used in the studio.

I can use the preview select/prepare to return `title: adminTitle || title`, but I can't then sort all of the documents in the studio by this same value which is confusing for users.

**Describe the solution you'd like**
Some sort of select/prepare statement for the sortings similar to the preview, or even exposing preview values to the sortings

I'm not sure if this is really practical or not, but thought I'd put it out there as something I've gotten stuck on. I'm probably just going to restructure the schema and add a toggle to show/hide the title on the frontend, but could still be useful maybe?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
