### ISSUE TITLE
options to make the array preview element text wrap around instead of truncate

### ISSUE THREAD

**Issue by neterial** [sanity-io/sanity#1640]
**Is your feature request related to a problem? Please describe.**

my use case is i have an array of sentences and users should be able  to see all of it( now some sentence got truncated )  screen shot example below: 

**Describe the solution you'd like**

options to made the text wrap

**Describe alternatives you've considered**

* made the default editor wider than 672px 
* use rich editor, but it doesn seems to support drag and drop to rearrange

**Additional context**

https://res.cloudinary.com/dcmzulhgd/image/upload/q_auto:low/w_800/v1574922320/alzp4meodd8k85lm6sec.png

**Comment by kmelve** [comment]
Thanks for reporting! Would your use case be solved if paragraphs in the rich text editor was draggable?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
