### ISSUE TITLE
Make inline objects first class citizens

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#1644]
We make extensive use of inline objects in arrays to build up complex document types. Nested objects gives incredible strength to Sanity document models.

However, we find that inlined objects still suffer from not being treated as first class citizens in Sanity.

For example:
1. Validation user experience is poor, with all fields highlighted in red as soon as an inlined object is added. (Makes the user feel they've done something wrong from the get-go.)
2. Default values don't work for inlined objects.
3. Setting user-specified keys have weak support on inline objects. Slug for example will refer to fields on the parent level for its source.

Hoping to see support for new features also becoming available for inlined objects.

**Comment by vicbergquist** [comment]
Hi! Just dropping by but:
> 2. Default values don't work for inlined objects.

I guess this is what you want: https://github.com/sanity-io/sanity/issues/1581? 😃

**Comment by bjornwang** [comment]
Yep, @vicbergquist, that looks just about right!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
