### ISSUE TITLE
Search for a content in array of strings returns nothing

### ISSUE THREAD

**Issue by jorngeorg** [sanity-io/sanity#1668]
If you have a field like this 
```
    {

      title: "Tags",
      name: "tags",
      type: "array",
      of: [
        {
          title: "Tag",
          type: "string",
          name: "tag"
        }
      ],
      options: {
        layout: "tags"
      }
    },
```

and you input a tag like "murgh" and try to search for that, your search results will be empty.

![image](https://user-images.githubusercontent.com/968695/70999003-d3672b00-20d8-11ea-9441-a62cdf29b90a.png)

**Comment by christopherafbjur** [comment]
Hi! Just checking in to see if this is something that is on your roadmap. Been almost a year since it was reported @jorngeorg @vicbergquist 

Thanks in advance!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
