### ISSUE TITLE
The long-awaited history property on slugs

### ISSUE THREAD

**Issue by mskutle** [sanity-io/sanity#1669]
**Is your feature request related to a problem? Please describe.**
We need a good solution for handling redirects, canonicals etc. whenever slugs change. 

**Describe the solution you'd like**
The long-awaited history property on slugs that is mentioned [here](https://www.sanity.io/docs/slug-type) :)

**Describe alternatives you've considered**

**Additional context**

**Comment by tommybarvaag** [comment]
When migrating customers with an existing CMS this functionality is crucial in regards to SEO. It can be done manually, with scripts or at the hosting vendor. But everything would be a lot simpler if the functionality was supported out of the box in Sanity.

Hoping this will be included in the roadmap.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by unitof** [comment]
I'd like an update or reopen here. It certainly seems `slug` type is built with a history feature in mind.
