### ISSUE TITLE
The editor is "locked" when adding only one image.

### ISSUE THREAD

**Issue by asundlihardig** [sanity-io/sanity#1690]
**Describe the bug**
Something strange is happening in the Rich Text Editor if the editor is empty, and we upload an image. The editor seems to be locked, and we are not able to write anything. If we start with text, there is no problem. The attached screen recording shows the behaviour.

In short: We are not able to add any text if we add an image block to the Rich Text Editor first.

**To Reproduce**
1. Go to the Rich Text Editor with a custom image block.  
2. Click on Insert Image and select an image
3. Try to add text

**Expected behavior**
We should be able to add text after the image was inserted.

**Screenshots**
[screenrecording.mov.zip](https://github.com/sanity-io/sanity/files/4036667/screenrecording.mov.zip)

**Which versions of Sanity are you using?**
@sanity/cli                0.147.3 (up to date)
@sanity/base               0.147.6 (up to date)
@sanity/components         0.147.6 (up to date)
@sanity/core               0.147.6 (up to date)
@sanity/dashboard          0.147.6 (up to date)
@sanity/default-layout     0.147.6 (up to date)
@sanity/default-login      0.147.0 (up to date)
@sanity/desk-tool          0.147.7 (up to date)
@sanity/google-maps-input  0.147.6 (up to date)
@sanity/vision             0.147.6 (up to date)

**What operating system are you using?**
macOS Catalina 10.15.2

**Which versions of Node.js / npm are you running?**
6.12.0
v10.15.3

**Additional context**
Custom component used in Rich Text Editor:
[imageWithMeta.js.zip](https://github.com/sanity-io/sanity/files/4036752/imageWithMeta.js.zip)

**Comment by vicbergquist** [comment]
I believe you can still start writing if you press enter or arrow down? I've had a similar problem and I believe it happens with any type of content block when there is no text!

**Comment by asundlihardig** [comment]
It works when we hit enter. So, it's a feature not a bug?

**Comment by vicbergquist** [comment]
Definitely a bug (and bad ux) 😅 Thank you for reporting!

**Comment by asundlihardig** [comment]
No worries. I'll tell the content editors. Thank you for responding to this issue. 🙌🏻 ✌🏻

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
