### ISSUE TITLE
Sanity.io Create - Blog with Sapper package vulnerabilities

### ISSUE THREAD

**Issue by ScottTCodesBackup** [sanity-io/sanity#1699]
I recently use the sanity.io create project called Blog with Sapper and when I ran my first `npm install` some of the packages we're out of date. It is quite an easy fix to run `npm audit fix` but this probably shouldn't be needed from a fresh setup. 

Also if you setup with netlify you need to do manual deploys with the clear site cache option or it will fail on builds after the audit fix.

The ideal solution would be up to date packages from the time of creation.

I haven't checked any other create projects so they may also be effected. 

Link to page I used - https://www.sanity.io/create?template=sanity-io%2Fsanity-template-sapper-blog

**Comment by evenwestvang** [comment]
Thanks for raising the issue @ScottTCodes! We should schedule maintenance on this @jemmima.

**Comment by jesse-hsu** [comment]
Using the same page @ScottTCodes did from Sanity to create a project, I'm also running into the same issue with deployments requiring the clear cache option.

Automatic deployments have also failed with or without running `npm audit fix`

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
