### ISSUE TITLE
Allow custom validation rules to access image metadata.dimensions object

### ISSUE THREAD

**Issue by ciampo** [sanity-io/sanity#1703]
**Is your feature request related to a problem? Please describe.**
This covers cases when the image needs to be validated based on its `width` / `height` / `aspectRatio`.
Currently, when implementing a `custom(fn)` validation rule,  those properties are not available

**Describe the solution you'd like**
Make the `metadata` and in particular the `dimensions` objects available to custom validation functions

**Describe alternatives you've considered**
The best I could do was to add a `description` with the recommended image dimensions

**Additional context**
N/A

**Comment by kmelve** [comment]
Thanks for the feature request! We have also gotten requests to make it possible to validate images on dimensions prior to upload. Is that what you actually want?

**Comment by ciampo** [comment]
Hey Knut, yes I am referring to adding validation on image dimensions. Ideally in the CMS client before uploading

**Comment by wispyco** [comment]
Yes this would be ideal. In order fore certain design elements to appear best constraining images helps a lot. Hope this happens.

**Comment by owenandrews** [comment]
The validation also needs to fire when an existing image is selected from the media library. The below snippet works but of course fires on every document update as documented. Would be great if there was a way of running validations only when the field changes directly.

```js
Rule.custom(async (image) => {
  if (!image) return true;
  const res = await client.fetch(`*[_id == '${image.asset._ref}'][0]{metadata}`)
  return res.metadata.dimensions.aspectRatio == 1.4 ? true : "Image must have an aspect ratio of 1.4"
})
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
