### ISSUE TITLE
Description on Document schema

### ISSUE THREAD

**Issue by camjc** [sanity-io/sanity#1714]
**Is your feature request related to a problem? Please describe.**
I want to leave a description/note to clarify something for Authors before they use a content type (specifically around a model that is acting as an escape-valve and that is sub-optimal for authors to use in most cases).

**Describe the solution you'd like**
`description` key on a document gets read and displayed at the top of the form.

**Describe alternatives you've considered**
A dodgy hack of adding a checkbox field and using its name and description.

**Additional context**
@kmelve wants this too, and he's a pretty cool person.

**Comment by kmelve** [comment]
Haha! Well, thanks for the feature request! It makes sense that this should be possible. Stay tuned!

**Comment by camjc** [comment]
For me this is not a super-high priority, but seems like it should be quick(?) to implement and might be useful to more than just myself.

**Comment by vicbergquist** [comment]
me too!

**Comment by readeral** [comment]
Just pushed a basic change to kick the conversation off!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
