### ISSUE TITLE
Computed initial values

### ISSUE THREAD

**Issue by sheerun** [sanity-io/sanity#1717]
**Is your feature request related to a problem? Please describe.**

I'd like to have "slug" field that should default to lowercase and dashed version of name. For example if name is "Hello World", then slug should be "hello-world".

**Describe the solution you'd like**

Ability to compute initial value of some field based on another field

**Describe alternatives you've considered**

There are async initialisers for values, but they don't allow to access current value of other field.

**Comment by sheerun** [comment]
I guess templates are the answer

**Comment by kmelve** [comment]
Hi @sheerun! For the slug field, you can actually set that functionality with `options.source`. That will give you a generate button (since Sanity is real-time, changing the slug automatically could break things, so we made it an explicit action). https://www.sanity.io/docs/slug-type#source-9a89f442eaea

**Comment by sheerun** [comment]
Thank you! It would be nice if this was generalized to other fields as well (i.e. ability to specify source(s) and button to re-generate value)

**Comment by kmelve** [comment]
Totally see the use for it! I doubt that we will add this as functionality in the same way for the other fields, but we will make it easier for you to get this functionality with better abstractions for extensibility. Stay tuned!
