### ISSUE TITLE
Parametrized template is not rendered 

### ISSUE THREAD

**Issue by sheerun** [sanity-io/sanity#1718]
**Describe the bug**

If I create parametrized template, it is not displayed as one of the options to create some object. If I remove `parameters` array from template, everything is OK though.

**To Reproduce**

Just create custom type with parameters like so:

```
import T from '@sanity/base/initial-value-template-builder'

export default [
  ...T.defaults(),
  T.template({
    id: 'Figure',
    title: 'figure',
    schemaType: 'figure',
    parameters: [
      {
        name: 'name',
        title: 'Name',
        type: 'string'
      }
    ], 
    value: parameters => {
      if (parameters.name) {
        return {
          name: parameters.name,
          slug: parameters.name.toLowerCase().replace(/\s+/g, '-')
        }
      }
      return {}
    }
  })
]
```

In such case there is no new entry under "+" menu.

**Expected behavior**

Parametrized templates are supported

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**

@sanity/cli             0.147.8 (up to date)
@sanity/base            0.147.8 (up to date)
@sanity/components      0.147.9 (up to date)
@sanity/core            0.147.9 (up to date)
@sanity/default-layout  0.147.9 (up to date)
@sanity/default-login   0.147.0 (up to date)
@sanity/desk-tool       0.147.9 (up to date)
@sanity/vision          0.147.9 (up to date)

**Which versions of Node.js / npm are you running?**

6.13.4
v10.18.1

**Comment by rexxars** [comment]
We've yet to introduce the concept of "optional" parameters - right now we assume that templates with parameters require these to work, and since we don't have a user interface for providing these at the moment, they are removed from the `+` menus.

I understand this is quite confusing, especially given that parameters _are_ passed down to the `value` function even if the `parameters` are not defined.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
