### ISSUE TITLE
SVG Previews for file content-types

### ISSUE THREAD

**Issue by fandy** [sanity-io/sanity#1725]
![image](https://user-images.githubusercontent.com/19108762/74152319-0fe86c00-4bdc-11ea-8c11-b0a8527e0918.png)

Right now previews work for `image` types, but not `file types`. It would be great if this were consistent.

**I have not tested other images, but it's possible those do not preview too. Would be great to get parity on that.**

**Comment by kmelve** [comment]
Hi! Any reason you couldn't use `type: 'image'` for this? Then you'll get access to transforming those SVGs to++.

**Comment by fandy** [comment]
@kmelve I was creating a `media` field for `products` content-type, which was a collection of images (and potentially video). It felt more appropriate, but is not a big deal.

I guess the inconsistency comes from expecting `file` to behave similar to `image`. What's Sanity's rationale for having separate `image` and `file` types, instead of a universal `asset` type like in Contentful?

**Comment by kmelve** [comment]
We think it makes sense to treat them differently, because images go into our asset pipeline, gets annotated with image-specific metadata, and have on-demand transforms. With SVG you can, for example, get bitmaps on demand (`?format=png`) and even specify background color (`?format=png&bg=FFFFFF`). 

I will close this issue since you can solve this by using the `image` field.
