### ISSUE TITLE
Uploading images to Media manager

### ISSUE THREAD

**Issue by fandy** [sanity-io/sanity#1727]
**Is your feature request related to a problem? Please describe.**
As someone coming from Contentful, it's really frustrating to not be able to work with images easily in Sanity Studio. For example, the only way to upload images is from within a field. This means creating a new content type for each asset, when sometimes it's useful to just reference an asset on its own, like with a CDN asset.

**Describe the solution you'd like**
Be able to upload images from within the media manager or fields.

**Describe alternatives you've considered**
NO existing solution in Studio, which is very frustrating.

**Comment by evenwestvang** [comment]
Hi @fandy – can't promise quick resolution, but this is definitely something we are looking to address. We should allow access to the underlying asset, asset metadata fields (both read only like file size and writable ones like file name) as well as asset batch upload.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
