### ISSUE TITLE
blockContent (text editor bug) for URL input

### ISSUE THREAD

**Issue by snorthman** [sanity-io/sanity#1738]
**Describe the bug**

Errors that will never go away (along with some ugly console errors) when performing the following steps:

**To Reproduce**

Write any text, "abc", in the rich text editor (I'm using the default blockContent.js, which allows for URLs to be created). This error only occurs when there is no text in the editor yet.
Click on URL, input an invalid url ("qwe").
Backspace the text until the editor is clear of all text.

"Invalid URL" popup remains indefinitely, and
```
TypeError: Cannot read property 'text' of null
    at Commands$1.deleteBackwardAtRange (slate.es.js:6445)
    at Editor.command (slate.es.js:11284)
    at Editor$$1.command (slate-react.es.js:5379)
    at Editor$$1.command (react-hot-loader.development.js:714)
    at onCommand (slate.es.js:5849)
    at next (slate.es.js:11485)
    at onCommand (FocusNoScrollPlugin.js:24)
    at next (slate.es.js:11485)
    at onCommand (EnsurePlaceHolderBlockPlugin.js:22)
    at next (slate.es.js:11485)
```
in console.

**Expected behavior**

"Invalid URL" to clear away, no console errors.

**Which versions of Sanity are you using?**

@sanity/cli             1.148.1 (up to date)
@sanity/base            1.148.2 (up to date)
@sanity/components      1.148.1 (up to date)
@sanity/core            1.148.1 (up to date)
@sanity/default-layout  1.148.1 (up to date)
@sanity/default-login   1.148.1 (up to date)
@sanity/desk-tool       1.148.1 (up to date)
@sanity/vision          1.148.1 (up to date)

**Comment by kmelve** [comment]
Thanks for reporting! Managed to reproduce this, so definitively seems like a bug.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
