### ISSUE TITLE
Switch between multiple accounts when using CLI

### ISSUE THREAD

**Issue by johnnypea** [sanity-io/sanity#1767]
I would like to switch between multiple Sanity.io accounts.

Something like `sanity switch ACCOUNT` would be useful. We can store multiple login tokens and tag/name them.

It's not very practical to log in every time I need to work on different project.

**Comment by vicbergquist** [comment]
Thank you for submitting! This is a good idea and definitely sounds like something that will improve the DX 👍 We'll look into it 😊

**Comment by milosmalic** [comment]
@vicbergquist Is there a way to change account at all? Like manually deleting it in some config and running **init** again to authenticate?

**Comment by milosmalic** [comment]
> @vicbergquist Is there a way to change account at all? Like manually deleting it in some config and running **init** again to authenticate?

Found **sanity login** command, forget about the question :-)

**Comment by AyourElwazani97** [comment]
@milosmalic works for me thanks

**Comment by codingChewie** [comment]
Ran across this while learning about Sanity and had an issue when trying to build a project in the CLI and was getting an error regarding not being added when running the command:

```
sanity start
```

and after clicking the URL: http://localhost:3333

In the terminal, after the global installation of:

```
npm install -g @sanity/cli
```

If you've performed the `init` command:

```
sanity init
```

and you want to use a different account, in the terminal you can logout:

```
sanity logout 
```

then log into your other account.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by dardoschuster** [comment]
Hi
Have same problem want to use client sanity and when y run localhost:/3333 says not authorized but shows the client account that allows me to access from Chrome what happens ???
Thanks

**Comment by dardoschuster** [comment]
Sorry I am using Github
