### ISSUE TITLE
Support for folders in the "select image" module

### ISSUE THREAD

**Issue by remisture** [sanity-io/sanity#1775]
It's hard to get an overview within the image module with lots of images, so it would be nice to have some way of organizing the images, for instance in a folder structure.

**Comment by vicbergquist** [comment]
There are many ways we'd like to improve the default image uploading and browsing experience, so please stay tuned. We appreciate the feedback! 😃 Meanwhile, maybe this plugin can be of help: https://www.sanity.io/plugins/sanity-plugin-media

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
