### ISSUE TITLE
Image field type can't be validated as "required"

### ISSUE THREAD

**Issue by Grsmto** [sanity-io/sanity#1816]
**Describe the bug**
Required validation does not seem to work on `image` field type.

**To Reproduce**

1. Define an image object with a validation rule:

```
export default {
  name: "imageWithCredits",
  title: "Image",
  type: "image",
  validation: Rule => [Rule.required().error("A value is required!")],
  fields: [
    {
      name: "attribution",
      type: "localeString",
      title: "Attribution",
      options: {
        isHighlighted: true,
      },
    },
    {
      name: "style",
      type: "string",
      title: "Alignment",
      options: {
        list: [
          { title: "Left", value: "left" },
          { title: "Right", value: "right" },
        ],
        layout: "radio",
        direction: "horizontal",
        isHighlighted: true,
      },
    },
  ],
};

```
2. Go to the studio and leave the field empty
3. Publish the document

**Expected behavior**

User should not be able to publish a document with a missing Image field if a validation required rule is in place.

**Screenshots**
As seen in the following screenshot, field is left empty but no validation error appear:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/527559/77930150-e5806a00-7280-11ea-91ff-a0e28ee42e16.png">

**Which versions of Sanity are you using?**

"@sanity/core": "^1.149.4",
@sanity/cli version 0.147.8

**Additional context**

As seen in this Slack thread (https://app.slack.com/client/T9Y440GN8/C9Y9GF1QD/thread/C9Z7RC3V1-1583795737.218300) seems like the issue is tracked somewhere (but not here apparently).

**Comment by vicbergquist** [comment]
Yes, this issue is also in our internal tracker, but thank you for reporting nevertheless!

**Comment by vicbergquist** [comment]
Hi there! I was looking into this, but I'm not able to reproduce it. Can you please test to see if it's working now by upgrading your Studio? If it's still not working for you, can you please share the schema where you're using the `imageWithCredits` type?

**Comment by Grsmto** [comment]
@vicbergquist hey! So I just tested now with the latest version and it seems to work fine!
Thanks!

**Comment by vicbergquist** [comment]
@Grsmto Thank you for checking! That's awesome! 🎉

**Comment by kno-raziel** [comment]
The required validation works partially, I was having this exact same issue and here are my finding in case some else experience the same.

Having a schema like the following, the required validation will works as expected, a image must be selected.

``` Javascript
import { FaImage } from 'react-icons/fa';

export default {
  name: 'img',
  title: 'Image',
  type: 'image',
  validation: (Rule) => Rule.required(),
  icon: FaImage,
  options: {
    hotspot: true,
  },
}
```

Adding optional field to the schema, like the following example will break the validation or at least that's what it seems.

```Javascript
import { FaImage } from 'react-icons/fa';

export default {
  name: 'img',
  title: 'Image',
  type: 'image',
  validation: (Rule) => Rule.required(),
  icon: FaImage,
  options: {
    hotspot: true,
  },
  fields: [
    {
      name: 'caption',
      type: 'string',
      title: 'Caption',
      options: {
        isHighlighted: true,
      },
    },
  ],
};
```
With just filling the optional field, will set the validation as valid even when no image have been selected wich in my opinion is not correct because will allow the creation of a new entry without actually having an image.

![image](https://user-images.githubusercontent.com/8211946/179367324-0d51ad15-9d78-4875-a128-b4b43917dd94.png)

And I suppose that happens because the Rule.required, just validate the existence of the image object and is not validating if the asset field exist in the object.

```Javascript
{
  "_type": "img",
  "caption": "asd",
}
```

To solve this I have ended using a custom validation, to validate if an image have been select.

```Javascript
export default {
  name: 'img',
  title: 'Image',
  type: 'image',
  validation: (Rule) => [
    Rule.custom((value) => {
      return value && value.asset
        ? true
        : {
            message: 'An Image is Required!',
          };
    }),
  ],
  codegen: { required: true },
  icon: FaImage,
  options: {
    hotspot: true,
  },
  fields: [
    {
      name: 'caption',
      type: 'string',
      title: 'Caption',
      options: {
        isHighlighted: true,
      },
    },
  ],
};

```

Result:

![image](https://user-images.githubusercontent.com/8211946/179367670-66fd1320-d806-4e84-ba07-4c7ee3718efc.png)


Regards,
