### ISSUE TITLE
Improve local developer setup documentation

### ISSUE THREAD

**Issue by zanedev** [sanity-io/sanity#1838]
**Is your feature request related to a problem? Please describe.**
Can we get clear instructions on how to run sanity locally with a sample project?  I tried running the watcher and npm linking packages from my other studio project and nothing is working.  It would be nice to be able to debug these things ourselves and help contribute to the core.

**Describe the solution you'd like**
Better developer setup and running locally docs.

**Describe alternatives you've considered**
Tried npm linking myself no luck not sure if that's even the proper way to do that so don't want to waste anymore time on it.

**Comment by kmelve** [comment]
Hi! Sorry for your trouble – making it easier and have more documentation around how to start and develop on the studio code is absolutely something that we have plans to improve. 

Meanwhile, you're more than welcome to ask and troubleshoot with us on [slack.sanity.io](https://slack.sanity.io).

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
