### ISSUE TITLE
Better user land traceable error messages

### ISSUE THREAD

**Issue by zanedev** [sanity-io/sanity#1841]
**Is your feature request related to a problem? Please describe.**
I have been working with sanity for a few weeks now and I get random errors in the console that don't trace to any userland code. Some of them appear as notices in the app in dev **and** prod although i see no affected functionality.

**Describe the solution you'd like**
Please always indicate what userland component/code is in the stack trace, something an id or anything but the useless traces we get now.

**Describe alternatives you've considered**
Looking at the trace none of it my code.

**Additional context**
Examples attached.
![image (5)](https://user-images.githubusercontent.com/817344/79081594-d0b9c280-7cd3-11ea-8cc4-483e5a672171.png)
![image (4)](https://user-images.githubusercontent.com/817344/79081595-d1eaef80-7cd3-11ea-880c-8a27d32044bc.png)

**Comment by zanedev** [comment]
More examples

![image](https://user-images.githubusercontent.com/817344/79081915-753d0400-7cd6-11ea-9395-5ece3ff0ca1f.png)

**Comment by vicbergquist** [comment]
Thanks for reporting! Improving error messaging is definitely on our list of todos and we appreciate the feedback. Will be sure to add this to our internal tracker, thank you!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
