### ISSUE TITLE
"reference" field name make graphql deploy throw an error

### ISSUE THREAD

**Issue by sirojinadias** [sanity-io/sanity#1855]
**Describe the bug**

Unable to create a field with the name "reference", it makes `sanity graphql deploy` throw this error :
```
Error: "" did not match name pattern (/^[_A-Za-z][_0-9A-Za-z]*$/) (context: root type)
    at ~/matcha/studio/node_modules/@sanity/core/lib/actions/graphql/deployApiAction.js:128:31
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (~/matcha/studio/node_modules/@sanity/core/lib/actions/graphql/deployApiAction.js:3:103)
    at _throw (~/matcha/studio/node_modules/@sanity/core/lib/actions/graphql/deployApiAction.js:5:291)
```

**To Reproduce**

1. Create a sanity document with a `reference` field
```
export default {
  name: 'myDocument',
  type: 'document',
  fields: [
    {
      name: 'reference',
      type: 'string'
    }
  ]
}
```
2. Studio will start with but when you want to `sanity graphql deploy`, it will throw with the above error.
3. Rename `reference` to `ref` and it will be ok.

**Expected behavior**

GraphQL API deployed.

**Which versions of Sanity are you using?**

```
@sanity/cli              1.149.9 (up to date)
@sanity/base            1.149.10 (up to date)
@sanity/cli              1.149.9 (up to date)
@sanity/components      1.149.10 (up to date)
@sanity/core            1.149.12 (up to date)
@sanity/dashboard       1.149.10 (up to date)
@sanity/default-layout  1.149.10 (up to date)
@sanity/default-login   1.149.11 (up to date)
@sanity/desk-tool       1.149.10 (up to date)
```

**What operating system are you using?**
OSX 10.13.6

**Which versions of Node.js / npm are you running?**
NPM : 6.14.4
Node : v13.12.0

**Comment by saasen** [comment]
This issue is pretty old. Are you still running into this issue in `gen3`?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
