### ISSUE TITLE
New Interface schema type

### ISSUE THREAD

**Issue by djfarly** [sanity-io/sanity#1876]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to reference a document, but you don't really care about its type - you only care about it having a certain structure or rather implementing certain fields.
[Coming from a graphql heavy background this kinda feels like bread and butter.](https://graphql.org/learn/schema/#interfaces) Thus its kinda frustrating having to manually list all types something can reference.

**Describe the solution you'd like**
1. Introduce a new interface schema type
```typescript
    {
      type: 'interface',
      name: 'linkableDocument',
      title: 'Linkable Document',
      fields: [
        { type: 'slug', name: 'slug' },
        { type: 'string', name: 'title' },
      ],
    },
```

2. Allow documents (and objects?!) to implement interfaces
```typescript
    {
      type: 'document',
      name: 'page',
      implements: ['linkableDocument'],
      title: 'Page',
      fields: [
        { type: 'slug', name: 'slug', title: 'Slug' },
        { type: 'string', name: 'title': title: 'Title' },
        { type: 'string', name: 'something': title: 'Something!' },
      ],
    },
```

3a. Error if the implementation is not complete or mismatching
```typescript
    {
      type: 'document',
      name: 'blogPost',
      implements: ['linkableDocument'],
      title: 'Blog Post',
      fields: [
        { type: 'string', name: 'slug', title: 'Slug' }, // error: field "slug" needs to be of type "slug"
        // error: blogPost must implement field "title" of type "string"
      ],
    },
```

3b. Alternatively use interface field declarations as implicit field declarations
```typescript
    {
      type: 'document',
      name: 'blogPost',
      implements: ['linkableDocument'],
      title: 'Blog Post',
      fields: [
        { type: 'slug', name: 'slug', title: 'Path' }, // overrides interfaces "slug" field (b/c type matches)
        // field "title" is used from interface definition
      ],
    },
```

4. Allow references to use interface types
```typescript
    {
      type: 'rerefence',
      name: 'internalLink',
      title: 'Internal Link',
      to: [{type: 'linkableDocument'}]
    },
```

5. The reference interface in the studio should now allow to select documents of all types that implement `linkableDocument`

6. Groq needs some way to handle interfaces - i'm not familiar enough with Groq to say anything about that

7. GraphQL can simply use GraphQL interfaces to handle interface references.
```graphql
link {
  _type
  # interface fields
  slug
  title
  
  ... on Page {
    # fields for specific implementations
    something
  }
}
```

**Describe alternatives you've considered**
Adding all types referenced by a reference field manually. That only work if you know all "implementors" though. In our use case a plugin defines the interface and the reference-field. User code should be able to add implementations that can be referenced though.

**Additional context**

[Slack thread](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1589031956127900)

Sorry for all the feature requests today :) Let me know if I can help pushing things forward. 👋

**Comment by djfarly** [comment]
I thought about it some more - using version 3b. above makes a little bit more sense to me (or seems more convenient, I guess 🙈), especially if you allow interfaces on any object type.

**Comment by aaronadamsCA** [comment]
It really feels like this feature would make Sanity the perfect companion for Gatsby. I'm really starting to feel the pain of working without GraphQL interfaces; this would make my life so much easier.

We're all devs here, so I won't go into all of the reasons composition would be massively important for our schemas. But I do want to offer a small tactical insight into the day-to-day of trying to set up a Studio project for scalability and maintenance.

This is a small part of my Sanity schema:

![image](https://user-images.githubusercontent.com/1505561/87878607-a15ad600-c9e5-11ea-885e-294f04109709.png)

`city.place` can be of type `province` or `country`:

```js
{
  type: "reference",
  name: "place",
  to: [{ type: "province" }, { type: "country" }],
},
```

This translates to this part of my GraphQL schema:

```graphql
union CountryOrState = Country | Province
```

And now here's how I need to ask for the contents of `city.place`:

```graphql
{
  sanityCity {
    place {
      __typename
      ... on SanityProvince {
        id
        title
      }
      ... on SanityCountry {
        id
        title
      }
    }
  }
}
```

And I'm completely unable to, say, filter `city.place` by `title`, since without a shared interface I don't get any filter/sort capabilities.

There's work for gatsby-source-sanity to do to improve this, but I don't think they could get all the way there without Sanity bringing some real support for interfaces.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
