### ISSUE TITLE
Ability to backup content without being inside the project doesn't work as you might expect

### ISSUE THREAD

**Issue by antony** [sanity-io/sanity#1896]
**Describe the bug**

I want to run a backup script to back-up my content, as part of a cron job. I don't want that script to check-out my entire sanity project.

The docs appear to indicate that you can simply:

```
SANITY_AUTH_TOKEN=xyz123 npx @sanity/cli dataset export production production.ndjson
```

However this command needs to be run inside your full project, otherwise it doesn't work.

**To Reproduce**

1. Run:
```
SANITY_AUTH_TOKEN=xyz123 npx @sanity/cli dataset export production production.ndjson
```
from outside a Sanity project

**Output**

```
Error: "dataset" is not available outside of a Sanity project context.
Run the command again within a Sanity project directory, where "@sanity/core"
is installed as a dependency.
    at O.runCommand (~/.npm/_npx/587165/lib/node_modules/@sanity/cli/bin/sanity-cli.js:3488:2119)
    at t.exports (~/.npm/_npx/587165/lib/node_modules/@sanity/cli/bin/sanity-cli.js:2106:2296)
```

**Expected behavior**

I expect to be able to run this command without having the entire kitchen sink checked out :) There's no point in having `npx` if you need everything checked out locally anyway.

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

npx will always check out the latest version

```
@sanity/cli  1.149.13
```

**What operating system are you using?**

Ubuntu 20.04

**Which versions of Node.js / npm are you running?**

```
6.14.4
v14.0.0
```

**Comment by jakeadamsiii** [comment]
Hey mate, facing the same issue, do you have a solution? 

Cheers!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
