### ISSUE TITLE
React console warnings in fresh project: Cannot update a component from inside the function body of a different component.

### ISSUE THREAD

**Issue by ryan-reach** [sanity-io/sanity#1909]
**Describe the bug**

Console shows warnings from React

**To Reproduce**

1. sanity init
2. choose blog starter
3. run studio
4. selecting different document types triggers the warning in the console

**Expected behavior**

No warnings

**Screenshots**
<img width="410" alt="Screen Shot 2020-06-03 at 8 59 23 AM" src="https://user-images.githubusercontent.com/60242214/83653655-47a76500-a579-11ea-82c7-8bfaed951d82.png">

**Which versions of Sanity are you using?**

@sanity/cli             1.149.13 (up to date)
@sanity/base            1.149.15 (up to date)
@sanity/components      1.149.15 (up to date)
@sanity/core            1.149.13 (up to date)
@sanity/default-layout  1.149.15 (up to date)
@sanity/default-login   1.149.11 (up to date)
@sanity/desk-tool       1.149.15 (up to date)
@sanity/vision           1.149.0 (up to date)

**What operating system are you using?**

macOs 10.15.4

**Which versions of Node.js / npm are you running?**

6.14.4
v12.17.0

**Additional context**

n/a

**Security issue?**

no

**Comment by Sergix** [comment]
Same issue here.

**Comment by vicbergquist** [comment]
Thank you for reporting! We are aware of the issue and will look into it 👍

**Comment by bradley** [comment]
Is it possible this is also what's causing the "flash" when navigating between editor pages?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
