### ISSUE TITLE
Theme customization is not possible for StyleSelect:hover

### ISSUE THREAD

**Issue by JohnatanNorman** [sanity-io/sanity#1921]
**Describe the bug**

The value of hover is relying on --white variable
https://github.com/sanity-io/sanity/blob/master/packages/%40sanity/components/src/selects/styles/StyleSelect.css#L26

**To Reproduce**

1. Make dark theme (?)

**Expected behavior**

The value should be exposed as separate variable or rely on --selected-item-color for example.

**Screenshots**
![Screen Shot 2020-06-13 at 9 32 09 PM](https://user-images.githubusercontent.com/41754671/84577014-816e3c00-adc1-11ea-8b22-9eec0bf561b4.png)

**Which versions of Sanity are you using?**

```sh
@sanity/cli             1.149.16 (up to date)
@sanity/base            1.149.16 (up to date)
@sanity/color-input     1.149.16 (up to date)
@sanity/components      1.149.16 (up to date)
@sanity/core            1.149.17 (up to date)
@sanity/default-layout  1.149.16 (up to date)
@sanity/default-login   1.149.16 (up to date)
@sanity/desk-tool       1.149.16 (up to date)
@sanity/image-url       0.140.19 (up to date)
```

**Comment by vicbergquist** [comment]
Thanks for reporting! We know it can be hard to customise all parts of the Studio and are working on improving this experience and making it easier 👍

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
