### ISSUE TITLE
CLI: sanity graphql list is not reporting back the correct name

### ISSUE THREAD

**Issue by torbjokv** [sanity-io/sanity#1927]
**Describe the bug**

When creating a graphql endpoint for a dataset with a name on the form "hello-123-456", the `sanity graphql list` command is not reporting back the correct name.

**To Reproduce**

```
$ sanity dataset create hello-123-456 --no-playground --visibility public
  Dataset created successfully

$ sanity graphql deploy --dataset hello-123-456 --no-playground
  Dataset: hello-123-456
  Tag: default
  GraphQL API deployed to:
  https://XXXXX.api.sanity.io/v1/graphql/hello-123-456/default

$ sanity graphql list | grep hello -A 3
  184.  Dataset:     hello                      # here I would expect the full hello-123-456
    Tag:         123                            # here I would expect default
    Generation:  gen2
    Playground:  false

$ sanity graphql undeploy --dataset hello --tag 123
  ? Are you absolutely sure you want to delete the GraphQL API connected to the "h
  ello" dataset, tagged "123"? (y/N) Yes       # does not work

$ sanity graphql undeploy --dataset hello-123-456
  ? Are you absolutely sure you want to delete the current GraphQL API connected t
  o the "hello-123-456" dataset? (y/N) Yes     # does work
```

**Expected behavior**

`sanity graphql list` should return the correct dataset name with default tag.

**Which versions of Sanity are you using?**

@sanity/cli                     1.149.13 (latest: 1.149.16)
@sanity/base                    1.149.15 (latest: 1.149.16)
@sanity/block-content-to-react     2.0.7 (up to date)
@sanity/block-tools              1.149.4 (latest: 1.149.16)
@sanity/cli                     1.149.16 (up to date)
@sanity/client                  1.149.13 (latest: 1.149.16)
@sanity/components              1.149.15 (latest: 1.149.16)
@sanity/core                    1.149.13 (latest: 1.149.17)
@sanity/default-layout          1.149.15 (latest: 1.149.16)
@sanity/default-login           1.149.11 (latest: 1.149.16)
@sanity/desk-tool               1.149.15 (latest: 1.149.16)
@sanity/google-maps-input        1.149.7 (latest: 1.149.16)
@sanity/production-preview       1.149.0 (up to date)
@sanity/vision                   1.149.0 (latest: 1.149.16)

**What operating system are you using?**

Windows 10 / git bash

**Which versions of Node.js / npm are you running?**

npm: 6.12.0
node: v12.13.0

**Comment by kmelve** [comment]
This indeed looks like a bug – thanks for reporting! I'll bring it back to the team 👍

**Comment by torbjokv** [comment]
> This indeed looks like a bug – thanks for reporting! I'll bring it back to the team 👍

Thanks! I have now over 200 graphql endpoints and no way to delete them since I'm missing the full name from graphql list 😅

**Comment by saasen** [comment]
I have reproduced this. I'm working on a fix. Thanks for reporting, @torbjokv!

**Comment by saasen** [comment]
Not only is the dataset name wrong, but it gives the wrong tag as well.

**Comment by saasen** [comment]
I looked into this more thoroughly and the fix isn't as easy as I wanted it to be. The APIs are generated the way you specify, but the `list` option doesn't give you the correct information, which is very confusing of course.

A temporary workaround for this is to not use `-` as a separator for datasets and tags.

**Comment by torbjokv** [comment]
Are there any way to use the api directly to retrieve the full name, so that I can delete my endpoints?

**Comment by saasen** [comment]
The problem is in the backend. That's partially why it's hard to fix it right now. You can delete your endpoints with the CLI as long as you give it the full name. That said, you probably don't know the name of all of your endpoints in your head. If you need a list of all of them, we are happy to give you that. I'll ask if we can prioritize this.

**Comment by roffelsaurus** [comment]
There is another problem here.

```
$ sanity graphql undeploy --dataset hello-123-456
  ? Are you absolutely sure you want to delete the current GraphQL API connected t
  o the "hello-123-456" dataset? (y/N) Yes     # does work
```

This works completely, but only for gen2 apis.

I have two hyphenated gen1 apis which are impossible to remove from the api list in any way. The actual endpoints are removed from the web, but not from the graphql list. So there must be some data inconsistency in your backend.

**Comment by saasen** [comment]
@roffelsaurus: Thank you for this. Could you open a new issue for this? We can then link them together as they seem related.

**Comment by cdierkens** [comment]
Any update on this issue? Even if I could see the list on the sanity.io UI that would be enough to know what tags to delete.

**Comment by saasen** [comment]
No, we haven't gotten around to fix this yet, sadly. We would need to change how we store the APIs in the backend to fix this. The problem is not how we show them in the console/UI, it's in how we store it in the backend that makes it hard to know exactly what the name is.

I'll discuss this internally right away. We have some plans on improving other parts of this as well, and might postpone it to do it together with that.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
