### ISSUE TITLE
sanity start reports wrong dataset

### ISSUE THREAD

**Issue by aaronadamsCA** [sanity-io/sanity#1945]
**Describe the bug**

`sanity start` reports `Using dataset from environment config (production)` even though I'm using the `"development"` dataset. Sanity does use the correct dataset on startup; this is just a reporting error, albeit a confusing one.

**To Reproduce**

My (abridged) sanity.json:

```json
{
  "root": true,
  "project": {
    "name": "xxx"
  },
  "api": {
    "projectId": "xxx",
    "dataset": "development"
  },
  "plugins": [...],
  "env": {
    "production": {
      "api": {
        "dataset": "production"
      }
    },
    "development": {
      "plugins": ["@sanity/vision"]
    }
  },
  "parts": [...]
}
```

I don't have any env vars in my dev environment.

**Expected behavior**

Sanity should report it's using the `"development"` dataset, because it is.

**Which versions of Sanity are you using?**

```text
@sanity/cli                1.149.16 (latest: 1.149.18)
@sanity/base               1.149.16 (latest: 1.149.18)
@sanity/cli                1.149.16 (latest: 1.149.18)
@sanity/components         1.149.16 (latest: 1.149.18)
@sanity/core               1.149.17 (latest: 1.149.18)
@sanity/dashboard          1.149.16 (latest: 1.149.18)
@sanity/default-layout     1.149.16 (latest: 1.149.18)
@sanity/default-login      1.149.16 (latest: 1.149.18)
@sanity/desk-tool          1.149.16 (latest: 1.149.18)
@sanity/google-maps-input  1.149.16 (up to date)
@sanity/vision             1.149.16 (up to date)
```

**What operating system are you using?**

Ubuntu on Docker on WSL 2 on Windows 10.

**Which versions of Node.js / npm are you running?**

NPM 6.14.4
Node.js v12.16.3

**Comment by johant87** [comment]
Almost a year later and I seem to have still the same issue on the latest version of Sanity.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
