### ISSUE TITLE
Punctuation stripped when pasting from Google Docs

### ISSUE THREAD

**Issue by ghost** [sanity-io/sanity#1956]
**Describe the bug**

There is certain punctuation that Google Docs transforms. For example:

`...` becomes `…` (the second one is a single special character)
`'` becomes `’`

These are not output on the front end.

I attempted to implement my own on paste handler but couldn't figure out what the was the expected return value. It would be good to get some additional documentation around this.
Here is the existing documentation that I followed: https://www.sanity.io/docs/customization#custom-paste-handling-dbbec5ed1782

**To Reproduce**

Steps to reproduce the behaviour:

1. Open this Google Doc: https://docs.google.com/document/d/1xKBEbwy93m8YbXnY7HoFXUCM65bpj1KrVwz8PLnwMHA/edit?usp=sharing
2. Copy the text
3. Paste into a text field
4. See that text is removed

**Expected behaviour**

I think it would be ideal that these characters are transformed back. Something like the following:
```
text.replace(/[\u00A0-\u9999<>\&]/gim, (i) => `&#${i.charCodeAt(0)};`)
```
Or perhaps they should remain as special characters but be displayed on the front end.

**Screenshots**
Displays in the editor but not on the front end:
![image](https://user-images.githubusercontent.com/41870207/88616443-83712d80-d0d7-11ea-8b20-262ebb488f2a.png)

![image](https://user-images.githubusercontent.com/41870207/88616718-3b9ed600-d0d8-11ea-9817-6bd1257df7ae.png)

**Which versions of Sanity are you using?**

@sanity/cli  1.149.16 (latest: 1.149.18)

**What operating system are you using?**
macOS Catalina 10.15.5

**Which versions of Node.js / npm are you running?**

6.14.4
v10.16.3

**Comment by vicbergquist** [comment]
Hi and thank you for reporting! I've added this to our internal tracker 👍

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
