### ISSUE TITLE
Stop focusing on the first document field if search field is already selected

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#1966]
**Is your feature request related to a problem? Please describe.**
We see a lot of unintentional changes in the first field of documents made by editors and finally figured out the reason.

When loading Sanity, they often very quickly click in the search field and start typing. If they've opened a page showing a form editor, loading the form might still be ongoing, and when loading finishes the first field in the form editor will get focus.

This often leads to parts of the search criteria being entered in the first form field, if the user has already started typing in the search field. Sometimes the editors forget to clean this up, or just get confused and don't notice, going back to the search field.

This leads to a lot of DRAFT documents with erroneous content in the first field.

**Describe the solution you'd like**
If the search field is already in focus (having been selected), don't move focus to the first form field.

**Comment by vicbergquist** [comment]
Thanks for reporting! I can understand the frustration with this one ☝️

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
