### ISSUE TITLE
Sanity Studio batch loading adds documents at arbitrary locations

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#2000]
**Describe the bug**

When viewing a list of documents in the Studio, the studio will batch load the documents, adding new documents as you scroll down.

However, it seems this mechanism might not properly take sort order into account, as our Editors report documents being added in arbitrary locations in the list when they scroll. Our current theory is that the loading always happens with the default sort order, which seems to be "last changed", while if the editors switch to "alphabetic sorting" in our list, the error starts occurring.

Whet they describe to me is the first  batch of document loaded and listed will not contain all documents in the A-B range, but when the scroll further down the alphabet, new documents in the A-B range will be loaded and will appear up above so they must scroll back up to see them.

**Expected behavior**

Sorting should be taken into account when loading, so that documents added to the list should only ever be added to the bottom of the list.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
