### ISSUE TITLE
Issue with import/export table data with empty value

### ISSUE THREAD

**Issue by alexander-y** [sanity-io/sanity#2051]
**Describe the bug**
When we do import/export data between different dataset, lines in tables look shifted. We use plugin Datatable for it
https://www.sanity.io/plugins/sanity-plugin-datatable
If the cell does not contain any value, after import/export data to a new dataset, the table looks like missing one cell. 

**To Reproduce**

1. Add 2 rows for a table
2. Add 2 columns 
3. Fill in with any data all fields except the first column in the first row
4. Export data from the current dataset
5. Import data to the new dataset

Error: The first row is shifted left. 

**Expected behavior**
Expected behavior: The first row should not be shifted. The table should like the same as before import.

**Screenshots**
After import
![image](https://user-images.githubusercontent.com/11156512/95757660-1a4d8f00-0cb0-11eb-95c4-466ed606a2cd.png)

Should be
![image](https://user-images.githubusercontent.com/11156512/95757552-f68a4900-0caf-11eb-9010-6d7a3e6a3d5a.png)

**Which versions of Sanity are you using?**

@sanity/cli                2.0.1 (up to date)
@sanity/base               2.0.2 (up to date)
@sanity/color-input        2.0.1 (up to date)
@sanity/components         2.0.2 (up to date)
@sanity/core               2.0.1 (up to date)
@sanity/default-layout     2.0.2 (up to date)
@sanity/default-login      2.0.1 (up to date)
@sanity/desk-tool          2.0.2 (up to date)
@sanity/image-url       0.140.19 (up to date)
@sanity/vision             2.0.1 (up to date)
**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

6.14.6                                                                                                                                                          
v12.18.3

**Additional context**

I saw that issue with both plugins
https://www.sanity.io/plugins/sanity-plugin-datatable
https://www.sanity.io/plugins/sanity-plugin-table

If I put space in the table cell, the table looks ok after import/export operation.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
