### ISSUE TITLE
Dynamically populating fields to a document

### ISSUE THREAD

**Issue by coodoo** [sanity-io/sanity#2060]
**Is your feature request related to a problem? Please describe.**

I was wondering is it possible to dynamically populate a document with different fields based on data from another document.

**Describe the solution you'd like**

Have a look at the image below.

Let's say we have two kind of documents, `Template` and `Page`, user first create two templates, each with different number of fields (say texts and images).

User then create a new page (2nd image below), and the first thing to do on that page is to select a template, in this case `template_1` was selected, then all three fields defined in `template_1` will be populated on current page (providing initial value at the same time), so that user can enter new values for each of them.

![New Mockup 1](https://user-images.githubusercontent.com/325936/95980115-44898300-0e4f-11eb-8009-b0d7bdec58ca.png)

**Describe alternatives you've considered**
I have considered `initial value with template builder` to no avail.

**Additional context**

The goal here is to allow users creating indefinite number of pages based on multiple predefined templates.

Thoughts?

**Comment by rudfoss** [comment]
I know this is old, but I've stumbled across it while looking for a similar solution and eventually had to write something custom. It's not an exact match for what you want, but it may spark some ideas: https://github.com/rudfoss/sanity-dynamic-fields

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
