### ISSUE TITLE
Compact placeholder string using blurhash

### ISSUE THREAD

**Issue by nullhook** [sanity-io/sanity#2074]
Currently the `lqip` placeholder strings are base64 and are too long. 

Perhaps an alternative compact version could be used by implementing [blurhash](https://github.com/woltapp/blurhash).

![image](https://user-images.githubusercontent.com/8665427/96360122-9aa04400-1137-11eb-9ac2-75c0efb83657.png)

**Comment by hdoro** [comment]
I was thinking the same, Taher! Especially because blurhash's low fidelity is more pleasing on the eye than `lqip`

After some thought, though, I realized that **blurhash needs a client-side decoder for expanding their hashes into image data**, which makes it hard for users of a general purpose solution like Sanity and may even defeat the purpose of smaller strings by adding JS overhead. I don't know, after I went over the hype I realized this wouldn't be as important as I thought it might be.

Regardless of whether the team decide to implement this, in the meantime you could always **run an encoder function when someone uploads an image** (maybe through a webhook or directly inside the studio?), then save that to the image's document metadata. You could then do a `select(metadata.blurhash, metadata.lqip)` query in GROQ to get the one that is available and use it in your front-end as needed 😉 

Hope this helps and let us know if you do end up implementing it o/

**Comment by geball** [comment]
Thanks again for this request, @nullhook. I'll close this issue as `blurhash` was added in [v2.21.3](https://github.com/sanity-io/sanity/releases/tag/v2.21.3). 🎉

**Comment by kerns** [comment]
If I can save anyone 10 minutes – it is implemented as `blurHash`, at least in v3.
