### ISSUE TITLE
Nitpick: Remove fieldset heading space if not used

### ISSUE THREAD

**Issue by rix1** [sanity-io/sanity#2084]
**Is your feature request related to a problem? Please describe.**
I love the fieldsets and the ability to create n-column layouts 👏  However, I noticed that if I omit the `fieldset.title` the studio still applies some extra space due to the title div with no children.

**Describe the solution you'd like**
I'd like to get the [empty div removed](https://user-images.githubusercontent.com/2470775/96828604-3da6d580-1438-11eb-9983-b3d5b5346671.png) to tidy up a bit.

| Uneven spacing due to missing `title` | Removed empty divs 💅  |
|--------|-------|
|   ![localhost_3333_staging_desk_jobListings;norwegianJobListings;4a465a27-ad58-44ca-a164-8b31d30444bd (1)](https://user-images.githubusercontent.com/2470775/96828535-21a33400-1438-11eb-8f6c-a94787b58a3e.png)  |  ![localhost_3333_staging_desk_jobListings;norwegianJobListings;4a465a27-ad58-44ca-a164-8b31d30444bd](https://user-images.githubusercontent.com/2470775/96828522-1e0fad00-1438-11eb-996f-f2912fc80406.png)   |

**Describe alternatives you've considered**
Accept uneven spacing between fields/fieldsets and make my inner designer-eyes bleed (jk 🙃 ) 

**Additional context**
Here's a snippet of my document schema:
```js
export default {
  name: JOB_LISTING_TYPE,
  title: 'Job listing',
  icon: ClipboardIcon,
  type: 'document',
  fieldsets: [
    {
      name: groups.dates,  // <-- notice no title 
      options: {
        columns: 2,
      },
    },
    {
      title: 'Location',
      name: groups.location,
      description: 'Affiliation to office, e.g. Oslo, Norway',
      options: {
        columns: 2,
      },
    },
  ],
  //...
}
```

**Comment by vicbergquist** [comment]
Hi Rikard! Simply removing the "empty" div when there's no title would make you lose both presence and validation markers :/
But I think I have a solution and will look into it 😊 Thank you for reporting!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
