### ISSUE TITLE
Ability to automatically generate a thumbnail preview for PDF file types

### ISSUE THREAD

**Issue by nakedgremlin** [sanity-io/sanity#2091]
**Is your feature request related to a problem?**

We are always dealing with a multimedia gallery slideshows, containers, etc that have a mix of images and videos. For things like Mux video, we have been able to leverage their thumbnails for this purpose. Recently we are encountering situations where PDF files are requested too. It'll be great if Sanity can provide an image thumbnail for PDF files for this purpose. 

**Describe the solution you'd like**

Ability to pull a thumbnail from a PDF uploaded to Sanity, identical to what we can do with images.

**Describe alternatives you've considered**

We used [react-pdf](https://react-pdf.org/) for a run-time implementation, but it provided very resource heavy.

We are now planning to build out a Cloud function that will accept the PDF file and send back the image, which we would then send back to Sanity in a hidden field for that asset type. It's not the best solution, but seems to be the only way right now. The consumption on the frontend will be to look for the hidden field if the file is a "PDF" file.

**Comment by nakedgremlin** [comment]
Another alternative we considered was offloading the PDF image generation to something like Cloudinary (as they do generate thumbnails on PDF files), but that started to feel like too many strings holding this one together. It would be wonderful for this to be provided by Sanity direct.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
