### ISSUE TITLE
Can't query each item inside "type: block"

### ISSUE THREAD

**Issue by gilbertlucas46** [sanity-io/sanity#2093]
How do you query an image when its inside a `type: block` ?

I want to query the image like this 👇
```
asset {
	fluid(maxWidth: 700) {
		...GatsbySanityImageFluid
	}
}
```

But there's no option to get it like that, this is all I can do 👇
![image](https://user-images.githubusercontent.com/5719346/97134715-1c701d00-1789-11eb-94fc-fe6887ac253f.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/5719346/97134881-a4562700-1789-11eb-8559-b45a444071a3.png)

![image](https://user-images.githubusercontent.com/5719346/97134388-0f9ef980-1788-11eb-9aa2-c5d48501b263.png)
![image](https://user-images.githubusercontent.com/5719346/97134766-488b9e00-1789-11eb-9bf3-9d8bb466ccd5.png)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
