### ISSUE TITLE
GraphQl Data not fetching right content

### ISSUE THREAD

**Issue by Tarshh** [sanity-io/sanity#2095]
Hello,
I'm trying to query my new image. 
I uploaded it on the Sanity desk and published. Yet I'm not getting the correct Image.
![image](https://user-images.githubusercontent.com/47401362/97417541-1b192e80-1908-11eb-97f9-37dcc72493cb.png)

I have noticed if I use the "AllSanity<typename>". This specific query gets twice the result. First array without new image, second one with the new image.
![image](https://user-images.githubusercontent.com/47401362/97418125-ba3e2600-1908-11eb-97b0-7c4c99be39cc.png)

Does anyone have an idea why the 'allSanity<typename>' gives me 2 arrays while there is only one defined? One with the new assets and the other with the old.

**Comment by autodomme** [comment]
Same problem here. One is the original version, the next is the updated and published version

**Comment by leeuwd** [comment]
Same here. The API returns old data.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by khalilp5** [comment]
> Same problem here. One is the original version, the next is the updated and published version

Any chance this issue was resolved? I'm facing the same issue right now.
