### ISSUE TITLE
[Potential Bug] Sanity Studio fails to load on Chrome locally

### ISSUE THREAD

**Issue by awareness481** [sanity-io/sanity#2097]
**Describe the bug**

Sanity studio fails to load on Chrome locally, with an `ERR_CONNECTION_REFUSED` error. It works on Firefox. I also tried different ports (after of course adding access through manage.sanity.io) but I still got the same error.

**To Reproduce**

1. Clone [nextjs-ecommerce](https://github.com/awareness481/next-js-e-commerce) or use the starter
2. Follow the instructions to properly setup the project
3. Run `npm run dev` on project root
4. Open http://localhost:3333 on Chrome and see `ERR_CONNECTION_REFUSED` error.

*Note*: This happens to all my Sanity projects so far, but this is the most recent one.

**Expected behavior**

Sanity studio working on chrome.

**Screenshots**

![image](https://user-images.githubusercontent.com/12380586/97774728-ece35b00-1b62-11eb-9db2-fdca89bfb733.png)

**Which versions of Sanity are you using?**

**Project root** versions
```bash
@sanity/cli           2.0.3 (latest: 2.0.5)
@sanity/cli           2.0.5 (up to date)
@sanity/client        2.0.1 (up to date)
@sanity/image-url  0.140.19 (up to date)
```

**studio folder** versions

```bash
@sanity/cli                     2.0.3 (latest: 2.0.5)
@sanity/base                    2.0.7 (up to date)
@sanity/block-content-to-react  2.0.7 (up to date)
@sanity/color-input             2.0.5 (up to date)
@sanity/components              2.0.7 (up to date)
@sanity/core                    2.0.5 (up to date)
@sanity/default-layout          2.0.7 (up to date)
@sanity/default-login           2.0.5 (up to date)
@sanity/desk-tool               2.0.8 (up to date)
@sanity/vision                  2.0.5 (up to date)
```

**What operating system are you using?**

(Xubuntu)
```bash
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Which versions of Node.js / npm are you running?**

```bash
6.14.8
v12.18.3
```

**Additional context**

As I said earlier I tried different ports but I got the same error. I expect this error to either be local to my system or affect a minority of users as I couldn't find a similar issue.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
