### ISSUE TITLE
True document level translation

### ISSUE THREAD

**Issue by jdwillemse** [sanity-io/sanity#2121]
**Is your feature request related to a problem? Please describe.**
I find it frustrating that document level translation is not a native feature in Sanity. Tools like Next.js are making it easier to support multiple languages but Sanity only has a [community-created plugin](https://github.com/LiamMartens/sanity-plugin-intl-input#with-intl-plugin) or a [workaround](https://www.sanity.io/docs/localization#document-level-translations-f695f60516c4) suggested by the docs. The workaround is not a real solution as it does not link the documents that are translations of one another. It is probably possible to find workarounds for this too, but I really would expect a native solution in a modern CMS.

**Describe the solution you'd like**
I would like the Sanity team to roll the features present in the community translation plugin into Sanity with features added to show when documents are missing translations. I would also like language to be a query filter.

**Describe alternatives you've considered**
I've used the community plugin which works well, but it had missing features and then an upgrade broke backwards compatibility (I'm very grateful to the creator and maintainers so I do not say this to diminish their work). Since the plugin is a workaround for providing missing functionality it ran into conflicts with other workarounds like hiding the document list for singleton docs.

**Comment by bastienrobert** [comment]
Another major problem with the both solutions is that you need to have a document in the primary language to translate it into a secondary one, eg. if my primary language is English and I want to create a page in French only, it is impossible.
Also, it is impossible to filter by language in the studio.

**Comment by jonlambert** [comment]
Currently evaluating CMS solutions for a few big upcoming projects and was super excited to discover Sanity. Real shame to see translations are only supported via a pretty complex workaround. Would be good to have true, first-class support without needing to copy in a bunch of files from a template. Feels very brittle and prone to errors.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
