### ISSUE TITLE
Modifying hex colors results in "Uncaught TypeError"

### ISSUE THREAD

**Issue by remisture** [sanity-io/sanity#2124]
**Describe the bug**

Trying to manually set the hex color results in `Uncaught TypeError: Cannot read property 'isValidHex' of undefined`

**To Reproduce**

1. Open a color picker
2. Try modifying the hex value
3. See console logs

**Expected behavior**

The user can set the hex color manually without any errors.

**Screenshots**

<img width="1330" alt="Skjermbilde 2020-11-12 kl  11 38 35" src="https://user-images.githubusercontent.com/2372967/98930496-04b0cc80-24dd-11eb-936f-ed65f5dd61b4.png">

**Which versions of Sanity are you using?**

```
@sanity/cli                 2.0.9 (up to date)
@sanity/base                2.0.9 (up to date)
@sanity/cli                 2.0.9 (up to date)
@sanity/color-input         2.0.9 (up to date)
@sanity/components          2.0.9 (up to date)
@sanity/core                2.0.9 (up to date)
@sanity/dashboard           2.0.9 (up to date)
@sanity/default-layout      2.0.9 (up to date)
@sanity/default-login       2.0.9 (up to date)
@sanity/desk-tool           2.0.9 (up to date)
@sanity/production-preview  2.0.5 (up to date)
@sanity/vision              2.0.9 (up to date)
```

**What operating system are you using?**

MacOs 10.15.7

**Which versions of Node.js / npm are you running?**

```
$ npm -v && node -v
6.14.8
v12.19.0
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
