### ISSUE TITLE
Can't able to login 

### ISSUE THREAD

**Issue by gjgit** [sanity-io/sanity#2129]
Can't login into sanity .,

![image](https://user-images.githubusercontent.com/2841150/99228449-a5bbc200-2812-11eb-95bd-769d5c752404.png)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
