### ISSUE TITLE
Inconsistent filename capitalization for types `DefaultFieldset.js` and `DefaultFieldSet.d.ts`

### ISSUE THREAD

**Issue by ricokahler** [sanity-io/sanity#2132]
**Describe the bug**

When importing `Fieldset` from `@sanity/components`, e.g.

```js
import Fieldset from '@sanity/components/lib/fieldsets/DefaultFieldSet';
```

there is an inconsistent filename capitalization in the `.d.ts` file vs the `.js` implementation.

![image](https://user-images.githubusercontent.com/10551026/99311683-f17a6580-282a-11eb-877c-c3e30fdc1edd.png)

This causes a build in certain linux system to fail to find the correct file. In particular, it fails to build when deploying to Netlify:

![image](https://user-images.githubusercontent.com/10551026/99311927-50d87580-282b-11eb-963f-a1d8842e689b.png)

**To Reproduce**

1. Import `@sanity/components/lib/fieldsets/DefaultFieldSet`
2. Try to build
4. See build error

Let me know if you want a better reproduction, I can spin up some CI or similar and have it throw there.

**Expected behavior**

Consistent filename structure.

**Screenshots**

See above

**Which versions of Sanity are you using?**

```
@sanity/cli             2.0.9 (up to date)
@sanity/base            2.0.9 (up to date)
@sanity/cli             2.0.9 (up to date)
@sanity/components      2.0.9 (up to date)
@sanity/core            2.0.9 (up to date)
@sanity/dashboard       2.0.9 (up to date)
@sanity/default-layout  2.0.9 (up to date)
@sanity/default-login   2.0.9 (up to date)
@sanity/desk-tool       2.0.9 (up to date)
@sanity/vision          2.0.9 (up to date)
```

**What operating system are you using?**

My personal computer is a mac but the errors are occurring in a Netlify build and on my co-workers computer (he runs Arch).

**Which versions of Node.js / npm are you running?**

We have our netlify build use the current LTS and `npm@latest`

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
