### ISSUE TITLE
Request  --skip-document-on-missing-asset

### ISSUE THREAD

**Issue by Ali762** [sanity-io/sanity#2135]
When importing large datasets, some documents may be missing assets. (e.g. a failed image url)

When a missing asset is encountered, the entire import will fail.

The --allow-failing-assets was added, which will permit the import to continue, but simply omit that asset. This means that incomplete documents are added. Sometimes it would be preferable to omit that entire document from the import instead.

We should have an alternative option which would continue the dataset import, only importing those documents which are complete, and produce a report at the end of which documents were skipped, for example --skip-document-on-missing-asset (which would obviously be mutually exclusive with --allow-failing-assets)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
