### ISSUE TITLE
SnackbarItem component cannot render

### ISSUE THREAD

**Issue by SamRaymer** [sanity-io/sanity#2136]
**Describe the bug**

When including the SnackbarItem in a new plugin in a new project, throws an error `onSetHeight is not a function`

**To Reproduce**

1. Go to any page with a SnackbarItem component from `'part:@sanity/components/snackbar/item'`

**Expected behavior**

I would expect the SnackbarItem to render without trouble.

**Which versions of Sanity are you using?**
```
@sanity/cli                2.0.9 (up to date)
@sanity/base               2.0.9 (up to date)
@sanity/components         2.0.9 (up to date)
@sanity/core               2.0.9 (up to date)
@sanity/default-layout     2.0.9 (up to date)
@sanity/default-login      2.0.9 (up to date)
@sanity/desk-tool          2.0.9 (up to date)
@sanity/google-maps-input  2.0.9 (up to date)
@sanity/vision             2.0.9 (up to date)
```

**What operating system are you using?**
OSX Catalina

**Which versions of Node.js / npm are you running?**

npm 6.13.6
node v10.16.2

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
