### ISSUE TITLE
New tabs opened by IntentLink throw a router error

### ISSUE THREAD

**Issue by SamRaymer** [sanity-io/sanity#2137]
**Describe the bug**

IntentLinks add a trailing slash to URLs which causes the router in new tabs to crash.

**To Reproduce**

1. Go to a plugin with an IntentLink to edit an item, e.g. (from the movie database example)
```
import { IntentLink } from "part:@sanity/base/router";

[...]

        <IntentLink
          intent="edit"
          params={{ id: "movie_10681", type: "movie" }}
          target="_blank"
        >
          Wall-E
        </IntentLink>
```

2. Click on the link to Wall-E
4. See error in new tab
```
router.state is undefined

Stack:

DefaultLayout/<@http://localhost:3333/static/js/app.bundle.js:262128:9
render@http://localhost:3333/static/js/app.bundle.js:265833:23
```
5. Remove trailing slash from URL and re-load page
6. See edit window for Wall-E

**Expected behavior**

Clicking the IntentLink should resolve to the editing window without manual intervention

**Which versions of Sanity are you using?**

```

@sanity/cli                2.0.9 (up to date)
@sanity/base               2.0.9 (up to date)
@sanity/components         2.0.9 (up to date)
@sanity/core               2.0.9 (up to date)
@sanity/default-layout     2.0.9 (up to date)
@sanity/default-login      2.0.9 (up to date)
@sanity/desk-tool          2.0.9 (up to date)
@sanity/google-maps-input  2.0.9 (up to date)
@sanity/vision             2.0.9 (up to date)
```

**What operating system are you using?**
OSX Catalina

**Which versions of Node.js / npm are you running?**

npm 6.13.6
node v10.16.2

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
