### ISSUE TITLE
Keyboard shortcuts for header actions aren't working

### ISSUE THREAD

**Issue by Aratramba** [sanity-io/sanity#2139]
**Describe the bug**

The shortcuts for the Inspect header action don't seem to work and the same for the Open Preview shortcut. 

The publish document shortcut does work as expected.

**To Reproduce**

1. Go to any document
2. Press Control+Option+I
3. Watching nothing happen

**Expected behavior**

The inspect modal window should open, same as when clicking the button.

**Screenshots**
![image](https://user-images.githubusercontent.com/580312/99500907-49c07d00-297b-11eb-8d9a-891ffad1a79c.png)

**Which versions of Sanity are you using?**
```
@sanity/cli                        2.0.9 (up to date)
@sanity/base                       2.0.9 (up to date)
@sanity/block-content-to-markdown  0.0.5 (up to date)
@sanity/block-content-to-react     2.0.7 (up to date)
@sanity/cli                        2.0.9 (up to date)
@sanity/client                     2.0.9 (up to date)
@sanity/components                 2.0.9 (up to date)
@sanity/core                       2.0.9 (up to date)
@sanity/dashboard                  2.0.9 (up to date)
@sanity/default-layout             2.0.9 (up to date)
@sanity/default-login              2.0.9 (up to date)
@sanity/desk-tool                  2.0.9 (up to date)
@sanity/production-preview         2.0.5 (up to date)
@sanity/vision                     2.0.9 (up to date)
```

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

```
6.13.4
v12.14.1
```

Tested in Chrome, Opera and Firefox on OSX

**Comment by Aratramba** [comment]
this is still an issue with the latest versions

```
@sanity/cli                2.1.4 (up to date)
@sanity/base               2.1.6 (up to date)
@sanity/color-input        2.1.4 (up to date)
@sanity/components         2.1.4 (up to date)
@sanity/core               2.1.4 (up to date)
@sanity/default-layout     2.1.6 (up to date)
@sanity/default-login      2.1.4 (up to date)
@sanity/desk-tool          2.1.6 (up to date)
@sanity/google-maps-input  2.1.6 (up to date)
@sanity/vision             2.1.4 (up to date)
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
