### ISSUE TITLE
Modal screen out of view and not scrollable

### ISSUE THREAD

**Issue by bzmillerboy** [sanity-io/sanity#2147]
**Describe the bug**
When the modal is open and I try to add a link which opens a popover, the popover is displaying outside the viewport and I am not able to scroll it into view.

**Expected behavior**

I'd expect to be able to scroll so the modal and popover content are in view.

**Screenshots**
Screen Recording: [https://jmp.sh/UcEvgx1](https://jmp.sh/UcEvgx1)

<img width="1100" alt="Screen Shot 2020-11-22 at 6 32 17 PM" src="https://user-images.githubusercontent.com/1130899/99922559-2c830a00-2cff-11eb-81ff-ab88ddd9e477.png">

**Which versions of Sanity are you using?**

@sanity/cli             2.0.9 (up to date)
@sanity/base            2.0.9 (up to date)
@sanity/cli             2.0.9 (up to date)
@sanity/color-input     2.0.9 (up to date)
@sanity/components      2.0.9 (up to date)
@sanity/core            2.0.9 (up to date)
@sanity/dashboard       2.0.9 (up to date)
@sanity/default-layout  2.0.9 (up to date)
@sanity/default-login   2.0.9 (up to date)
@sanity/desk-tool       2.0.9 (up to date)

**What operating system are you using?**
MaOS 10.15.7

**Which versions of Node.js / npm are you running?**

6.14.8
v14.15.0

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
