### ISSUE TITLE
Schema.compile throws error

### ISSUE THREAD

**Issue by jdwillemse** [sanity-io/sanity#2151]
**Describe the bug**

I'm trying to use the [code sample](https://www.sanity.io/docs/presenting-block-text) for deserializing html into block text but I get this error
```
TypeError: Schema.compile is not a function
```

I was able to access the method by using `Schema.default.compile({`, but then I run into more errors on `blockTools.htmlToBlocks`

I'm despirate for a way to convert html to portable text. Please help.

**To Reproduce**

1. Run the code snippet in a node environment
2. See the error

**Expected behavior**

I expect the code to run without an error and produce the output as mentioned in the code snippet.

**Which versions of Sanity are you using?**
```json
    "@sanity/block-tools": "^2.0.9",
    "@sanity/schema": "^2.0.9",
```

**Which versions of Node.js / npm are you running?**

7.0.8
v15.2.1

**Additional context**

I have found others with the same problem https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1603179083262600

**Comment by jdwillemse** [comment]
I found the problem thanks to this https://codesandbox.io/s/wqzj35kq87?file=/src/index.js:0-1220

The package export is not correctly formatted for `import` but instead `require` should be used.

**Comment by 12ian34** [comment]
Thanks for logging this and posting your working solution. This also helped me https://www.sanity.io/answers/hi-again-ive-been-trying-to-use-sanity-block-p1606997792144500

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
