### ISSUE TITLE
Studio doesn't load in browser if project path contains a '#'.

### ISSUE THREAD

**Issue by TheAdmiral** [sanity-io/sanity#2161]
**Describe the bug**

If the path to the project contains a `#` character, e.g. `/Volumes/HDD/Users/ian/Projects/# My Project/Studio/`, opening the running studio in a browser shows the 'Connecting to Sanity.io' loading screen, but never progresses further.

Looking in the browser dev tools, the built-in server is returning 404s for `app.bundle.js` and `vendor.bundle.js`, even though they have been built and are present in the `static` directory.

No errors are shown in the console.

**To Reproduce**

1. Create a directory with a # somewhere in the name and move to it
2. `sanity init && sanity start`
3. Open http://localhost:3333 in a browser

**Expected behavior**

The Studio should connect to Sanity and load the UI.

**Which versions of Sanity are you using?**

@sanity/cli             2.0.9 (up to date)  
@sanity/base            2.0.9 (up to date)
@sanity/components      2.0.9 (up to date)
@sanity/core            2.0.9 (up to date)
@sanity/default-layout  2.0.9 (up to date)
@sanity/default-login   2.0.9 (up to date)
@sanity/desk-tool       2.0.9 (up to date)
@sanity/vision          2.0.9 (up to date)

**What operating system are you using?**

macOS Big Sur 11.0.1

**Which versions of Node.js / npm are you running?**

6.14.9
v14.15.1

(Also tested with Node v15.3.0)

**Additional context**

Adding a # to the start of a directory name is a cheap 'n' dirty way to make a directory appear at the top of a column in the macOS Finder.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
