### ISSUE TITLE
Overflow hidden/ no scrollbar for annotation popdown in sanity studio 2.0

### ISSUE THREAD

**Issue by winsvold** [sanity-io/sanity#2170]
After bumping to sanity 2.0 the popover for editing annotations has changed, but there is no scrollbar, so we are not able to access all of the fields.

![image](https://user-images.githubusercontent.com/29202094/101330531-0028cb00-3873-11eb-9f60-2c551a01cca2.png)

Verson: 2.0.9

**Workarround**
[Add some custom styling](https://www.sanity.io/docs/styling#overriding-variables)

Create a file custom-styling.css:
```
[class^='popover_card'] {
    overflow: auto;
}
```

I think you can import it pretty much anywhere, I used schema.js:
```
// Top of file:
import './custom-styling.css?raw'
```

**Comment by dnalley** [comment]
this didnt work

**Comment by joaisa17** [comment]
> this didnt work

My project is a Next.js project. This solution worked for me
```css
[data-ui*="Popover__wrapper"] {
    overflow: auto !important;
}```
The css file has to be imported via _app.jsx/tsx if you're using next.js.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
