### ISSUE TITLE
eslint and prettier causes sanity studio to not start

### ISSUE THREAD

**Issue by chrisyeung1121** [sanity-io/sanity#2177]
**Describe the bug**

When I start a new sanity project via `sanity init`, I try to include `eslint` and `prettier` as my devDependencies. I found out that after installing them, it will cause all my `node_modules/@sanity/base` files to be removed and only `nanoid` file is left. I have attached the Before and After Screenshot.

**Before**
<img width="335" alt=" 2020-12-09 at 12 36 39 PM" src="https://user-images.githubusercontent.com/3488583/101585743-5b95bd00-3a1b-11eb-84eb-84f93b26b694.png">

**After**
<img width="205" alt=" 2020-12-09 at 12 34 56 PM" src="https://user-images.githubusercontent.com/3488583/101585753-62243480-3a1b-11eb-9c1c-0f8fb2c6eb7e.png">

**To Reproduce**

1. run `sanity init`
2. run `npm i -D eslint eslint-config-prettier eslint-plugin-prettier prettier`
3. See error

**Expected behavior**

`@sanity/base` still has the sanity.json file

**Which versions of Sanity are you using?**

@sanity/cli             2.1.0 (up to date)
@sanity/base            2.1.0 (up to date)
@sanity/components      2.1.0 (up to date)
@sanity/core            2.1.0 (up to date)
@sanity/default-layout  2.1.0 (up to date)
@sanity/default-login   2.1.0 (up to date)
@sanity/desk-tool       2.1.0 (up to date)
@sanity/vision          2.1.0 (up to date)

**What operating system are you using?**
MacOS Catalina

**Which versions of Node.js / npm are you running?**

6.14.8
v12.18.3

**Comment by chrisyeung1121** [comment]
Update - I found out whatever libraries I install with npm. It will delete everything in `@sanity/base`

**Comment by saalimh** [comment]
Hi Chris,

I am experiencing the same problem as you and I am not being able to access sanity studio on my local host.

I keep getting this error
<img width="640" alt="Screenshot 2020-12-09 at 10 56 29" src="https://user-images.githubusercontent.com/59394790/101621301-7e20d980-3a0d-11eb-933f-c7d2902d8e4f.png">

I have read on sanity.io that it can be fixed by adding a sanity.json file but I am unsure where to add it as it is already there. (https://www.sanity.io/help/missing-plugin-sanity-json)

Could you help me out?

**Comment by rexxars** [comment]
This seems very odd, but in any case - it should be addressed in [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) which now leaves package manager interactions up to the user.
