### ISSUE TITLE
History api should be added to client

### ISSUE THREAD

**Issue by Burnett2k** [sanity-io/sanity#2179]
**Is your feature request related to a problem? Please describe.**
We are currently using sanity client in our projects and would like to take advantage of the newer history api in order to retrieve information about deleted items.

**Describe the solution you'd like**
It should behave very similarly to `getDocument` or `getDocuments`, simply takes in an id or an array of ids with a revision or timestamp just like the http api

**Describe alternatives you've considered**
I can obviously hit the api using an http client like axios, but it would be much preferred to be able to use sanity client for all interaction with Sanity.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
