### ISSUE TITLE
[Feature request] Being able to immediately type into referenceInput after clicking dropdown arrow

### ISSUE THREAD

**Issue by Aratramba** [sanity-io/sanity#2184]
**Problem**
When clicking the arrow next to the ReferenceInput focus isn't put on the input field, but stays on the arrow. You need to manually place focus on the input field before being able to type. This means you can't start typing while seeing all input values.

![sanity-reference-input](https://user-images.githubusercontent.com/580312/101793753-6c6f2d00-3b06-11eb-9158-aedd4f9a6125.gif)

**Solution**
Focus should be moved to the input field so that a user can start to type immediately after clicking the arrow. Results should stay visible. This is how many enhanced select boxes work:

[React Select](https://react-select.com/home)
![react-select](https://user-images.githubusercontent.com/580312/101790886-3a100080-3b03-11eb-822b-3338ec021051.gif)

[Choices.js](https://joshuajohnson.co.uk/Choices/)
![choices](https://user-images.githubusercontent.com/580312/101793048-b3a8ee00-3b05-11eb-8391-618654c26fa6.gif)

[Select2.js](https://select2.org/getting-started/basic-usage)
![select2](https://user-images.githubusercontent.com/580312/101793052-b4418480-3b05-11eb-9dd6-bc9f7a30547b.gif)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
