### ISSUE TITLE
WebP uploading buggy

### ISSUE THREAD

**Issue by cfraz89** [sanity-io/sanity#2185]
I have multiple webp images (extracted from a webm video via ffmpeg) where a 500 error is generated either upon upload, or when retrieved from the cdn.
[For example](https://cdn.sanity.io/images/kbz1tcxy/production/39785f4e85d120a273acd97e2d9203f9414d5748-960x720.webp)
Have attached two problematic webp images. [webps.zip](https://github.com/sanity-io/sanity/files/5674302/webps.zip)

However that when i encode images from squoosh.app, they don't have any issues.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
