### ISSUE TITLE
Sanity Studio doesn't validate nested fields

### ISSUE THREAD

**Issue by jferrettiboke** [sanity-io/sanity#2195]
**Describe the bug**

Sanity Studio doesn't validate nested fields properly.

<img width="274" alt="Screenshot 2020-12-17 at 19 47 44" src="https://user-images.githubusercontent.com/11066224/102529824-bde86080-40a0-11eb-9467-5ea000426533.png">

**To Reproduce**

```js
// supportedLanguages.js

const supportedLanguages = [
  { id: "no", title: "Norwegian", isDefault: true },
  { id: "en", title: "English" },
];

export default supportedLanguages;
```

```js
import supportedLanguages from "./supportedLanguages";

const localeString = {
  title: "Localized string",
  name: "localeString",
  type: "object",
  // Fieldsets can be used to group object fields.
  // Here we omit a fieldset for the "default language",
  // making it stand out as the main field.
  fieldsets: [
    {
      title: "Translations",
      name: "translations",
      options: { collapsible: false },
    },
  ],
  // Dynamically define one field per language
  fields: supportedLanguages.map((lang) => ({
    title: lang.title,
    name: lang.id,
    type: "string",
    fieldset: lang.isDefault ? null : "translations",
  })),
};

export default localeString;
```

```js
// requireAllTranslations.js

import supportedLanguages from "./supportedLanguages";

export default function requireAllTranslations(Rule) {
  const fields = {};
  supportedLanguages.forEach(
    (lang) => (fields[lang.id] = (fieldRule) => fieldRule.required())
  );
  return Rule.fields(fields);
}
```

```js
// article.js

import requireAllTranslations from "./requireAllTranslations";

export default {
  name: "articles",
  title: "Articles",
  type: "document",
  fields: [
    {
      title: "Title",
      name: "title",
      type: "localeString",
      validation: (Rule) => requireAllTranslations(Rule),
    },
  ],
  preview: {
    select: {
      title: `title.en`,
    },
  },
};
```

**Expected behavior**

All nested fields for translations should be required.

**Which versions of Sanity are you using?**

```
@sanity/cli                 2.1.0 (up to date)
@sanity/base                2.1.3 (up to date)
@sanity/components          2.1.0 (up to date)
@sanity/core                2.1.2 (up to date)
@sanity/default-layout      2.1.3 (up to date)
@sanity/default-login       2.1.0 (up to date)
@sanity/desk-tool           2.1.3 (up to date)
@sanity/production-preview  2.1.0 (up to date)
@sanity/vision              2.1.0 (up to date)
```

**What operating system are you using?**

macOS Big Sur 11.0.1

**Which versions of Node.js / npm are you running?**

- NPM: 6.14.9
- Node.js: v14.7.0

**Comment by coreyward** [comment]
I don't believe `Rule.fields` is a thing, so that might be the issue. Why not add the `required` validations when the field is created (i.e. when doing `supportedLanguages.map(…)`)?

**Comment by gpoole** [comment]
[Looks like `Rule.fields` must have been added](https://github.com/sanity-io/sanity/blob/97883c99234e817b099eea2665850f4cc7bc6008/packages/%40sanity/validation/src/Rule.ts#L343) since that last comment? The code from the original issue should work as expected now.

As you mentioned @coreyward probably simpler to just add the `required` rules directly to the language fields, but I think in this case the problem is that @jferrettiboke wants to be able to control which fields are required depending on where `localeString` is being used e.g. in some places all translations are required, in other places it's optional?

To add an extra note to your point about some confusion I had @coreyward: I didn't realise that nested objects with required fields will only show errors if the nested object itself is also required by the parent. For example, the following does not cause a validation error for a `button` if the `link.href` field is empty:

```js
{
  type: "object",
  name: "button",
  fields: [
    { type: "link", name: "link" }
  ]
}

{
  type: "object",
  name: "link",
  fields: [
    { type: "string", name: "href", validation: Rule => Rule.required() }
  ]
}
```

Since the `button` object may be optional in some places and required in others, I didn't want to mark `link.href` as required since I don't want errors when the whole `button` is optional. I've now realised that `link.href` will only show a required error if `button.link` is _also_ marked required. And that's why it's fine to mark all the language fields of `localeString` as required, even if the actual `localeString` is optional.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
