### ISSUE TITLE
[Feature request] Document list: Datatable with columns, interactive sort & filter

### ISSUE THREAD

**Issue by DiesIrae** [sanity-io/sanity#2211]
I'm new to Sanity, and apart from this big pain point described below, I find it amazing, congrats! 

**Is your feature request related to a problem? Please describe.**
The object list drawer UX (the "select preview" in the data schema) is very basic, and I could not find anywhere a module / plugin to improve it. I need to:
- Search & filter documents by children (in the movie example, I can't find "Alien: Covenant" if I type "Michael Fassbender")
- Look at lots of document data without always opening them
- Compare documents with one another

**Describe the solution you'd like**
A data table instead of the document list drawer, with classic data table features:
- Columns
- Sort by clicking on column
- Free text filter
- Data filtering by column

**Additional context**
This is a classic CMS function IMHO, as you can see on Strapi, Directus...

This can be achieved with a React Data Table like [Material Table](https://github.com/mbrn/material-table), but it needs a strong frontend integration, I don't know if this can be done with the current plugin system.

**Comment by kkgthb** [comment]
I, too, am a little surprised that I can't see "Interstellar" or "The Martian" in the suggested search results when I search "Damon" (although I do see "Elysium").

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
