### ISSUE TITLE
__experimental_search support for array of strings?

### ISSUE THREAD

**Issue by broksonic21** [sanity-io/sanity#2214]
**Describe the bug**

**To Reproduce**

Lets say you have this:

```
   type: 'document',
  name: 'author',
  fields: [
    {name: 'name', type: 'string'},
    {name: 'otherNames', type: 'array', of: [{ type: 'string' }]},
    // ...
  ],
  __experimental_search: [
    {weight: 1.2, path: 'name'}
  ]
```

I can't find a way to get experimental search to accept the otherNames values. 'otherNames' doesn't work, is there another form?

**Expected behavior**

Able to search for experimental search for array fields.

**Comment by broksonic21** [comment]
Note: I tried:

`otherNames`, `otherNames[]`, and `otherNames.*` just to try a few forms, but no luck. Any ideas?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
