### ISSUE TITLE
Split resizer z-index of 1000 has display priority over dialogs

### ISSUE THREAD

**Issue by nestlist** [sanity-io/sanity#2226]
The SplitController Resizer (span with light grey vertical line between panes) defaults to a z-index of 1000.

A side effect is that it remains visible above any content from panes including dialogs.

I've created a simple 'true' full window dialog using a fixed position div. The Dialog given in part:@sanity/components/dialogs/fullscreen is still constrained in the child pane.

Simply setting the z-index on the SplitController to 100 instead of 1000 retains the resize functionality but doesn't interfere with dialog content.

I can't see any scenario where a user would need to resize the panes whilst having a dialog open.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
