### ISSUE TITLE
Sanity Studio Hidden Post

### ISSUE THREAD

**Issue by jordan-miguel** [sanity-io/sanity#2232]
# Issue

It seems like a have a rogue/hidden post within Sanity studio that I cannot locate. 

## Sanity graphQL playground (works as expected)

- Create & Publish **_2 test posts_** at http://localhost:3333/desk/Post
- Run `sanity graphql deploy`

Data is retrieved as expected:
### query
```
query {
  allPost {
    _id
  }
}
```
### output
```
{
  "data": {
    "allPost": [
      {
        "_id": "drafts.7e42569e-2a38-4bb2-8fa4-14fe21c5f86a"
      },
      {
        "_id": "drafts.91f9d11c-cd18-4d81-8f0c-51c191604be9"
      }
    ]
  }
}
```

# Gatsby graphiQL playground http://localhost:8000/___graphql (retrieving an extra/hidden post)

## Sanity graphQL playground (works as expected)

- Run `gatsby develop`
- View GraphiQL

Data is retrieved as expected:
### query
```
query MyQuery {
  allSanityPost {
    totalCount
  }
}

```
### output
```
{
  "data": {
    "allSanityPost": {
      "totalCount": 3
    }
  },
  "extensions": {}
}
```

Below is a screenshot showing only 2 posts in my Post document. Where is the extra post coming from?

<img width="948" alt="Screenshot 2021-01-19 at 14 10 30" src="https://user-images.githubusercontent.com/14114089/105051676-ea5c1780-5a66-11eb-9448-7aca9635284d.png">

**Comment by rexxars** [comment]
Could you try querying with titles or document IDs in the Gatsby Graphiql?

**Comment by LawJolla** [comment]
This is a pretty ugly bug.  It may be related to nested objects.  Here you can see the results queried two ways -- the top for all siteSettings belonging to a dealership.  The second for all siteSettings.  The results with `id: "46c..."` are stale and do not show in Studio.  The result with `id: "siteSettings"` is current and shown in Studio, but is not reachable through the dealership type.

![Image 2021-03-11 at 5 06 32 PM](https://user-images.githubusercontent.com/17485128/110871907-7da61200-828c-11eb-81b4-7b1f28be121f.jpg)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
