### ISSUE TITLE
Forgetting the quote around a type name that is the same as a reserved keywords will crash the studio

### ISSUE THREAD

**Issue by hrisng** [sanity-io/sanity#2242]
**Describe the bug**
Let's say you have type name like `location`. Forgetting the quote around it will not cause the `foo is not defined` error to display, because it is a reserved word. It will instead be resolved as the `location` window object.
The studio will then attempt to display the `SchemaErrors` to show that the type of `type` property is invalid, which cause React to crash because React can't render an object.

**To Reproduce**
1. Name a custom type the same as a reserved word
2. Omit the quote when using it
3. Studio crash with uncaught exception without any useful information

**Expected behavior**
I know this seems like an edge case, but it is a extremely frustrating behavior and can be fixed by a simple check when rendering the error. We could also offer some hint to make it easier to debug.

**Which versions of Sanity are you using?**
@sanity/cli: 2.1.4, and ran `sanity upgrade` to the latest
npm: 6.14.10
node: v15.0.1

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
