### ISSUE TITLE
Mismatch of property name in docs

### ISSUE THREAD

**Issue by jakubpodolski** [sanity-io/sanity#2245]
In the options filed, for the reference type, there is a mismatch of the property name. 
It is stated that the property is called `filterParams` while in reality, it is simply `params` 

![image](https://user-images.githubusercontent.com/38116079/105486026-1e754980-5cae-11eb-8fa7-1f6e0e6bb384.png)

![image](https://user-images.githubusercontent.com/38116079/105486051-2af9a200-5cae-11eb-84ca-ef6d8085632c.png)

The problem is visible here: https://www.sanity.io/docs/reference-type#filterParams-0bab0cc1c383

**Comment by rexxars** [comment]
There's actually two different implementations here;
```js
{
  filter: () => ({
    filter: 'str',
    params: {key: 'value'}
  })
}
```

and 

```js
{
  filter: 'string',
  filterParams: {key: 'value'}
}
```

In hindsight, this it very confusing. The original rationale was that we might at some point want to add some kind of other "params" to the reference input, which isn't related to the filter, and thus should prefix with `filter` to make it explicit.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
