### ISSUE TITLE
Can't upload multiple images

### ISSUE THREAD

**Issue by myronov** [sanity-io/sanity#2313]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Can't upload multiple images to some fields

**To Reproduce**

1. Go to image array field
2. Upload multiple images

**Expected behavior**

Uploading multiple images should work consistently for all fields.

**Screenshots**

https://user-images.githubusercontent.com/55454191/108398296-c54af800-7210-11eb-883c-3b879fec4b69.mp4

**Which versions of Sanity are you using?**

@sanity/cli 2.1.4 (latest: 2.3.8)
@sanity/base 2.3.8 (up to date)
@sanity/components 2.2.6 (up to date)
@sanity/core 2.3.8 (up to date)
@sanity/default-layout 2.3.8 (up to date)
@sanity/default-login 2.2.6 (up to date)
@sanity/desk-tool 2.3.8 (up to date)
@sanity/google-maps-input 2.3.8 (up to date)
@sanity/image-url 0.140.22 (up to date)
@sanity/production-preview 2.2.6 (up to date)
@sanity/vision 2.2.6 (up to date)

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

6.14.6
v14.15.4

**Additional context**

Uploading multiple images seems to work in nested fields, it doesn't work for another field though.

**Comment by rexxars** [comment]
Hi!

Could you post the schema field definition for the `hero` field?

**Comment by myronov** [comment]
```
      title: 'Hero',
      name: 'hero',
      type: 'array',
      of: [{ type: 'article_hero' }]
```
      
~~~~~~~~~~~~~~~~~~~~~~~~~
```

      title: 'Article Hero',
      name: 'article_hero',
      type: 'object',
      preview: {
        select: {
          title: 'image.alt',
          subtitle: 'image.copy',
          media: 'image',
          videoUrl: 'video'
        },
        prepare: prepareOembedVideo
      },
      fields: [
        {
          title: 'Image',
          name: 'image',
          type: 'image',
          options: {
            metadata: ['palette'],
            hotspot: true
          },
          fields: [
            {
              name: 'alt',
              type: 'string',
              title: 'Alt',
              options: {
                isHighlighted: true
              }
            },
            {
              name: 'caption',
              type: 'string',
              title: 'Caption',
              options: {
                isHighlighted: true
              }
            },
            {
              name: 'attribution',
              type: 'string',
              title: 'Attribution'
            },
            {
              title: 'Buy Release Link',
              type: 'buySneakerLink',
              name: 'buySneakerLink',
              options: {
                isHighlighted: true
               }
             }
          ],
          preview: {
            select: {
              title: 'alt',
              subtitle: 'caption',
              media: 'asset'
            }
          }
        }
      ]
```

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
export const prepareOembedVideo = (selection) => {
  const { videoUrl, ...rest } = selection
  if (videoUrl) {
    const videoId = getVideoId(videoUrl)
    if (videoId && videoId.service === 'youtube') {
      return {
        ...rest,
        media: <img src={`http://img.youtube.com/vi/${videoId.id}/default.jpg`} width='100' />
      }
    }
  }
  return {
    ...rest
  }
}
```

**Comment by rexxars** [comment]
Right - this is a bit complicated because the child of the array is not an image, but an object, which happens to include an image field. I'm not quite sure what the behavior of this should be - for instance, if the `article_hero` type contained two or more image fields - which one should it choose? And if you had a deep object structure with an image somewhere in the tree, should it recursively look for an image field?

I think the array field should probably not go into a "drop here" state unless it has already determined that it can accept files/images, for now.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
