### ISSUE TITLE
[desk-tool] DocumentTypeList pane not loading documents when collapsed on page load

### ISSUE THREAD

**Issue by peeke** [sanity-io/sanity#2332]
**Describe the bug**

When reloading an editor page in the studio (visited through a DocumentTypeList), when the DocumentTypeList pane is initially collapsed it won't load any documents (except for just the first item in the list). When the pane is expanded when you reload the page, everything works fine.

**To Reproduce**

Make sure you have a studio with desk tool, including a DocumentTypeList.

1. Navigate to the DocumentTypeList pane
2. Click a document
3. Resize the page, so the DocumentTypeList pane is collapsed
4. Reload the page
5. Click on the DocumentTypeList pane heading, to expand it

It now only show the first document originally in the DocumentTypeList.

**Expected behavior**

I would expect the DocumentTypeList to work consistently, regardless of initial state of the pane.

**Screenshots**

Loading with panel opened:

![image](https://user-images.githubusercontent.com/4712314/109116257-85b86a80-7740-11eb-98fa-199e161156fe.png)

Loading page with panel closed:

![image](https://user-images.githubusercontent.com/4712314/109116320-9ff24880-7740-11eb-894b-bd9398e0c71b.png)
![image](https://user-images.githubusercontent.com/4712314/109116381-b6989f80-7740-11eb-99fc-358d5e752e1b.png)

**Which versions of Sanity are you using?**

```
@sanity/cli                2.4.0 (up to date)
@sanity/base               2.4.1 (up to date)
@sanity/cli                2.4.0 (up to date)
@sanity/components         2.2.6 (up to date)
@sanity/core               2.4.0 (up to date)
@sanity/default-layout     2.4.1 (up to date)
@sanity/default-login      2.2.6 (up to date)
@sanity/desk-tool          2.4.2 (up to date)
@sanity/image-url       0.140.22 (up to date)
@sanity/vision             2.2.6 (up to date)
```

**What operating system are you using?**

macOS Big Sur

**Which versions of Node.js / npm are you running?**

```
6.14.11
v10.23.3
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
