### ISSUE TITLE
[Feature request] Studio - Vision: Tabs like in the Graphql Playground

### ISSUE THREAD

**Issue by Hahlh** [sanity-io/sanity#2338]
**Is your feature request related to a problem? Please describe.**

When I am constructing queries, I don't soley work on a single thing. I need to test stuff, jump to another problem briefly, run some different queries to further construct others. Especially while learning GROQ this feature (along with Graphql-like autocomplete) could be of great use.

**Describe the solution you'd like**

The Graphql Playground offers a Tab functionality, that would also be awesome to have in Vision. 

Thank you for your great work!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by Hahlh** [comment]
@kmelve So I should now go and double check that this feature request is still relevant for the studio? Or has this been implemented in v3? 
I don't see why a feature request like this should otherwise be closed.
