### ISSUE TITLE
Cannot import images from exported dataset

### ISSUE THREAD

**Issue by BolajiAyodeji** [sanity-io/sanity#2347]
**Describe the bug**

I'm trying to import an exported dataset, but it fails with an error:

```
Error: Error while fetching asset from "file://./images/5c3041a760673e003d870279644ad0a2e1ed53f1-1000x1000.png":
File does not exist at the specified endpoint
```

All images return an error after exporting a dataset (and importing on another machine) even though I see them in my development studio. However, other data and documents were imported successfully.

Looks like a wrong image file path in the unzipped export. I'm not sure if this is a bug or I'm doing something wrong. Any ideas on how I can fix this, please? Thanks!

**Expected behavior**

When I import a dataset, all images and other data should import successfully.

**Which versions of Sanity are you using?**

@sanity/cli  2.4.0 (up to date)

**What operating system are you using?**

macOS Big Sur

**Which versions of Node.js / npm are you running?**

7.5.4
v15.0.1

**Comment by danielblignaut** [comment]
this may help you:

```javascript
const fs = require('fs')
const util = require('util')
const ndjson = require('ndjson')


function rebuildFileAssetUrls(val, key) {
	if(typeof val === 'string') {
		const newVal = val.replace('file://./', `file://${__dirname}/`)

		return newVal
	}
	else if(Array.isArray(val)) {
		return val.map((item)=> rebuildFileAssetUrls(item))
			
	}
	else if(typeof val === 'object' && val != null) {
		const entries = Object.entries(val)
		let newItem = {}
		entries.forEach(([key, val])=> newItem[key] = rebuildFileAssetUrls(val, key))

		return newItem
	}
	else if(typeof val === 'undefined' || val == null) {
		return val
	}
	else if(typeof val === 'boolean' || typeof val === 'number') {
		return val
	}
	else {
		return val
	}
}

(async ()=> {
	let data = await new Promise((resolve)=> {
		let temp = []
		fs.createReadStream('./data.ndjson')
			.pipe(ndjson.parse())
			.on('data', function(obj) {
				temp.push(obj)
			})
			.on('end', function() {
				resolve(temp)
			})
	})

	let writeStream = fs.createWriteStream('./output.ndjson')
	const serialize = ndjson.stringify()
	serialize.on('data', function(line) {
		// line is line of stringified JSON with newline delimiter the end
		writeStream.write(line, 'utf-8')

	})
	
	writeStream.on('finish', () => {
		console.log('wrote all data to file')
	})

	data = data.forEach((item)=> {
		let newItem = {
			...item
		}
		

		newItem = rebuildFileAssetUrls(newItem)
		
		serialize.write(newItem)

	})

	

	serialize.end()


})()
```

note the input files and output files are relative to this directory... best to run in root of sanity project. Should recursively find and fix file references in the outputted file for you.

NOTE FOR SANITY TEAM: file urls need to be absolute to play nice with sanity import tool.... otherwise the import tool should replace all relative file urls for absolutes during import (best solution to prevent broken urls)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by AryanJ-NYC** [comment]
I'm suddenly getting this error. I'm on Sanity v3.40.0.
