### ISSUE TITLE
Validation is ignored when live edit is enabled

### ISSUE THREAD

**Issue by andyrichardson** [sanity-io/sanity#2352]
**Describe the bug**

✅  When `liveEdit` is disabled on a document, changes cannot be pushed until validation errors are resolved.
❌  When `liveEdit` is enabled on a document, changes are pushed immediately, regardless of validation errors.

**To Reproduce**

1. Create a document with validation on a field
2. Enable live edit
3. Enter data into the document that will cause validation to fail

**Expected behavior**

Changes are not published until valid data is present

**Actual behavior**

Changes are pushed immediately, regardless of validation

**Which versions of Sanity are you using?**

```
@sanity/cli             2.4.0 (latest: 2.5.0)
@sanity/base            2.4.1 (latest: 2.5.0)
@sanity/cli             2.4.0 (latest: 2.5.0)
@sanity/client          2.2.6 (up to date)
@sanity/code-input      2.2.6 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.4.0 (latest: 2.5.0)
@sanity/default-layout  2.4.1 (latest: 2.5.0)
@sanity/default-login   2.2.6 (up to date)
@sanity/desk-tool       2.4.2 (latest: 2.5.0)
@sanity/export          2.2.6 (up to date)
@sanity/import          2.2.6 (up to date)
@sanity/vision          2.2.6 (up to date)
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
