### ISSUE TITLE
--non-null-document-fields flag defaults to false

### ISSUE THREAD

**Issue by andyrichardson** [sanity-io/sanity#2355]
**Describe the bug**

Despite being in a [non-major release](https://github.com/sanity-io/sanity/releases/tag/v2.2.2), the `--non-null-document-fields` flag is now `false` by default.

Users of pre v2.2.2 releases will have noticed that updating to v2.2.2 changed all fields in the schema to now be optional (unless explicitly adding the `--non-null-document-fields` flag which previously was default functionality).

**Comment by rexxars** [comment]
Nullable document fields has actually been the default since [v1.149.12](https://github.com/sanity-io/sanity/releases/tag/v1.149.12).

The `--non-null-document-fields` was introduced in v2.2.2 to allow changing this, should you know that document types are never used directly in other schema types without being a reference.
