### ISSUE TITLE
[Feature request] Allow non-interactive CLI commands

### ISSUE THREAD

**Issue by JEGardner** [sanity-io/sanity#2362]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use the Sanity CLI in my CI/CD pipeline without user interaction.

**Describe the solution you'd like**
Ideally for all commands, you should be able to provide enough options that prompts aren't needed. The ones I am currently interested in are dataset export & import. There's also a requirement to be able to login using a token instead of the browser. 

**Describe alternatives you've considered**
An alternative that I will probably need to use is to write my own commands using the packages used by Sanity's commands (@sanity/export & @sanity/import).

**Comment by bartholomews** [comment]
I have the same issue, my workaround is to run `echo "Y" | sanity dataset import x y`,
but I have to set `SANITY_AUTH_TOKEN` env var to my personal sanity token (in the browser session cookies). When I use the robot token, either with Deploy or Read+Write I get `User is missing required permissions "manageDatasets" to perform this operation` so it's not ideal for CI pipeline (dataset export works fine even with robot token Read)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
