### ISSUE TITLE
Scrolling while a number input is focussed is changing the value

### ISSUE THREAD

**Issue by andre-brdoch** [sanity-io/sanity#2370]
**Describe the bug**

Scrolling via scrolling wheel while having focus on a number input changes its value.

**To Reproduce**

In the studio, click on a number input, edit its value, then attempt to scroll down (while the field is still focussed).

**Expected behavior**

It should scroll down the page, and not change the input value.

**Browser**:
Firefox

**Additional context**

It is quite easy to change a number value to something that was not intended without noticing 😃 Also this is not standard browser behavior of number inputs. Since most documents require scrolling, this can happen quite easily.

This does not happen when scrolling via trackpad.

**Comment by bjoerge** [comment]
We don't do anything special handling here so not sure what's going on. I'm also not able to reproduce this in Firefox 86. What OS, version of Firefox and versions  of sanity packages are you on?

I'm observing the behavior you describe when scrolling using wheel or trackpad on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number, but in Chrome and Safari, not Firefox, and only when hovering the cursor over the input _while_ the input is focused (macos).

**Comment by andre-brdoch** [comment]
Hi @bjoerge , you are right, my initial description was not correct! Thanks for pointing that out. Below I updated the behavior I am seeing.

So this is clearly not a bug as I had labelled it! However, it is still undesirable behavior in my opinion. Sanity forms (opposite to most forms on the internet) can get long quite often and require scrolling. You just edited a field, so it has focus.  Also since you just want to scroll, you will probably not move the cursor first. Because of this the described issue is probably not a rare exception, but rather quite likely.

Maybe it could be something that Sanity could avoid with some custom handling? 😃 

----

On the [mozilla link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number), I get the behavior in the following situations:

Chrome 89:
- happens both with scroll wheel and trackpad
- only while the input is hovered

Firefox 86:
- happens only for scroll wheel (this is different to what you saw)
- only while the input is hovered

I am using windows 10

```
"@sanity/base": "^2.6.0",
"@sanity/block-tools": "^2.5.0",
"@sanity/color-input": "^2.2.6",
"@sanity/components": "^2.2.6",
"@sanity/core": "^2.6.1",
"@sanity/dashboard": "^2.2.6",
"@sanity/default-layout": "^2.6.0",
"@sanity/default-login": "^2.2.6",
"@sanity/desk-tool": "^2.6.1",
"@sanity/image-url": "^0.140.22",
"@sanity/ui": "^0.33.9",
"@sanity/vision": "^2.2.6"
```

**Comment by bjoerge** [comment]
Thanks for confirming @andre-brdoch. I think you are raising a valid concern here. The native behavior can, as you say, easily result in unintentional changes and we should see if we can do something to mitigate it. Generally we try to avoid overriding native browser behavior, but this might be one of the cases where it makes sense for us to provide a workaround, perhaps by offering an option to disable it.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by bjoerge** [comment]
FWIW, this recently came back to us, and a workaround is coming in https://github.com/sanity-io/sanity/pull/9064

This workaround doesn't fix it Safari, but the underlying bug has been fixed in WebKit, and is effective as of the current Technology Preview, and likely will be included in an official Safari release some time soon.
