### ISSUE TITLE
Local font support

### ISSUE THREAD

**Issue by robschwitzer** [sanity-io/sanity#2371]
**Describe the bug**

Using @import for local fonts results in compilation errors. Using @font-face has no effect at all

**To Reproduce**

1. Add 
```
{
   "implements": "part:@sanity/base/theme/variables/override-style",
   "path": "variableOverrides.css"
}
```
to "parts" in sanity.json.
2. Create `variableOverrides.css` at root of project.
3. Create `static/fonts` directory and add desired font(s)
4. Add `@import url('/static/fonts/<your-font.otf>')` to `variableOverrides.css` 
5. Add `--font-family-base: 'YOUR-FONT'` to `:root` style block
6. Run `sanity start` and see compilation error referencing missing font module

**Expected behavior**

Sanity studio should compile and font should be available in the app

**Which versions of Sanity are you using?**

```
@sanity/cli             2.1.0 (latest: 2.6.0)
@sanity/base            2.1.3 (latest: 2.6.0)
@sanity/color-input     2.1.0 (latest: 2.2.6)
@sanity/components      2.1.0 (latest: 2.2.6)
@sanity/core            2.1.2 (latest: 2.6.1)
@sanity/default-layout  2.1.3 (latest: 2.6.0)
@sanity/default-login   2.1.0 (latest: 2.2.6)
@sanity/desk-tool       2.1.3 (latest: 2.6.1)
@sanity/vision          2.1.0 (latest: 2.2.6)
```

**What operating system are you using?**

MacOS Big Sur 11.2.2

**Which versions of Node.js / npm are you running?**

npm `6.14.10` & node `15.1.0`

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
