### ISSUE TITLE
[graphql] Namespace GraphQL Sanity Base Types

### ISSUE THREAD

**Issue by LawJolla** [sanity-io/sanity#2372]
Thanks everyone for your hard work on an amazing product!

One of the big draws of GraphQL is schema merging.  However, Sanity's base types, e.g. `Image` and `File` likely conflict with an existing project's `Image`, `File`, etc.

E.g.
```
type Image {
   ...my app's image type is already defined as "Image"
}

// sanity's image type, throws error for conflicting types
type Image {
    _key: String
    _type: String
    asset: SanityImageAsset
    crop: SanityImageCrop
    hotspot: SanityImageHotspot
}
```
to
```
type SanityImage {
    _key: String
    _type: String
    asset: SanityImageAsset
    crop: SanityImageCrop
    hotspot: SanityImageHotspot
}
```
I'd love to be able to name space these to Sanity[Type]  (I think namespacing the all types, like you've done with SanityImageAsset, SanityImageCrop, etc. would be better anyway.)

If there's a work around happy to hear that too.

**Comment by saasen** [comment]
Thanks for reporting. The only workaround as of now is to rename your own type (if possible). We are working on improving the GraphQL experience substantially, but I can't give any timeframe as to when that will be finished.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
