### ISSUE TITLE
[Studio] Option to change account email

### ISSUE THREAD

**Issue by iakovosvo** [sanity-io/sanity#2375]
**Is your feature request related to a problem? Please describe.**
I would like to change my account email from the account settings (I login with Github) but it doesn't looks like its possible to do that. 

**Describe the solution you'd like**
An option to change my account email.

**Describe alternatives you've considered**
Delete my account and make a new one.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
