### ISSUE TITLE
`sanity start` command uses incorrect .env file

### ISSUE THREAD

**Issue by joecritch** [sanity-io/sanity#2380]
**Describe the bug**

I have both a `.env.production` and `.env.development` inside my local studio folder (for `sanity deploy` and `sanity start` respectively), both containing custom `SANITY_STUDIO_` environment variables. However, when I just run `sanity start` command, it uses the `SANITY_STUDIO_ ` variables from `.env.production` file instead of `.env.development`.

- Note 1: if I delete the local `.env.production`, `sanity start` then works as expected.
- Note 2: if I use a more explicit `SANITY_ACTIVE_ENV=development sanity start`, then it works as expected

**To Reproduce**

1. Create both `.env.production` and `.env.development` each with a custom variable of different values, e.g. `SANITY_STUDIO_PROJECT_URL`
2. Log the value out in (in `resolveProductionUrl.js`'s function for example) 
3. Run `sanity start` 
4. Note how it will show the `SANITY_STUDIO_PROJECT_URL` from `.env.production`, as opposed to `.env.development`

**Expected behavior**

I expect to see the values from `.env.development` when running `sanity start`, in accordance to the [docs](https://www.sanity.io/docs/studio-environment-variables#f5e9e3158896): _"If not defined, it will default to development when running the sanity start command"._

**Which versions of Sanity are you using?**

```
@sanity/cli                 2.6.0 (up to date)
@sanity/base                2.6.0 (up to date)
@sanity/components          2.2.6 (up to date)
@sanity/core                2.6.1 (up to date)
@sanity/dashboard           2.2.6 (up to date)
@sanity/default-layout      2.6.0 (up to date)
@sanity/default-login       2.2.6 (up to date)
@sanity/desk-tool           2.6.1 (up to date)
@sanity/google-maps-input   2.6.0 (up to date)
@sanity/production-preview  2.2.6 (up to date)
@sanity/vision              2.2.6 (up to date)
```

**What operating system are you using?**

macOS Catalina (10.15.7)

**Which versions of Node.js / npm are you running?**

```
npm: 7.6.1
node: v12.16.3
```

**Comment by daren-malfait** [comment]
I'm also having this issue. @2.7.4

**Comment by LeonSkrilec** [comment]
I am having the same issue as @jcontonio. It would be really nice if this can be fixed in the next releases.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
