### ISSUE TITLE
Don't require fields on object types when inputComponent is being used

### ISSUE THREAD

**Issue by loremipson** [sanity-io/sanity#2385]
**Describe the bug**

`fields` is a required array on `object` types. This is awkward in situations where your Custom Input Component creates and stores an object without the users knowledge or need to put content into fields. In this situation, `fields` isn't necessary.

**To Reproduce**

Define a field with an `inputComponent` and set the type to `object` without providing fields.

```js
export default {
  name: 'myField',
  type: 'object',
  inputComponent: MyComponent,
}
```

**Workaround**

Right now, if I just pass a `fields` array, I can bypass the error. But this array is useless, so it's definitely awkward and confusing:

```js
export default {
  name: 'myField',
  type: 'object',
  fields: [{ type: 'string', name: 'temporaryFakeField' }],
  inputComponent: MyComponent,
}
```

**Which versions of Sanity are you using?**

@sanity/cli  2.6.0

**Which versions of Node.js / npm are you running?**

yarn@1.22.10
node@15.11.0

**Comment by LuudJanssen** [comment]
Allowing no fields would also be very nice for static block content fields. For example, I have this use case where I want to add a horizontal ruler to the block content editor, but it doesn't require any options (fields), it's just "there". Now I have to add a `hidden` placeholder field.

**Comment by loremipson** [comment]
@LuudJanssen are you using the `object` type for this? If you can, `string` actually allows for empty fields. I don't know if that works for you though?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
