### ISSUE TITLE
Sanity install not working

### ISSUE THREAD

**Issue by kanhaiya007** [sanity-io/sanity#2389]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**
Installed `sanity cli` on Linux (Ubuntu 20.04), Whenever creating a new project or installing plugin with `sanity install` it is throwing this error
```
✖ Resolving dependenciesinking dependencies
✖ An unexpected error occurred: "EINVAL: invalid argument, mkdir '/media/kanahaiya/New Volume/abc-works/New folder/node_modules/@sanity/types/parts/all:part:@sanity'".
✖ Resolving dependenciesinking dependencies

```

**To Reproduce**
1. Install Sanity on Ubuntu (20.04).
2. Start a new project with `sanity init`
Error while resolving dependency

**Screenshots**
![Screenshot from 2021-03-18 17-16-08](https://user-images.githubusercontent.com/41814802/111626322-d8eb7d80-8813-11eb-9d47-3663348ace28.png)

**Which versions of Sanity are you using?**
@sanity/cli  2.6.0 (up to date)

**What operating system are you using?**
Ubuntu 20.04

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
```
npm -v:  6.14.11
node -v:  v14.16.0
```

**Comment by surjithctly** [comment]
Did you try it on a path where there is no space in the folder names?

eg: `new_volume ` &  `new_folder `

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
