### ISSUE TITLE
Bottom menu items not accessible

### ISSUE THREAD

**Issue by asundlihardig** [sanity-io/sanity#2393]
**Describe the bug**
When the "Add" button of arrays are placed at the end of the document, the document status bar will be placed over the menu. The bottom menu items are not accessible. 

**Expected behavior**
Should add more space at the end of the screen so we will be able to scroll to all menu items.

**Screenshots**
<img width="717" alt="Skjermbilde 2021-03-21 kl  18 23 08" src="https://user-images.githubusercontent.com/1292166/111914907-3da51300-8a74-11eb-9ec7-b9f0f8392355.png">

**Which versions of Sanity are you using?**
@sanity/cli                 2.6.0 (up to date)
@sanity/base                2.6.2 (up to date)
@sanity/code-input          2.2.6 (up to date)
@sanity/components          2.2.6 (up to date)
@sanity/core                2.6.2 (up to date)
@sanity/dashboard           2.2.6 (up to date)
@sanity/default-layout      2.6.2 (up to date)
@sanity/default-login       2.2.6 (up to date)
@sanity/desk-tool           2.6.3 (up to date)
@sanity/production-preview  2.2.6 (up to date)
@sanity/vision              2.2.6 (up to date)

**Which versions of Node.js / npm are you running?**
Node: v14.15.0
NPM: 6.14.11
Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Comment by asundlihardig** [comment]
Would you mind taking a look at this issplease @vicbergquist ?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
