### ISSUE TITLE
Validation notification does not display properly

### ISSUE THREAD

**Issue by nilsnh** [sanity-io/sanity#2395]
**Describe the bug**

Long validation warning text gets clipped when displayed inside an array edit modal.

**To Reproduce**

1. On a document add an array field where you can add object types.
2. On the object type add an array type field with option to add objects.
3. When creating an innermost object, if a field has a long warning text it will try to go outside the box and get clipped so it does not display fully.

**Expected behavior**

Expected to see the whole validation warning message.

**Screenshots**

![Screenshot 2021-03-22 at 08 07 48](https://user-images.githubusercontent.com/282865/111953210-9c0ad980-8ae6-11eb-8715-bc8dd9f1586e.png)

**Which versions of Sanity are you using?**

@sanity/cli                 2.6.0 (up to date)
@sanity/base                2.6.2 (up to date)
@sanity/cli                 2.6.0 (up to date)
@sanity/components          2.2.6 (up to date)
@sanity/core                2.6.2 (up to date)
@sanity/dashboard           2.2.6 (up to date)
@sanity/default-layout      2.6.2 (up to date)
@sanity/default-login       2.2.6 (up to date)
@sanity/desk-tool           2.6.3 (up to date)
@sanity/production-preview  2.2.6 (up to date)
@sanity/vision              2.2.6 (up to date)

**What operating system are you using?**

macOS 11.2.3

**Which versions of Node.js / npm are you running?**

6.14.11
v14.15.0

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
