### ISSUE TITLE
Provide error message when _type is missing from e.g. a patch event

### ISSUE THREAD

**Issue by mittnavnermike** [sanity-io/sanity#2409]
**Describe the bug**

If you patch an object within a document with the javascript client and do not include the `_type` field the data will show in your content studio and appear to be ok. If you then try to edit the field – it is frozen. This leads to confusion especially when the case is very different if you are missing the `_key` value. In the missing`_key` case you get a clear error, and also a way to fix it which is very nice.

I have only tried it with a patch event – but I guess the behavior is similar to other events.

**To Reproduce**

1. Create a patch script that patches an existing document
2. Patch an object that is missing/null in the document without adding the `_type` value.
3. Open the document in the content studio
4. Navigate to the patched object
5. Try a field within that object

**Expected behavior**

I would expect some sort of error that tells me that the `_type` key is missing. Also maybe the input fields within the object should appear disabled to reflect that the field is not editable or that something is wrong.

**Which versions of Sanity are you using?**

@sanity/cli                 2.0.5 (latest: 2.7.1)
@sanity/base                2.3.8 (latest: 2.7.1)
@sanity/cli                 2.3.8 (latest: 2.7.1)
@sanity/color-input         2.2.6 (up to date)
@sanity/components          2.2.6 (up to date)
@sanity/core                2.3.8 (latest: 2.7.1)
@sanity/default-layout      2.3.8 (latest: 2.7.1)
@sanity/default-login       2.2.6 (latest: 2.7.0)
@sanity/desk-tool           2.3.8 (latest: 2.7.1)
@sanity/production-preview  2.2.6 (up to date)
@sanity/vision              2.2.6 (latest: 2.7.0)

**What operating system are you using?**
Big Sur 11.2.3

**Which versions of Node.js / npm are you running?**
NPM: 7.0.3
NODE: v15.0.1

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
