### ISSUE TITLE
Zero matches returned from GROQ v2021-03-25 query with array in filter

### ISSUE THREAD

**Issue by geoffreyjball** [sanity-io/sanity#2415]
**Describe the bug**

Using API v2021-03-25 in Vision, a filter doesn't seem to return any documents when a filter is included. The same filter will return results using API v1.

**To Reproduce**

1. Go to Vision.
2. Select API v1.
3. Enter a query that includes arrays and that returns results. For example:

`*[_type == "post" && features[]._ref == "118acf60-bd77-495d-8d40-334564d995ba"]`

or

`*[_type == "post" && author[references("118acf60-bd77-495d-8d40-334564d995ba")]]`

4. Select API v2021-03-25 and run the same query. A result of No Matches would be a reproduction.

**Expected behavior**

I would expect the queries above to return the same results in both API versions.

**Which versions of Sanity are you using?**

@sanity/cli             2.7.2 (up to date)
@sanity/base            2.7.2 (up to date)
@sanity/code-input      2.2.6 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.7.2 (up to date)
@sanity/default-layout  2.7.2 (up to date)
@sanity/default-login   2.7.0 (up to date)
@sanity/desk-tool       2.7.2 (up to date)
@sanity/vision          2.7.3 (up to date)

**What operating system are you using?**

macOS 11.1

**Which versions of Node.js / npm are you running?**

npm: 7.6.3
node: v15.12.0

**Additional context**

Also experienced by Stian and reported in the Sanity Slack community here: https://sanity-io-land.slack.com/archives/C011CAT70DD/p1617134336018200

**Comment by judofyr** [comment]
This first one can be solved by using an `in` expression instead. The reason for this is that `features[]._ref` returns an array of strings. This should work in both v1 and v2021-03-25:

```
*[_type == "post" && "118acf60-bd77-495d-8d40-334564d995ba" in features[]._ref]
```

The second approach returns no results because `features[references("…")]` returns an array (potentially an empty one if there's no references in it). It's not allowed to `&&` on arrays directly. To filter based on this you need to wrap it in `count(…) > 0`:

```
*[_type == "post" && count(features[references("118acf60-bd77-495d-8d40-334564d995ba")]) > 0]
```

The first query is preferred though and will be more performant.

**Comment by geoffreyjball** [comment]
Much appreciated. Thanks @judofyr!
