### ISSUE TITLE
Feature Request: Schema Builder GUI

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/sanity#2420]
I would like to see a Schema Builder GUI built into the sanity studio so we can just drag & drop elements and save? This option is provided by most of the Headless CMS along with Strapi (wherein the background, they just create the schema file)

So, I liked the Strapi approach and I'm sure it will fit Sanity as well since sanity currently handles schema using a file. 

This feature request is open to discussion. If you like this idea and want this to be implemented, please thumbs up on this post 👍

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
