### ISSUE TITLE
@sanity/client create method creates documents with _id not in UUID format

### ISSUE THREAD

**Issue by pastinepolenta** [sanity-io/sanity#2430]
**Describe the bug**

@sanity/client create method creates document with _id that is not in UUID format

**To Reproduce**

- Use `@sanity/client` like so: `const res = await client.create(doc)`
- `res._id` is in a form like `kOl3s971TBXd4GdccNW1jk`

**Expected behavior**
`res._id` follows the UUID format like when creating the documents via the studio

**Which versions of Sanity are you using?**

@sanity/client 2.2.6
@sanity/cli             2.2.6 (latest: 2.7.4)
@sanity/base            2.1.6 (latest: 2.7.4)
@sanity/color-input     2.2.6 (up to date)
@sanity/components      2.1.4 (latest: 2.2.6)
@sanity/core            2.1.4 (latest: 2.7.4)
@sanity/default-layout  2.1.6 (latest: 2.7.4)
@sanity/default-login   2.1.4 (latest: 2.7.0)
@sanity/desk-tool       2.1.6 (latest: 2.7.4)
@sanity/vision          2.1.4 (latest: 2.7.4)

**What operating system are you using?**
Ubuntu 20.04

**Which versions of Node.js / npm are you running?**

6.14.10
v12.20.1

**Comment by yacouba700** [comment]
const res = await client.create(doc)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
