### ISSUE TITLE
Allow arbitrary bearer token for `GET` to public dataset

### ISSUE THREAD

**Issue by paulThorsen** [sanity-io/sanity#2451]
**Is your feature request related to a problem? Please describe.**
When adding _any_ `Authorization: Bearer <token>` to a `GET` content request to a _public dataset_, I get 
```
error: {
    errorCode: 'SIO-401-ANF',
    message: 'Session not found',
    statusCode: 401,
    error: 'Unauthorized'
  }
```

I imagine this is intended to protect the API (odds are, if there is a bearer token included, the request is meant to change content), but it doesn't make much sense that including a "bad" bearer token will cause my request to fail on a `GET` to a _public dataset_. In one of my projects, we are intercepting all HTTP requests within the app and adding a bearer token to the header once a user is authenticated for use within the app. My work-around currently is that I check if the HTTP request is to the Sanity API and explicitly exclude that bearer token on each request to avoid this error. 

**Describe the solution you'd like**
I'd like to see a solution that ignores the bearer token altogether if the request is just _getting_ content from a _public dataset_. It seems that the API authentication is currently protecting more than it needs to.

**Describe alternatives you've considered**
The alternative for our situation, as I've described above, is to manually check where the HTTP request is going and leave off the bearer token (that is used for other purposes) for the Sanity API request to succeed.

**Comment by rexxars** [comment]
Thanks for filing an issue!

Even with a public dataset, there are certain documents within it which are private and should only be readable for authenticated users or requests with a valid authorization token - drafts being the most common one.

By treating an invalid token as if it wasn't sent, it would be hard to diagnose errors where a user provides a token in order to (for instance) preview documents in a website, since the request would return the published documents and not the drafts.
