### ISSUE TITLE
Nested objects are validated prematurely

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2461]
**Describe the bug**

When adding an item to an array that has validations like 'required' set, the fields are immediately marked as invalid, even before one has had a chance to interact with the fields in the modal. There should be some sort of `dirty` or `touched` checking to prevent this validation running prematurely.

Given the realtime nature of Studio, any changes are persisted in the background automatically. This is often not desirable, and a more explicit means of committing changes would be appropriate. This ties into my comment on this thread: #2428 - it could be as simple as adding 'ok' and 'cancel' buttons to the modals.

This [commit](https://github.com/sanity-io/sanity/commit/1fc68007dc77134ffaec77840ba225f244c2173a) already fixed bubbling those errors to all other fields, what remains is a more sensible handling of validation of the newly created item. 

**Expected behavior**

The fields should not validate before the user deals with the form. In fact, the item should not be added to the array until any meaningful edits have been done.

**Screenshots**

![image](https://user-images.githubusercontent.com/2749/116670947-a56a4a00-a9a0-11eb-9546-f55fbca1c4a1.png)

**Which versions of Sanity are you using?**

@sanity/cli             2.10.0 (up to date)
@sanity/base            2.10.0 (up to date)
@sanity/components       2.2.6 (up to date)
@sanity/core            2.10.0 (up to date)
@sanity/default-layout  2.10.0 (up to date)
@sanity/default-login    2.8.0 (up to date)
@sanity/desk-tool       2.10.1 (up to date)
@sanity/vision          2.10.0 (up to date)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
