### ISSUE TITLE
Default document uses AppLoadingScreen directly bypassing the parts system

### ISSUE THREAD

**Issue by alexeygolev** [sanity-io/sanity#2464]
One might argue that is a feature request but as there is a dedicated part that can be implemented I see it as a bug

**Describe the bug**

[This line](https://github.com/sanity-io/sanity/blob/a768eaf2611b4124e0ed6525bc82b0aa7e0ce00b/packages/%40sanity/base/src/components/Document.js#L5) is importing the default `AppLoadingScreen` effectively making the `part:@sanity/base/app-loading-screen` pointless. 
The default layout [uses](https://github.com/sanity-io/sanity/blob/a768eaf2611b4124e0ed6525bc82b0aa7e0ce00b/packages/%40sanity/default-layout/src/Root.tsx#L5) the part correctly but it loads after the document loads which means there will be two loading screens — one sanity default and one custom. 

**To Reproduce**

Attempt implementing the `part:@sanity/base/app-loading-screen` to override the sanity loading screen

**Comment by EvGreen** [comment]
wish this was resolved, trying to theme up the backend nicely and it's kind of a crucial part to the overall looks

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
