### ISSUE TITLE
JS Client: delete() with query - params not handled

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2492]
**Describe the bug**

It is expected that the `delete` method should handle the `params` passed in, similar to a fetch. However, the following does not work atm:

```javascript
client.delete(
  {
    query: '*[_type == $type]',
    params: { type: 'sometype' },
  }
)
```

As shown by the Typescript definition, this is currently not supported, and throws the following error:

https://github.com/sanity-io/sanity/blob/e8f5b7ced14e6c2184ff7769436cd7d1bfde4918/packages/%40sanity/client/sanityClient.d.ts#L30

```
"error": {
  "description": "param $type referenced, but not provided",
  "end": 15,
  "query": "*[_type == $type]",
  "start": 11,
  "type": "queryParseError"
}
```

**Expected behavior**

That it would be consistent with other methods.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
