### ISSUE TITLE
SANITY_ACTIVE_ENV not respected

### ISSUE THREAD

**Issue by EECOLOR** [sanity-io/sanity#2495]
**Describe the bug**

This section in `sanity.json` is ignored when I set `SANITY_ACTIVE_ENV=dev`:

```json
{
  "env": {
    "dev": {
      "plugins": [
        "@sanity/vision"
      ]
    }
  }
}
```

**To Reproduce**

1. Add a plugin in a certain `env`
2. Call `sanity start` with the `SANITY_ACTIVE_ENV` to the custom `env`
3. Plugin is not loaded

**Expected behavior**

Expected the plugin to be loaded.

**Notes**

I might be mistaken about the meaning of `SANITY_ACTIVE_ENV`, in the source code I also see `SANITY_INTERNAL_ENV` mentioned. This however seems to influence `apiHosts` which seems to be a feature for sanity.io developers.

A few things I found in the code that might help:

`SANITY_ACTIVE_ENV` not passed in: https://github.com/sanity-io/sanity/blob/b0c577c9572509a343b11317379d9b6e23668876/packages/%40sanity/core/src/actions/start/startAction.js#L20

`env` set to `'development'` instead of `SANITY_ACTIVE_ENV`: https://github.com/sanity-io/sanity/blob/b0c577c9572509a343b11317379d9b6e23668876/packages/%40sanity/core/src/actions/start/startAction.js#L39

`NODE_ENV` picked before passed in `env`: https://github.com/sanity-io/sanity/blob/b0c577c9572509a343b11317379d9b6e23668876/packages/@sanity/resolver/src/readManifest.js#L40

`reduceConfig` is passed `buildEnv` which is set to `SANITY_INTERNAL_ENV`, `NODE_ENV` or 'production':
https://github.com/sanity-io/sanity/blob/a3f7158016d63728a9b435e6ab444ff2b90fd424/packages/%40sanity/webpack-loader/src/partLoader.js#L40

In all cases it seems `reduceConfig` is called with the incorrect environment.

This might be related to https://github.com/sanity-io/sanity/issues/2380

**Comment by gpoole** [comment]
Finding this also in 2.30.0, `SANITY_ACTIVE_ENV` has no effect. [The documentation is explicit](https://www.sanity.io/docs/studio-environment-variables#f5e9e3158896) that setting it is meant to work as you'd expect. Setting `NODE_ENV` also doesn't work.

**Comment by gpoole** [comment]
Although referring to the original issue if you use `development` instead of `dev` in sanity.json the configuration will be correctly changed to `production` when you run `sanity build` and `development` if you use `sanity start`. It just doesn't seem to let you override that default by setting `SANITY_ACTIVE_ENV`.

**Comment by matijagrcic** [comment]
You can do the following

Create .env files:
```bash
.env.development
.env.qaf
.env.production
```

in those .env files put the variables you need, example below

```bash
#.env.development
SANITY_STUDIO_API_DATASET=development
#.env.qaf
SANITY_STUDIO_API_DATASET=qaf
#.env.production
SANITY_STUDIO_API_DATASET=production
```

Then in package.json under scripts have the following

```json
"scripts": {
    "start": "yarn environment-development sanity start",
    "start-qaf": "yarn environment-qaf sanity start",
    "start-production": "yarn environment-production sanity start",
    "build": "yarn environment-development sanity build",
    "build-qaf": "yarn environment-qaf sanity build",
    "build-production": "yarn environment-production sanity build",
    "deploy": "yarn environment-production sanity deploy",
    "environment-development": "cross-env SANITY_ACTIVE_ENV=development",
    "environment-qaf": "cross-env SANITY_ACTIVE_ENV=qaf",
    "environment-production": "cross-env SANITY_ACTIVE_ENV=production",
    "format-queries": "prettier --write \"queries/**/*.groq\""
  },
```

Inside sanity.json you can have

```json
"api": {
    "projectId": "XXXXX"
  },
  "project": {
    "name": "XXXXX"
  },
 "env": {
    "development": {
      "plugins": ["@sanity/vision"]
    },
    "qaf": {
      "plugins": ["@sanity/vision"]
    },
    "production": {}
  },
```

Then execute any of the commands in scripts and it will be fine, correct .env will be picked up.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
