### ISSUE TITLE
PortableText editor: minor display issue

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2496]
**Describe the bug**

When no styles have been defined (empty array), there's a double border in the toolbar (since it doesn't account for this omission).

![image](https://user-images.githubusercontent.com/2749/118134010-c0f23d80-b401-11eb-9fa1-21348314d9bb.png)

This is how it looks when some styles are defined:

![image](https://user-images.githubusercontent.com/2749/118134381-27775b80-b402-11eb-92c5-36058d29d781.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/2749/118134088-d36c7700-b401-11eb-9525-caa67087fc93.png)

**Which versions of Sanity are you using?**
@sanity/cli                2.10.0 (up to date)
@sanity/base               2.10.2 (up to date)
@sanity/color-input         2.2.6 (up to date)
@sanity/components          2.2.6 (up to date)
@sanity/core               2.10.2 (up to date)
@sanity/default-layout     2.10.2 (up to date)
@sanity/default-login       2.8.0 (up to date)
@sanity/desk-tool          2.10.2 (up to date)
@sanity/google-maps-input  2.10.2 (up to date)
@sanity/vision             2.10.0 (up to date)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
