### ISSUE TITLE
sanity/cli init yields "Error: Failed to communicate with the Sanity API: Unauthorized - Session not found. "

### ISSUE THREAD

**Issue by MarkTension** [sanity-io/sanity#2503]
**Describe the bug**
doing sanity init via the cli in the root folder of a react app yields:

```
Error: Failed to communicate with the Sanity API:
Unauthorized - Session not found. For more information, see https://docs.sanity.io/help/cli-errors.
    at /usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4356:3725
```

before the error is thrown, sanity notices that I already have an account

`Looks like you already have a Sanity-account. Sweet!

**What operating system are you using?**
MacOS

**Which versions of Node.js / npm are you running?**
I'm using @sanity/cli version 2.10.0

**npm and node versions:**
6.14.8
v10.16.0

**Comment by MarkTension** [comment]
Could solve this with sanity logout , and doing sanity init again.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
