### ISSUE TITLE
Cannot create new documents on version 2.10: Template "undefined" has invalid "value" property

### ISSUE THREAD

**Issue by fvieira** [sanity-io/sanity#2505]
**Describe the bug/Steps to reproduce**
We cannot create a new document on Sanity, when we press the create button the following error appears on the pane to the right: "Error Check developer console for details", while on the developer console, it gives the following error: "Failed to resolve initial value".

**Screenshots**
![Screenshot from 2021-05-21 11-23-49](https://user-images.githubusercontent.com/390867/119124227-5906ad00-ba28-11eb-98c2-b15fe565d718.png)

**Which versions of Sanity are you using?**
@sanity/cli                2.10.0 (up to date)
@sanity/base               2.10.2 (up to date)
@sanity/cli                2.10.0 (up to date)
@sanity/components          2.2.6 (up to date)
@sanity/core               2.10.2 (up to date)
@sanity/dashboard           2.7.0 (up to date)
@sanity/default-layout     2.10.2 (up to date)
@sanity/default-login       2.8.0 (up to date)
@sanity/desk-tool          2.10.4 (up to date)
@sanity/google-maps-input  2.10.2 (up to date)
@sanity/storybook          2.10.2 (up to date)
@sanity/vision             2.10.0 (up to date)

**What operating system are you using?**
Ubuntu 19.10

**Which versions of Node.js / npm are you running?**
npm - 6.14.4
node - v12.16.2

**Additional context**
We rolled back to Sanity 2.9.1 version and the issue is gone.

Let us know if you are not able to reproduce.

**Comment by rexxars** [comment]
Hi, thanks for reporting!

Do you have an `initialValue` property set on the `page` template?
Do you have any initial [initial value templates](https://www.sanity.io/docs/initial-value-templates) defined?

**Comment by fvieira** [comment]
Hi, we don't have either of those, we did have initialValue on some fields of some objects that are were used inside the page document, but to try to find the problem we reduced our whole schema to a page document with two simple fields and no initialValues and the problem still happened. We even tried pointing our studio at a different dataset with totally different data and it didn't help.
What we didn't try was to simply start a project from scratch, but if you're not able to reproduce the bug we can try this and start copying code from our project until the error happens.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
