### ISSUE TITLE
Add support for `defaultOrdering` on `documentTypeListItem`

### ISSUE THREAD

**Issue by coreyward** [sanity-io/sanity#2534]
The Structure Builder makes it easy to show a list item that expands into a list of documents corresponding with the list item via `documentTypeListItem`. It also makes it easy to set the default order of items in a list using `defaultOrdering`. Unfortunately, combining these two things is made to be rather difficult because `documentTypeListItem` does not behave like a `list` but instead like a `listItem`.

**Describe the solution you'd like**
I'd like to see `documentTypeListItem` get support for chaining `list` methods like `defaultOrdering`.

**Describe alternatives you've considered**
The alternative is to manually use `list` or `documentTypeList`, but these lose optimizations and additional features provided by `documentTypeListItem`.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by coreyward** [comment]
@kmelve I believe the new v3 behavior is the same here, right? That's what the [documentation seems to suggest](https://www.sanity.io/docs/structure-builder-reference#f6208b48be60). If so, I'd love to get this issue re-opened with a v3 tag or similar to keep the context (all the 👍 demonstrating the popularity of this request, namely).
