### ISSUE TITLE
Enable specifying Sanity client version for the Studio

### ISSUE THREAD

**Issue by coreyward** [sanity-io/sanity#2535]
**Is your feature request related to a problem? Please describe.**
v1 of the GROQ API has a number of shortcomings that prevent filtering of data in common scenarios that have been resolved with the newer vX or date-based versions of the API. Unfortunately, the Studio stubbornly clings to v1 in all scenarios without the possibility to override it or to pass in a client configured with the newer APIs.

**Describe the solution you'd like**
I'd like to have a way to pass the client instance or configuration to use for Structure Builder methods, or for there to be a way to configure the API version to utilize in sanity.json.

**Describe alternatives you've considered**
In some cases it is possible to manually build lists using a versioned client directly, but this means losing a lot of the functionality provided out of the box by Structure Builder methods like `documentList`.

**Comment by judofyr** [comment]
It's supported in quite a few places already, but I guess we're missing some cases. Let's try to keep track of them here:

- [ ] Structure Builder
- [ ] `filter` field in Reference-type: https://www.sanity.io/docs/reference-type#filter-ebd7a95f9dc6

Anything else?

**Comment by alexbchr** [comment]
@judofyr Any update on when this is coming? I am mainly interested by the support in `filter` field on Reference Types

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
