### ISSUE TITLE
Title not generated for image fields

### ISSUE THREAD

**Issue by OllieJT** [sanity-io/sanity#2536]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

When defining the schema, you can omit the title  and sanity will capitalise the name field as a fallback. This does not work for fields within the image type.

**To Reproduce**

1. Add an image type to your schema
2. Add a field to the image type with the `name:` and `type:` properties (not `title:`
3. View the schema in a sanity studio

**Expected behavior**

The title should be generated from the `name:`

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**
```
    "@sanity/base": "^2.10.5",
    "@sanity/components": "^2.2.6",
    "@sanity/core": "^2.10.5",
    "@sanity/default-layout": "^2.10.5",
    "@sanity/default-login": "^2.10.5",
    "@sanity/desk-tool": "^2.10.5",
```

**Which versions of Node.js / npm are you running?**

NPM: 6.14.13
Node: v14.17.0

**Additional context**

This will apply the title Something
```
const someObject = {
	type: "object",
	name: "something"
    fields:[...]
}
```

However “another_thing” will not get the same treatment:
```
const someObject = {
	type: "image",
	name: "something"
    fields:[
        {
            type: "string",
            name: "another_thing"
        }
    ]
}```

**Comment by mornir** [comment]
I remember reading somewhere that Sanity users shouldn't rely on that fallback and should always add titles to fields. Make me wonder if this fallback is bound to be deprecated in the future.

**Comment by OllieJT** [comment]
@mornir Yeah I don't think this is a big issue, I just shared as it didn't seem like the intended behaviour

**Comment by judofyr** [comment]
I agree that we should at least be consistent!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
