### ISSUE TITLE
Asset Upload - Sanity Types ReadStream vs Readable Stream

### ISSUE THREAD

**Issue by SharonStrats** [sanity-io/sanity#2537]
When you are using Typescript there is an error with types using the client.asset.upload('image', createReadStream,...) shown in Sanity documentation as how to use this function. The problem is that createReadStream (fs) returns a ReadStream, while Sanity types excepts a File,Blob, Buffer, or ReadableStream. 

There is another side effect issue this creates, I am writing it here for those struggling it may help.  There is a separate issue with ReadableStream in general and that is the dom version of ReadableStream is different from the node version.  So depending on where you are using this (frontend or backend app) and what libs you are including in your tsconfig, this is something to look out for.

**To Reproduce**

I have created this repository which you can clone and see how I have gotten around the issue for now https://github.com/SharonStrats/sanity-migration. If you remove the casting and use createReadStream directly you will get the type error I am referring to.

**Expected behavior**

There should not be a type error.

**Which versions of Sanity are you using?**

@sanity/client 2.10.5

I suggest adding ReadStream to the types accepted for the body argument in client.assets.upload() in sanityClient.d.ts

**Comment by judofyr** [comment]
I think that `ReadableStream` is a typo in this type definition. I don't think we support the browser-based `ReadableStream` interface. This was intended to be `stream.Readable` (from Node). However, I'm not sure what the recommended way is to solve this typing issue. We ned the `stream.Readable` from `@types/node`, but then I think we need to add `@types/node` as a regular dependency (which is not optimal).

Do you know what's the recommended way to resolve this is?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
