### ISSUE TITLE
@sanity/form-builder - on paste, both browser default and custom paste handlers may be triggered

### ISSUE THREAD

**Issue by dominicm00** [sanity-io/sanity#2543]
**Describe the bug**

In the block editor, paste events are first triggered on the local `span` before bubbling up to the `PortableTextEditor` where paste handlers are triggered. 

In Chrome (v. 91.0.4472.77) on "normal" paste (Ctrl+V), there is no browser default behavior for the `span` paste and the event bubbles up to `PortableTextEditor` with no other side effects, where it is handled and `preventDefault` is called. In Firefox (v. 89.0) on paste (Ctrl+V) and Chrome (v. 91.0.4472.77) on "paste as plain text" (Ctrl+Shift+V), the browser pastes the clipboard inside the `span` **before** the custom paste handler is called at the `PortableTextEditor` level, causing both the clipboard contents and the value of the custom paste handler to be inserted. This is possibly due to inconsistent behavior around `contentEditable`.

**To Reproduce**

1. Create a custom editor with an `onPaste` function that returns an `insert` patch:
```js
import React from "react";
import { BlockEditor } from "part:@sanity/form-builder";
import blockTools from "@sanity/block-tools";

export class CustomEditor extends React.PureComponent {
  render() {
    return (
      <div>
        <BlockEditor {...this.props} onPaste={handlePaste} />
      </div>
    );
  }
}

function handlePaste(input) {
  const { path, type } = input;

  let blocks = blockTools.htmlToBlocks("<p>Some HTML</p>", type);

  return { insert: blocks, path };
}
```
2. Create block content with the custom editor:
```js
/* snip */
{
  title: "Content",
  name: "content",
  type: "array",
  inputComponent: CustomEditor,
  of: [
    {
      type: "block",
    },
  ],
},
/* snip */
```

3. Paste text into the editor

**Expected behavior**

Whatever is returned from the custom paste handler would be inserted into the editor.

**Actual behavior**

Both the raw clipboard text and the custom paste handler values are inserted into the editor.

**Videos**
Firefox:

https://user-images.githubusercontent.com/33702823/121250270-88fcdf80-c873-11eb-90b4-ab3a9a190297.mp4

Chrome:

https://user-images.githubusercontent.com/33702823/121250282-8e5a2a00-c873-11eb-82a6-5803e59235de.mp4

**Which versions of Sanity are you using?**

@sanity/cli             2.10.5 (up to date)
@sanity/base            2.10.5 (up to date)
@sanity/components       2.2.6 (up to date)
@sanity/core            2.10.5 (up to date)
@sanity/default-layout  2.10.5 (up to date)
@sanity/default-login   2.10.5 (up to date)
@sanity/desk-tool       2.10.5 (up to date)
@sanity/vision          2.10.5 (up to date)

**What operating system are you using?**

Tested on MacOS Big Sur and Manjaro Linux

**Which versions of Node.js / npm are you running?**

npm: 7.15.1
Node.js: v16.3.0

**Comment by judofyr** [comment]
Wow, thanks for a great issue! These things are always complicated to get correct across browsers and various versions, and maybe in this case there might not even be a good way of solving it (since who knows how `contentEditable` works?). I've put it into our internal backlog, but it might take some time for us to look at it.

**Comment by SimonGribert** [comment]
I had the same issue and took some help from the Sanity Slack community. Simply adding `event.preventDefault()` solved the issue for me.

Something like this:

```
import React from "react";
import { BlockEditor } from "part:@sanity/form-builder";
import blockTools from "@sanity/block-tools";

export class CustomEditor extends React.PureComponent {
  render() {
    return (
      <div>
        <BlockEditor {...this.props} onPaste={handlePaste} />
      </div>
    );
  }
}

function handlePaste(input) {
  const { event, path, type } = input;
  event.preventDefault();

  let blocks = blockTools.htmlToBlocks("<p>Some HTML</p>", type);

  return { insert: blocks, path };
}
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
