### ISSUE TITLE
O(n) query performance when retrieving one item from large dataset

### ISSUE THREAD

**Issue by fusepilot** [sanity-io/sanity#2561]
**Describe the bug**

Returning index 0 of a ~10K long dataset is fast (23ms execution). Returning index 9,000 takes 2,184ms (~100x).  My expectation was that this query should be constant O(1) time since I’m ultimately asking for only 1 document. The docs say the technical doc limit is 1M. so extrapolating at this rate, returning index 1M from this dataset would take ~24,000ms (~1,000x) as long to execute. I'm not sure if performance is expected or not, but either way, it removes Sanity as an option for certain types of use cases. So it seems like a bug or at least the use case of a feature request.

**To Reproduce**

1. Create a dataset with 10,000 of a single small schema called "item".
2. In Vision, create a query return item `[0]` of the array.
3. Observe low execution time.
4. In Vision, create a query return item `[9000]` of the array.
5. Observe high execution time.

**Expected behavior**

Both queries return 1 item. So I expect them to take the same amount of time regardless of where they are in the dataset. 

**Screenshots**
![image](https://user-images.githubusercontent.com/187164/122444185-27b0cc80-cf55-11eb-9c71-bc98bdd1891e.png)
![image](https://user-images.githubusercontent.com/187164/122444207-2aabbd00-cf55-11eb-830d-f553a60b4acf.png)

**Feature Request (if applicable)**

If this is intended behavior, then I think there should be a way of letting the developer specify the optimization themselves.

- Allow developers to set additional indexes in the schema: `indexable: [ { name: 'myIndexColumn' } ]`
- Allow developers to query by those indexes in GROQ:  `*[_type=="item" && global::index('myIndexColumn', 9000)].title`

**Which versions of Sanity are you using?**

@sanity/cli                     2.10.5 (latest: 2.11.0)
@sanity/base                    2.11.1 (latest: 2.11.2)
@sanity/block-content-to-react   3.0.0 (up to date)
@sanity/cli                     2.11.0 (up to date)
@sanity/components               2.2.6 (up to date)
@sanity/core                    2.11.0 (up to date)
@sanity/default-layout          2.11.1 (latest: 2.11.2)
@sanity/default-login           2.11.1 (up to date)
@sanity/desk-tool               2.11.1 (latest: 2.11.2)
@sanity/production-preview       2.2.6 (up to date)
@sanity/vision                  2.11.0 (latest: 2.11.2)

**What operating system are you using?**

macOS 11.3.1
Chrome 91.0.4472.77

**Which versions of Node.js / npm are you running?**

6.14.12
v12.22.1

**Comment by judofyr** [comment]
Yes, you are correct that offset queries are not optimized. This is intentional since it's not a very common use case. Most other databases have the same limitations. PostgreSQL for instance does also not process `OFFSET n` in O(1) time.

What problem are you trying to solve? Pagination? Or are you trying to fetch all the rows efficiently in batches? Either way there we should have ways to handle these cases.

**Comment by fusepilot** [comment]
Thanks for the reply @judofyr. Yes, pagination is the main use case. But batching all is also a need for certain scenarios I'm facing. Could you share what the recommended solutions are to both? The existing resources I've found on Sanity pagination don't address the O(n) performance as I've described above in larger datasets, so I'd be grateful for any pointers on how to avoid that pitfall.

**Comment by judofyr** [comment]
I can share some notes here. We should probably write this up somewhere else because it keeps popping up. These techniques are quite generic and I've also successfully used them in e.g. SQL databases.

**Context**: Let's say we want to fetch all posts ordered by title.

**First batch**: `*[_type == "post"] | order(title) [0...100]`

To fetch the first page/batch we use a regular slice. Nothing special here. Next we'll look at the _last entry_ in that batch and find the title and the _id. Let's call these `$lastTitle` and `$lastId`.

**Next batch**: `*[_type == "post" && (title > $lastTitle || (title == $lastTitle && _id > $lastId))] | order(title) [0...100]`

To fetch the next page we'll ask for anything which has a title _greater_ than the last title we saw. We've also here added a condition `title == $lastTitle && _id > $lastId` which catches the case where multiple posts have the same title. If we know that the field we're sorting on is unique we can drop this part (e.g. the query becomes `*[_type == "post" && title > $lastTitle] | order(title) [0...100]`.

We then once again find the last title/_id and use that to fetch the next batch. We can do this until the returned batch is less than 100 rows (and then we know we've reached the end).

**Finding total number of entries**: `count(*[_type == "post"])`

This query should be quite fast (it's strictly speaking also O(n), but it's optimized in a special way which practically makes it fast). You can execute this once initially and keep the count as you're iterating over the data.

**What if the data changes?**

This approach isn't guaranteed to give you all the data if it keeps changing. Example: There's a post that starts with the title "Zombie War", and after we've processed all titles starting with "B" it changes title to "A Zombie War".

If it's really critical that you're able to fetch _all_ posts then I think the only way is to sort by `_updatedAt`: Do the same trick, but `order(_updatedAt)` instead. Anything that gets updated you'll see twice.

**Comment by judofyr** [comment]
Closing since there were no follow-up questions.
