### ISSUE TITLE
Fail to install @sanity/cli  as dependency

### ISSUE THREAD

**Issue by xnslx** [sanity-io/sanity#2566]
<img width="818" alt="Screen Shot 2021-06-21 at 10 37 34 AM" src="https://user-images.githubusercontent.com/51500554/122823250-bcdcf980-d2a4-11eb-8b93-6185b1efcce6.png">
 
Not sure what is the reason.

**Comment by rexxars** [comment]
This happens because you are installing `@sanity/cli` using the `-g` (global) flag. This enables you to run commands like `sanity init` and `sanity login` in any folder. If you want to install it for your project only, you can do so by dropping the `-g` flag:

```
npm install @sanity/cli
```

It's a little more cumbersome to work with it if doing it this way - you'll have to use npm scripts like `npm start` instead of `sanity start` when running the studio, for instance. This is why we recommend installing it globally, with the `-g` flag.
