### ISSUE TITLE
Export assets using original filenames

### ISSUE THREAD

**Issue by svu-aau** [sanity-io/sanity#2596]
Hi, would like to make a feature request for the `sanity dataset export` command:  please add option to allow exporting the assets using their original filenames.

thanks!
Steve

**Comment by judofyr** [comment]
Thanks for the feature request! We've added it to our backlog.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
