### ISSUE TITLE
Set the default block styling to something other than normal

### ISSUE THREAD

**Issue by j2is** [sanity-io/sanity#2598]
Say I have the following heading 2 style defined, the editor would have to know to click the dropdown and change the style to a heading two, is there a way to disable the 'normal' setting that is always shown? Or at least be able to specify the default block style for each block?

```
export default {
  title: "Content",
  name: "headingTwo",
  type: "array",
  of: [
    {
      title: "Block",
      type: "block",
      styles: [{ title: "Heading 2", value: "h2" }],
      lists: [],
      marks: {
        decorators: [],
        annotations: [],
      },
    },
  ],
};

```

**Comment by judofyr** [comment]
Interesting! I tried looking into where the default "Normal"-style was being added, but it wasn't fully obvious to me. It looks like a bug to me; I'll ask around.

(Moving this issue into the Sanity repo since this is related to Studio's editor and not the React front end rendering.)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
