### ISSUE TITLE
The studio does not respond to a blockEditor property on lists

### ISSUE THREAD

**Issue by geball** [sanity-io/sanity#2601]
**Describe the bug**

When creating a list to use in the portable text editor, the studio does not seem to handle the `blockEditor` property. In the following example, the `blockEditor` code seems to be ignored.

```
lists: [
  { title: 'Bullet', value: 'bullet' },
  { title: 'Numbered', value: 'number' },
  {
    title: 'Feature List',
    value: 'feature',
    blockEditor: {
      // this does not work
      render: (props) => props.children.map((c) => <span>✓ {c}</span>)
      // this does not work either
      render: (props) => <span>✓ {props.children}</span>
    }
  }
],
```

**To Reproduce**

1. [Configure a list](https://www.sanity.io/docs/configuration#ed754a09e693) in the portable text editor schema.
2. Add a `blockEditor` field and add some code that would seem to work in any other field.

**Expected behavior**

It's expected that the list would respond to the `blockEditor` field and render accordingly.

**Which versions of Sanity are you using?**

2.12.2

**What operating system are you using?**

macOS 11.3

**Which versions of Node.js / npm are you running?**

7.18.1
v16.4.0

**Additional context**

Additional context and discussion is available at [this thread](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1624808700329400).

**Comment by alexandereneroth** [comment]
I found that the `icon` property on the `blockEditor` object works, but not `render`

**Comment by skogsmaskin** [comment]
Thanks for reporting! We will look into this. It's not officially supported in our current feature set (you would have to use custom rendering on the block itself for this).

**Comment by khendrikse** [comment]
I did a little hacky solution to get around this by grabbing it using an HTML attribute:

```
/* style the checkmark list inside the rich text editor */
div[data-list-item='checkmark'] > div::before {
  content: '✔';
  font-size: 12px;
  margin-left: 20px;
  margin-top: 3px;
}
```

Not saying this should be the way to go :p but it's something 😓

**Comment by xeniajensen** [comment]
I have the same issue, but [@khendrikse 's workaround](https://github.com/sanity-io/sanity/issues/2601#issuecomment-994516963) worked for me as weel

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
