### ISSUE TITLE
RTL support for Portable Text

### ISSUE THREAD

**Issue by tomasbal** [sanity-io/sanity#2613]
**Is your feature request related to a problem? Please describe.**
Currently when you try to enter RTL based language into the Portable Text, it accepts but breaks the formatting.

**Describe the solution you'd like**
The Portable Text to accept natively RTL languages and apply the adequate formatting.

**Describe alternatives you've considered**
Leave it as  it is, because you can pull the data from the API just fine, but it's really hard to fix/format the text when the formatting breaks, it's hard for the editors to work with RTL based languages.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by ablbol** [comment]
The Ordered / Unordered lists look really bad when dealing with RTL languages in the portable text.  Could you please fix that. 
Thanks

**Comment by noamalffasy** [comment]
![image](https://github.com/sanity-io/sanity/assets/7583207/25aba066-18c3-4f6a-b7fb-5f24a0e7d64e)

It is still an issue!
