### ISSUE TITLE
Make descriptions more accessible

### ISSUE THREAD

**Issue by DanielGJohnsen** [sanity-io/sanity#2617]
When using a defined object in a document, you can add a description which renders as a gray smaller text below the title, but when this object is used as a `type` in an array, the description does not show in the object modal opened. 
Also, the object description should show in the list underneath the title when you click the "Add item ...." button (or make a property `showDescription` to allow for toggling it of or on).

The description should also be allowed to be set in the `type: 'array'` itself, so it takes precedence. 
Ie:
```
name: 'myObject'.
description: 'This is default description'
``` 
would be a fallback if not providing:
```
type: 'array',
of: [
  { type: 'myObject', description: 'This is description used in the array' }
]
```

PS. If possible in one go, allow for markup in descriptions, would be nice with to inject a `</ br>` for readability

**Comment by judofyr** [comment]
This sounds like a sensible feature request although I could see it being problematic if we _automatically_ use the object description since they might be quite long today. I've added this to our backlog.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
