### ISSUE TITLE
Publish dashboard-widget-structure-menu to NPM

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/sanity#2620]
I have used dashboard-widget-structure-menu in a couple of projects, but I have to manually copy-paste the files each time. 

It would be great if sanity could publish this to `npm` as it would be easier to use and fix bugs related to it ( eg: #1685 )

[example use in a sanity project](https://github.com/sanity-io/sanity-template-kitchen-sink/tree/main/template/studio/plugins/dashboard-widget-structure-menu)

**Comment by judofyr** [comment]
This sounds very sensible. I've added it to our internal backlog.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
