### ISSUE TITLE
Not able to rename images/files on upload

### ISSUE THREAD

**Issue by edison-burnkit** [sanity-io/sanity#2627]
> ![5228dfc3-c273-4faf-a666-bc2603bbe193](https://user-images.githubusercontent.com/1131579/50371694-618cfc00-05c0-11e9-9574-4d5e8c7e36fc.gif)
> 
> I suspect this happens because of the hash matching thing. But i can see how it’s confusing for users. Not sure how to best go about it? Should we have some feedback telling what happened. Should it be overwritten with new file name?

I am quoting an issue which has been closed without any solution. This also happens to File type. Is there any update? How can we easily rename files? Thanks.

**Comment by judofyr** [comment]
(Here's the previous issue: https://github.com/sanity-io/sanity/issues/1139)

**Comment by judofyr** [comment]
What's happening here is that we determine that the file is already uploaded and then we use the file name from the time when it was originally uploaded. And currently a file only has a single file name. In this situation we _could_ update the file name, but then it would also be updated in the original place where it was uploaded.

What behavior would be best for you? Let the user know that the file already exists? Update the file with the "new" file name? Or would you actually prefer if files had "multiple" file names?

**Comment by edison-burnkit** [comment]
> What's happening here is that we determine that the file is already uploaded and then we use the file name from the time when it was originally uploaded. And currently a file only has a single file name. In this situation we _could_ update the file name, but then it would also be updated in the original place where it was uploaded.
> 
> What behavior would be best for you? Let the user know that the file already exists? Update the file with the "new" file name? Or would you actually prefer if files had "multiple" file names?

Thanks for your reply. My understanding is that it should update the file with the "new" file name. Is it something easy to achieve?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
