### ISSUE TITLE
Some of my asset url return an error when "?dl" parameter

### ISSUE THREAD

**Issue by JobiJoba** [sanity-io/sanity#2667]
**Describe the bug**

I've a document that contain a file (audio). 
In Sanity Studio, when I want to download that file it gives me an error 

```
Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.
```

If I try to do an export with the assets, it fails after the file 1000+ (it gives me the same error) (which means that it's not doing that for all the files)

When I look at the URL he failed to reach, I  see that at the end he have a "?dl" - If I remove  that, my file is downloaded correctly

**To Reproduce**

I don't know how to reproduce as I don't know what cause the fact that some of the files are corrupted when it has the "?dl" parameters ?

**Expected behavior**

Would be nice if all my files are downloaded correctly  ;) 

**Which versions of Sanity are you using?**

@sanity/cli             2.12.2 (latest: 2.14.0)
@sanity/base            2.12.2 (latest: 2.14.0)
@sanity/components       2.2.6 (latest: 2.14.0)
@sanity/core            2.12.2 (latest: 2.14.0)
@sanity/default-layout  2.12.2 (latest: 2.14.0)
@sanity/default-login   2.11.1 (latest: 2.14.0)
@sanity/desk-tool       2.12.2 (latest: 2.14.0)
@sanity/vision          2.11.2 (latest: 2.14.0)

**What operating system are you using?**

MacOs Catalina

**Which versions of Node.js / npm are you running?**

7.5.0
v14.15.4

**Additional context**

The files  that are uploaded are in Thai Script (ex:  "ไปดูหนังกันเถอะ.mp3")

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
