### ISSUE TITLE
vulnerability CVE-2021-23382 is introduced in @sanity/webpack-integration 

### ISSUE THREAD

**Issue by ayaka-kms** [sanity-io/sanity#2673]
Hi, @bjoerge @rexxars, a vulnerability CVE-2021-23382 is introduced in @sanity/webpack-integration  via:
●  @sanity/webpack-integration@2.13.1 ➔ postcss-cssnext@3.1.0 ➔ autoprefixer@7.2.6 ➔ postcss@6.0.23

However, postcss-cssnext is a legacy package, which has not been maintained for about 4 years.
Is it possible to migrate postcss-cssnext to other package to remediate this vulnerability?

I noticed several migration records in other js repo for postcss-cssnext:

1. in nuxt, version 1.4.5 ➔ 2.0.0, migrate postcss-cssnext to postcss-preset-env via [commit](https://github.com/nuxt/nuxt.js/commit/8acef8d01ec77e24cc930e6025e324d277af57a1)
2. in mwp-cli, version 8.2.454-beta ➔ 8.2.480-beta, migrate postcss-cssnext to postcss-preset-env via [commit](https://github.com/meetup/mwp-cli/commit/6927d5c48d20ef3ae6d7a1e70ec9a843059f13be)

Thanks.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
