### ISSUE TITLE
Superimpose watermarks on images

### ISSUE THREAD

**Issue by ryansheehan** [sanity-io/sanity#2730]
**Is your feature request related to a problem? Please describe.**
In an effort to curb copyright infringement, I would like to watermark my images

**Describe the solution you'd like**
When uploading images, it would be nice to, optionally, size and position a watermark.  It would work similar to the hotspot functionality. 

**Describe alternatives you've considered**
Today we manually add our watermark to our source images

**Additional context**
[Imgix](https://docs.imgix.com/tutorials#stq=watermark&stp=1) has a feature to overlay/watermark images with their api.  The images are cached in their cdn.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
