### ISSUE TITLE
Documentation for the 'fields' property of the file type is incomplete/misleading

### ISSUE THREAD

**Issue by baybars1223** [sanity-io/sanity#2753]
**Is your feature request related to a problem? Please describe.**
The documentation for the ['fields' property of the file type](https://www.sanity.io/docs/file-type#fields-93a1b58234d2) doesn't tell you that using the property inside another document will cause `sanity graphql deploy` to fail due to `Error: Encountered anonymous inline file "[field name]" for field/type "[document type]". To use this field with GraphQL you will need to create a top-level schema type for it.`   

**Describe the solution you'd like**
The documentation and examples included with it should make it clear that you have to create a 'new' type and add it to the schema to use the 'fields' property of the file type.  
Incidentally, I didn't even know that it was possible to import a definition with a type other than 'document' or 'object' into the schema or that you could 'extend' the native types by doing so. Some documentation on that would be nice. The documentation on [lift anonymous object type](https://www.sanity.io/help/schema-lift-anonymous-object-type) should also be updated to reflect that it applies to schema definitions of type `file` (and possibly other types?) as well as to definitions of type `object`.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
