### ISSUE TITLE
Callback to close popups

### ISSUE THREAD

**Issue by ryansheehan** [sanity-io/sanity#2775]
**Is your feature request related to a problem? Please describe.**
I've added an emoji picker to my project to insert emoji into block content.  Everything works great, but It would be nice to be able to automatically close the popup when the user selects their emoji.  Currently they have to hit escape or click the `x` to dismiss the popup

**Describe the solution you'd like**
A hook in the props given to the component that would close the popup

**Describe alternatives you've considered**
An option here is to add a _currently selected_ view of the emoji to make it clear to the user they have selected an emoji

**Update**
As a work around, a faux keyboard event can be used to dismiss the popup

```javascript
// simulate escape key event to close popup
      const keyboardEvent = new KeyboardEvent('keydown', {
        bubbles: true, 
        key: 'Escape', 
        code: 'Escape',
      });

      document.dispatchEvent(keyboardEvent);
```

**Additional context**

![image](https://user-images.githubusercontent.com/7987783/133304130-7efd4827-277a-465d-870f-fc6decfb6047.png)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
