### ISSUE TITLE
GitHub login issue

### ISSUE THREAD

**Issue by handletastic** [sanity-io/sanity#2829]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Cannot login locally via with GitHub as a login provider

**To Reproduce**

1. Create a new sanity project
2. Run sanity init
3. Run sanity login choose GitHub
4. Run sanity start
5. Click on GitHub button
6. Following error appears (check screenshot)

**Expected behavior**

To be able to login successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/16025440/136074300-d051c5bc-33ad-4a95-a519-3aa6f46dc9aa.png)

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.
sanity versions
@sanity/cli             2.20.0 (up to date)
@sanity/base            2.20.0 (up to date)
@sanity/core            2.20.0 (up to date)
@sanity/default-layout  2.20.0 (up to date)
@sanity/default-login   2.19.0 (up to date)
@sanity/desk-tool       2.20.0 (up to date)
@sanity/vision          2.20.0 (up to date)

**What operating system are you using?**
macOS 10.15.7

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
npm -v && node -v
7.21.1
v16.9.1

**Comment by afrieirham** [comment]
Not sure which browser you are using but I faced the same issue using Brave, I turn down the shield and now it works.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
