### ISSUE TITLE
List and document redraw when switching panes/tabs

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2858]
**Describe the bug**

There's an annoying redraw/refresh/reload issue when switching panes.

**To Reproduce**

See video.

**Expected behavior**

The document list and document title/header should not disappear.

**Screenshots**

https://user-images.githubusercontent.com/2749/137186305-9d8bb1c0-1e69-4398-af90-6500c88855c5.mov

**Which versions of Sanity are you using?**

@sanity/cli                      2.21.0 (up to date)
@sanity/base                     2.21.2 (up to date)
@sanity/code-input               2.21.2 (up to date)
@sanity/color-input              2.21.2 (up to date)
@sanity/components               2.14.0 (up to date)
@sanity/core                     2.21.0 (up to date)
@sanity/dashboard                2.21.2 (up to date)
@sanity/default-layout           2.21.2 (up to date)
@sanity/default-login            2.21.0 (up to date)
@sanity/desk-tool                2.21.2 (up to date)
@sanity/google-maps-input        2.21.2 (up to date)
@sanity/image-url                 1.0.1 (up to date)
@sanity/language-filter          2.21.0 (up to date)
@sanity/orderable-document-list   0.0.1 (up to date)
@sanity/vision                   2.21.2 (up to date)

**What operating system are you using?**

macOS

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
