### ISSUE TITLE
Vercel integration fails when not logged in

### ISSUE THREAD

**Issue by ghostdevv** [sanity-io/sanity#2879]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Vercel integration fails when not logged in to sanity

**To Reproduce**

1. Go to https://vercel.com/integrations/sanity
2. Sign in to vercel
3. Make sure you are signed out of sanity
4. Press add integration on vercel
5. the popup opens, you select your project, and it takes you to sanity
6. You are greeted with a blank screen

**Expected behavior**

If you aren't logged in it should ask you to login before continuing

**Which versions of Sanity are you using?**

Latest

**What operating system are you using?**

Arch Linux x64

**Which versions of Node.js / npm are you running?**

n/a

**Security issue?**

No

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
