### ISSUE TITLE
Nested Popup closes itself instantly once it opens

### ISSUE THREAD

**Issue by vin-ni** [sanity-io/sanity#2882]
**Describe the bug**

Nested Popup closes itself instantly once it opens. I believe it's due to sanity saving stuff in the background which makes it close

**To Reproduce**

1. Open Text Editor
2. Write some Text
3. Apply custom footnotes
4. Write Footnotes and inser Link
5. Popup closes automatically

**Expected behavior**

Popup stays open

**Screenshots**

https://user-images.githubusercontent.com/9806572/138100258-6609f1ec-f251-4d71-8845-0396fa408a39.mp4

**Which versions of Sanity are you using?**

@sanity/cli             2.19.1 (latest: 2.21.5)
@sanity/base            2.20.0 (latest: 2.21.5)
@sanity/color-input     2.20.0 (latest: 2.21.5)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.20.0 (latest: 2.21.5)
@sanity/default-layout  2.20.0 (latest: 2.21.5)
@sanity/default-login   2.19.0 (latest: 2.21.4)
@sanity/desk-tool       2.20.0 (latest: 2.21.5)
@sanity/vision          2.21.5 (up to date)

**What operating system are you using?**
Mac

**Which versions of Node.js / npm are you running?**

7.23.0
v12.18.2

Thanks :)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
