### ISSUE TITLE
Not working with Nx

### ISSUE THREAD

**Issue by ajereos-circadence** [sanity-io/sanity#2887]
I'm using Nx as monorepo, seems tsconfig only works in the editor but not when on dev or build. My guess is, this is related to webpack. Hope anyone solved this issue.

**To Reproduce**

1. create new app for sanity
2. create shared lib
3. include shared lib to sanity

**Expected behavior**

It should work as the editor, but it's not.

**Which versions of Sanity are you using?**

Recent

**Which versions of Node.js / npm are you running?**

14.17.4

**Comment by animamundi** [comment]
I also think this is related to Webpack. Sanity is using it's own internal Webpack configuration so it does not hook into the Nx Webpack configuration, which is where all of the shared libraries are linked up. Using a custom Webpack configuration might help to work around this.

There is an issue open for customizing the Webpack config here: https://github.com/sanity-io/sanity/issues/1609,
and one of the comments points to a solution for customizing the Webpack config: https://github.com/sanity-io/sanity/issues/2092#issuecomment-1004517695

**Comment by simonpeters** [comment]
any update on this for v3?

**Comment by kmelve** [comment]
Studio v3 is bundler-agnostic and introduces Vite as its new default bundling tool. You should probably have luck with it!

---

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by nestorbfgo** [comment]
@ajereos-circadence  Hi, Any workaround to use sanity inside of a Nx monorepo? Currently I don't find a solution to do it ?

**Comment by yehonadav** [comment]
i couldn't make it work and had to add my sanity project to .nxignore, which is a shame
@kmelve mb you can elaborate on how to use sanity with a viteconfig file? it would be really helpful if i can just create an nx react app with vite and then point it to sanity plugins and schema
