### ISSUE TITLE
[BABEL]: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "Identifier"

### ISSUE THREAD

**Issue by rohit1101** [sanity-io/sanity#2899]
**Describe the bug**

I have no idea why I am getting this error, initially I got this on my personal project but then I test on a brand new sanity project (blog schema) and ran `sanity graphql deploy` and I am still figuring out what's wrong from yesterday.

`TypeError: [BABEL]: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "Identifier" (While processing: /Users/MSD/Desktop/dev/projects/test/node_modules/@babel/preset-env/lib/index.js)
`

**To Reproduce**

1. `sanity init`
2. choose any template I chose Blog schema
3. `cd project_name`
4. run `sanity graphql deploy`

**Expected behavior**

A new graphql deploy for the existing schema but instead got the following out in the screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/37110560/139623703-a6e03a2c-e3b6-4cab-9083-96406707c388.jpeg)

**Which versions of Sanity are you using?**
@sanity/cli version 2.21.7

Run `sanity versions` in the terminal and copy-paste the result here.
@sanity/cli  2.21.7 (up to date)

**What operating system are you using?**
macOS Monterey version 12.0.1

**Which versions of Node.js / npm are you running?**
node => v16.13.0
npm => 8.1.0

**Comment by imjordanm** [comment]
I have the exact same issue right now. I will let you know if I figure out a fix.

**Comment by rohit1101** [comment]
Cool @imjordanm will do the same.

**Comment by chalas-ch** [comment]
Hello, I have the same issue too, I have no clue what is causing it though 😦

**Comment by jamiehenson** [comment]
Also experiencing this, and I believe the issue is to do with [this](https://babeljs.io/blog/2021/10/29/7.16.0) release, which dropped last Friday - a few days after Sanity `2.21.7`. This problem arises for me with a fresh set of packages, but not with a local project that uses pre-`7.16.0` Babel packages.

**Comment by jamiehenson** [comment]
As for _why_ the issue is happening in particular with this new version of Babel, currently still investigating.

**Comment by ricokahler** [comment]
Hi we're aware of this issue and it's very high priority for us. We're actively looking for the root cause but for now you can get around this issue by using [yarn `resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) or [`npm-force-resolutions`](https://www.npmjs.com/package/npm-force-resolutions).

So far we've isolated it to `@babel/types`.

To force an older version of `@babel/types`, add the following to your `package.json` and then reinstall:

```js
{
  "name": "mysanityproject",
  "keywords": ["sanity"],
  "scripts": {
    // 👇👇👇 (only if you use npm) add this to your scripts
    "preinstall": "npx npm-force-resolutions"
    // 👆👆👆
  },
  "dependencies": {
    "@sanity/base": "^2.21.7",
    "@sanity/components": "^2.14.0",
    "@sanity/core": "^2.21.7"
  },
  // 👇👇👇 Add this regardless if you're using npm or yarn
  "resolutions": {
    "@babel/types": "7.15.x"
  }
  // 👆👆👆
}
```

- If using `npm`, `npm-force-resolutions` will run prior to your install and create a `package-lock.json` file that resolves the compatible versions.
- If using `yarn`, resolutions are built in and it should work after a `yarn` install

After the reinstall, the graphql deploy should work.

**Comment by jamiehenson** [comment]
Thanks for the workaround and the swift response @ricokahler - can confirm that works.

**Comment by ricokahler** [comment]
Hi there 👋

This should be fixed [v2.21.8](https://github.com/sanity-io/sanity/releases/tag/v2.21.8). No need for any of the above workarounds. You should be able to run `sanity upgrade` and be able to deploy as normal.

Thank you all for your patience!

**Comment by 007AMAN007** [comment]
Hi @ricokahler

I am facing above same issue. But now when I am trying to run ```sanity upgrade``` it's not updating my sanity cli version. And when I am manually updating version in my ```package.json``` & running ```npm install```. It's throwing following error.

```npm ERR! notarget No matching version found for @sanity/cli@^2.21.8```.

**Comment by mariuslundgard** [comment]
Hi @007AMAN007, if you’re using `@sanity/cli` as a global npm module, can you try again after doing `npm install -g @sanity/cli`?

**Comment by chalas-ch** [comment]
Fixed it for me, thanks a lot for the quick response!
