### ISSUE TITLE
Emojis disappear in block content editor with Firefox

### ISSUE THREAD

**Issue by selbekk** [sanity-io/sanity#2904]
**Describe the bug**

[breathes deeply]

When I'm using Firefox 93 (it works in Firefox 87) on MacOS Monterey, and use the built in OS emoji picker inside of a block content editor, emojis show up, then disappear whenever I tap space. Additionally, emphasis (italic) mode is selected.

Here's a Gif showing what's happening:

![An emoji is selected, then disappears](https://user-images.githubusercontent.com/1307267/139808165-9cc23eb8-8040-4e72-94c7-4c5d6ff4be71.gif)

**To Reproduce**

1. Install Firefox on your Mac
2. Create a basic Sanity project with a block content editor
3. Add an emoji by using the built-in emoji picker (cmd+ctrl+space)
4. Tap any other character
5. See the emoji disappear, and emphasis mode being turned on. With some characters, the cursor position might also change.

**Expected behavior**

I would love emojis to work as they should, even in Firefox.

**Which versions of Sanity are you using?**

```
❯ sanity versions
@sanity/cli                 2.21.4 (latest: 2.21.7)
@sanity/base                2.21.2 (latest: 2.21.7)
@sanity/code-input          2.21.2 (latest: 2.21.7)
@sanity/components          2.14.0 (up to date)
@sanity/core                2.21.0 (latest: 2.21.8)
@sanity/default-layout      2.21.2 (latest: 2.21.7)
@sanity/default-login       2.21.0 (latest: 2.21.7)
@sanity/desk-tool           2.21.2 (latest: 2.21.7)
@sanity/production-preview  2.15.0 (up to date)
@sanity/vision              2.21.2 (latest: 2.21.7)
```

**What operating system are you using?**

MacOS Monterey

**Which versions of Node.js / npm are you running?**

```
❯ npm -v
8.1.0
❯ node -v
v16.13.0
```

**Additional context**

It actually worked before I updated Firefox. That was Firefox 87 iirc. I have verified this on two different computers (both mac, but different MacOS versions), and in Chrome. You can also copy-paste in emojis from other sources without them disappearing.

I'm so sorry that I have to file this bug. Godspeed!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by selbekk** [comment]
Wuss!
