### ISSUE TITLE
Studio List Filters

### ISSUE THREAD

**Issue by bzmillerboy** [sanity-io/sanity#2967]
**Is your feature request related to a problem? Please describe.**
It's difficult for clients and end Studio users to explore data/documents and filter down to specific sets of that data. Example, if I have list of blog post and I want to quickly and randomly view all blog post published by "Knut Melvær" in the past 12 months, I can't easily do that without requesting a developer to create a custom list view.

**Describe the solution you'd like**
I would like filter capability in the list view that allow typical filter capability on the fields within my list. Material UI has a great pattern for this on their Data Tables. https://mui.com/components/data-grid/filtering/

**Describe alternatives you've considered**
At a minimum, basic filtering would be great.

**Additional context**
In my experience, this has been one of the biggest complaints from my clients moving over from other CMS (ex. Wordpress). To the client, filtering has become a basic foundational feature when working data and they've come to expect it. Therefore, when it's absent, they get the impression Sanity is an immature platform (because they don't see the power behind the scenes).

**Comment by vicbergquist** [comment]
Thank you for requesting!

**Comment by bzmillerboy** [comment]
It looks like this plugin by @ricokahler  has hopes for basic and advanced filters, look promising. https://github.com/ricokahler/sanity-super-pane/issues/2

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
