### ISSUE TITLE
UI Bugs: Tooltips & Read Only Fields

### ISSUE THREAD

**Issue by OllieJT** [sanity-io/sanity#2971]
**Describe the bug**

1. Error tooltips are not always visible due to overflow:hidden on parent elements.
2. "Read Only" fields are no longer disabled in the UI

**To Reproduce**

### ( 1 ) Tooltips

1. Open an object type as a dialog
2. Allow a field within the dialog to be invalid
3. Attempt to view the error message

![](https://i.imgur.com/NIcq3eg.png)

Example: use this to add a link to some text. Enter an invalid url
```js
export default {
	title: "Rich Text",
	name: "richtext",
	type: "array",
	of: [
		{
			title: "Block",
			name: "block",
			type: "block",
			styles: [{ title: "Normal", value: "normal" }],
			lists: [],
			marks: {
				decorators: [],
				annotations: [
					{
						title: "Links",
						name: "link",
						description: "Link to another website",
						type: "object",
						fields: [
							{
								title: "URL",
								name: "url",
								type: "url",
								validation: (Rule) => Rule.required(),
								codegen: { required: true },
							},
						],
					},
				],
			},
		},
	],
	options: {
		editModal: "dialog",
	},
};

```

### ( 2 ) Read Only
1. Set a text field to readOnly: true
2. View the field in the frontend

**Additional context**
```json
{
    "@sanity/base": "^2.22.3",
    "@sanity/core": "^2.22.3",
    "@sanity/default-layout": "^2.22.3",
    "@sanity/default-login": "^2.22.3",
    "@sanity/desk-tool": "^2.22.3"
}
```

**Comment by vicbergquist** [comment]
Can you please share which browser(s) you are seeing this in?

**Comment by khendrikse** [comment]
I'm also getting the error message problem. It's happening in Chrome `96.0.4664.93` for me.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
