### ISSUE TITLE
Arrays of files no longer support direct / drag&drop upload 

### ISSUE THREAD

**Issue by baybars1223** [sanity-io/sanity#2974]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**
In the past (tested with v1.150.3) you could drag&drop multiple files (files, not images) into a file array input. Now you get a "no known conversion from file types to array" error message.  
As far as I can tell, `formBuilderConfig?.files?.directUploads` in `@sanity/form-builder/src/sanity/inputs/SanityArrayInput.tsx` evaluates to false by default, rather than true.

**To Reproduce**

1. Create a document with an array field of type 'file'
2. Attempt to drag&drop files into array input

**Expected behavior**
Be able to drag and drop multiple files into array file inputs

**Screenshots**

**Which versions of Sanity are you using?**
Tested with `v1.150.3` (works as expected), 
`v2.22.3` (fails)
```
@sanity/cli             2.19.0 (latest: 2.22.3)
@sanity/base            2.22.3 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.22.3 (up to date)
@sanity/dashboard       2.22.3 (up to date)
@sanity/default-layout  2.22.4 (up to date)
@sanity/default-login   2.22.3 (up to date)
@sanity/desk-tool       2.22.3 (up to date)
@sanity/vision          2.22.3 (up to date)
```

**Comment by evenwestvang** [comment]
Thanks for letting us know!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
