### ISSUE TITLE
Structure builder: menuItems on documentTypeList no longer works like it used to

### ISSUE THREAD

**Issue by jfulse** [sanity-io/sanity#2977]
**Describe the bug**

We used to have a create-button for document type lists with our own icon, This no longer works after upgrading `desk-tool` from 2.22.2 to 2.22.3; no button appears

**To Reproduce**

Use the following in the desk structure:

```
const TestIcon = () => <div>test icon<div>;

S.documentTypeList(documentType).menuItems([
    S.menuItem()
      .title("test")
      .intent({ type: "create", params: { type: documentType } })
      .showAsAction(true)
      .icon(TestIcon),
  ]);
```

Then no create document button appears. 

Some digging in the code reveals that the constructor of `MenuItemBuilder` is called with an empty `spec`, but I haven't gotten any further than that.

**Expected behavior**

The create document button should appear with the specified icon

**Which versions of Sanity are you using?**

@sanity/cli             2.19.1 (latest: 2.22.3)
@sanity/base            2.22.3 (up to date)
@sanity/cli             2.22.3 (up to date)
@sanity/core            2.22.3 (up to date)
@sanity/default-layout  2.22.4 (up to date)
@sanity/default-login   2.22.3 (up to date)
@sanity/desk-tool       2.22.3 (up to date)
@sanity/react-hooks     2.22.3 (up to date)
@sanity/vision          2.22.3 (up to date)

**What operating system are you using?**

macOS Big Sur

**Which versions of Node.js / npm are you running?**

8.1.3
v16.11.0

**Security issue?**

No

**Comment by fabien** [comment]
We were using a part override to achieve the same thing, unfortunately this has also stopped working: https://github.com/sanity-io/sanity/issues/2932

**Comment by fabien** [comment]
I also noticed a significant change in v.2.23.0 where having a single menu item with `.showAsAction(true)` now creates a dropdown with a single option, ignoring the custom menu item altogether.

In my case, this makes a considerable difference, because this workaround no longer works:

https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1636981159134900?thread_ts=1634810149.029000&cid=C9Z7RC3V1

```javascript
 S.menuItem()
      .title('Create')
      .icon(ComposeIcon)
      .intent({
        type: 'create',
        params: { type, id: `${prefix}.${uuid()}` },
      })
      .showAsAction(true),
```

This displays as:

![image](https://user-images.githubusercontent.com/2749/145672984-e0a7e112-c988-44c6-b1aa-ebae41c6836b.png)

![image](https://user-images.githubusercontent.com/2749/145672995-3f48567e-dfc0-45e0-98d2-9746fe4bcf24.png)

**Comment by fabien** [comment]
It appears that the bug originates from this changeset: https://github.com/sanity-io/sanity/pull/2939 - which affects some of the Structure builder code here: https://github.com/sanity-io/sanity/tree/next/packages/%40sanity/structure/src

@ricokahler any idea what changed that might affect this?

**Comment by ricokahler** [comment]
> @ricokahler any idea what changed that might affect this?

Ah yes. Thanks for the mention @fabien 

This change was related to #2939 and it includes new a component for pane header actions that aggregates all create intents and all initial value template items into one create button. This was done because this create button is now roles aware and therefore will disable options if your role can't create that option (see GIF below).

@jfulse does the create option still show up within the main create button? I understand this breaks your custom icon but I'm wondering if there are any other issues I'm missing

![demo of roles aware create button](https://user-images.githubusercontent.com/10551026/145843380-35025557-3045-409f-b7b4-bbfc027a84a0.gif)

---

@fabien and @jfulse, if you change the intent from `'create'` to `'edit'` you should get similar behavior to the old functionality.

`'edit'` intents to a document that doesn't exist yet will still end up navigating to that non-existent document and any edits will end up creating it.

```js
import {uuid} from '@sanity/uuid'

S.menuItem()
  .intent({
    type: 'edit',
    params: {type: 'author', id: uuid()},
  }),
```

Anyway, I'll take a look at this and see if what we can do. Thanks for reporting!

**Comment by fabien** [comment]
> Ah, I missed this part. This should definitely hide if there are no create options available.

I just double checked, after I applied your fix (using `edit`, which works, thanks!) and the default create button is always there.

![image](https://user-images.githubusercontent.com/2749/145852385-7795d99e-b571-494a-8fc8-c14e9c1b8017.png)

**Comment by ricokahler** [comment]
I just double checked the code and that behavior you're seeing is a bug: https://github.com/sanity-io/sanity/pull/3007

We'll probably have this fix out sometime tomorrow

**Comment by ricokahler** [comment]
Hi all, we just released [v2.23.1](https://github.com/sanity-io/sanity/releases/tag/v2.23.1) which includes #3007.

This should fix the bug that caused the create-related intents not to show up in the pane headers. However, this current behavior may still not be ideal for certain scenarios so I'll keep this open for those cases.

For now, I'll explain how it works at the current state (v2.23.1) along with some context:

> Disclaimer: firehose/wall-of-text incoming 😅 , feel free to ask for clarification if needed.

- This change was introduced to address some other inconsistencies with permissions (see #2939). Previously, the create-related menu items were not fully roles-aware and could incorrectly say a user had the ability to could create document that they couldn't. [(see here for roles docs)](https://www.sanity.io/docs/roles)
- #2939 introduced a shared component `PaneHeaderActions` that is now used for the list panes, document list panes, and custom user panes (the only pane it is not being utilized in, is the document pane). This new component [accepts](https://github.com/sanity-io/sanity/blob/3e1066159c73ffd9020200626a1e48860dc2d0ef/packages/%40sanity/desk-tool/src/components/paneHeaderActions/PaneHeaderActions.tsx#L32-L33) an array of `initialValueTemplateItems` and an array of `menuItems`. Both are provided by the [structure](https://www.sanity.io/docs/structure-builder-reference#initialValueTemplates-1037f655dd41) [builder](https://www.sanity.io/docs/structure-builder-reference#menuItems-a81443fad78c) and both provide affordances to create documents
- In order to make both roles-aware, the output of each was combined into a [singular create button](https://github.com/sanity-io/sanity/blob/3e1066159c73ffd9020200626a1e48860dc2d0ef/packages/%40sanity/desk-tool/src/components/paneHeaderActions/PaneHeaderCreateButton.tsx#L39) that will open a menu if more than one option for creating documents is found.
- This means that any `S.menuItem()` with a create intent (e.g. `S.menuItem().intent({type: 'create', params: {type: 'author'}})`) would be moved into this singular create button regardless if you had `showAsAction(true)`

Again, this behavior may not be ideal so I'll look into more alternatives that maintain some of the previous behavior more.

@jfulse @fabien, can you provide more details on your use case for separate buttons? this would greatly would help clarify and prioritize internally

**Comment by jfulse** [comment]
v2.23.1 has fixed the issue for us, thanks a lot!

**Comment by fabien** [comment]
@heggemsnes try adding `.initialValueTemplates([])`:

```
 S.listItem()
          .title("Kunder")
          .icon(User)
          .child(
            S.documentTypeList("customer")
              .initialValueTemplates([])
              .menuItems([
                S.menuItem()
                  .title("Ny kunde")
                  .icon(ComposeIcon)
                  .intent({
                    type: "edit",
                    params: { type: "customer", id: `user.${uuid()}` },
                  })
                  .showAsAction(true),
              ])
              .title("Kunder")
              .child((documentId) =>
                S.document().documentId(documentId).schemaType("customer")
              )
          ),
      ])
```

**Comment by geball** [comment]
From what I can see the original question and follow ups have been answered so I'll close this issue, but please let me know if not and we can open it again.

**Comment by trompx** [comment]
Hello,
I have a very similar issue that seems to be linked to this one: https://github.com/sanity-io/sanity/issues/3272
Also here is the [slack thread](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1651579661409189) with some additional info.
