### ISSUE TITLE
Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by tairosonloa** [sanity-io/sanity#2990]
**Describe the bug**

I just installed Sanity. I logged with GitHub in the CLI. When I do `sanity init` and then `sanity start` and goes to `localhost:3333`, if I try to enter with GitHub the page just refreshes and in DevTools console I can see the following error:

```
Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
```

Tried with node 14 LTS and node 16 LTS.  Tried both a template ([nextjs template](https://www.sanity.io/create?template=sanity-io%2Fsanity-template-nextjs-blog-comments)) and doing `sanity init` on an existing project.

**To Reproduce**

1. Install sanity globally with `npm install -g @sanity/cli`
2. On an existing project, do `sanity init` or just [use a template](https://www.sanity.io/get-started)
3. On studio folder, do `sanity start`
4. Go to `localhost:3333` and try to log in using GitHub.
5. Page refreshes and error is print in DevTools console.

**Expected behavior**

Just log in into studio.

**Which versions of Sanity are you using?**

@sanity/cli  2.22.3 (up to date)

**What operating system are you using?**

Ubuntu 20.04 under WSL2 on Windows 10.

**Which versions of Node.js / npm are you running?**

Tried two different versions:

- npm 8.1.0 with node v16.13.0
- npm 6.14.15 with node v14.18.2

**Comment by armandsalle** [comment]
Hey! This bug was cause by my ad blocker. I turn it off on localhost:3333 and it works now

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
