### ISSUE TITLE
Export ReferringDocumentsList and enhanceWithReferringDocuments

### ISSUE THREAD

**Issue by devinhalladay** [sanity-io/sanity#2992]
**Is your feature request related to a problem? Please describe.**
I am using [WithReferringDocuments](https://github.com/Delta-CI/sanity/blob/next/packages/@sanity/base/src/components/WithReferringDocuments.js) to show a list of referring documents or "backlinks" for my editors.

I'd like to be able to use the following components via an import of a component or a Sanity `part`:
- [enhanceWithReferringDocuments](https://github.com/sanity-io/sanity/blob/next/packages/@sanity/desk-tool/src/components/enhanceWithReferringDocuments.tsx)
- [ReferringDocumentsList](https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/desk-tool/src/components/ReferringDocumentsList.tsx)

A [quick search on GitHub](https://github.com/search?q=ReferringDocumentsList&type=code) shows that there are some other developers — [including Sanity itself](https://github.com/sanity-io/community-studio/blob/f0319298cf7318c3574651e858cdd8bb2db15bc4/schemas/components/referringDocuments/ReferringDocumentsList.js) — who needed these components, so they just copy/pasted the source code to their projects. Seems like this would be a valuable tool to have in the arsenal provided by Sanity packages.

**Describe the solution you'd like**
Export the components mentioned above through the Sanity parts system.

**Describe alternatives you've considered**
- Allow the components to be imported normally from `@sanity/desk-tool` without using the parts system
- Copy/paste the components into my own codebase

---

For the time being, I have just written my own components. While we wait for discussion to unfold here, if anyone needs these features, I've put together [a short recipe](https://garden3d.notion.site/List-Referring-Documents-Backlinks-in-Sanity-da442d8764414c2d9ded4a9f07735ac9) for rolling your own.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
