### ISSUE TITLE
Try another port when default is already in use

### ISSUE THREAD

**Issue by sixclones** [sanity-io/sanity#3013]
Hi,

I'd like to suggest a small feature for the CLI.
I'm generally working on multiple projects at once and it's a bit frustrating to not be able to run two sanity servers at the same time.
To be clear, it's currently possible but by manually changing the port of the dev server.

A solution could be to automatically try the next port by incrementing the given port until it succeed or it goes more than 10 tries.

Example from [Next.js](https://github.com/vercel/next.js/blob/canary/packages/next/server/lib/start-server.ts#L21-L35)
```js
server.on('error', (err: NodeJS.ErrnoException) => {
  if (
    port &&
    opts.allowRetry &&
    err.code === 'EADDRINUSE' &&
    retryCount < 10
  ) {
    warn(`Port ${port} is in use, trying ${port + 1} instead.`)
    port += 1
    retryCount += 1
    server.listen(port, opts.hostname)
  } else {
    reject(err)
  }
})
```

Thanks!

**Comment by rexxars** [comment]
We could do this, but for the studio to work you have to allow the CORS-origin access to your project - which means adding an additional one per port. We could of course prompt you to add one if we choose a different port, but it might result in a number of unused CORS origins over time.

I'll mark it down as a feature request and we'll give it some more thought - thanks for filing!

**Comment by sixclones** [comment]
Oh yeah, I wasn't thinking about the CORS-origin access.
I share your point about leaving unused CORS origins.
This was simpler in my mind, having to care about CORS add a new layer of complexity about this feature.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
