### ISSUE TITLE
Babel plugin for styled-components

### ISSUE THREAD

**Issue by jfulse** [sanity-io/sanity#3017]
**Is your feature request related to a problem? Please describe.**
Classnames from styled-components are mangled, making it difficult to use React profiling tools and similar in the browser console.

**Describe the solution you'd like**
Adding the following babel plugin improves classnames: https://styled-components.com/docs/tooling

**Describe alternatives you've considered**
We've managed to add the plugin to our own custom components in the Studio, but it doesn't affect the built in Studio components.

**Comment by ricokahler** [comment]
Ah yes we've been wanting to do the same. It needs to go in both the studio (this repo) and sanity UI ([a different repo](https://github.com/sanity-io/design)). We'll keep you update 😄

**Comment by jfulse** [comment]
Great, thanks!

**Comment by winsvold** [comment]
This would be great 🙏 Had to write this weird selector to do some styling, and it keeps breaking when upgrading the studio (not to add yellow borders, but to hide, but applied yellow borders here for illustration)

```
 #sanity > div:first-child > div:first-child > div:first-child {
    > div:first-child {
      > div:last-child > div:not(:last-child) {
        border: yellow dashed 1px;
      }
      > div:first-child {
        > div:nth-child(2), > div:nth-child(3) {
          border: yellow dashed 1px;
        }
        > div:nth-child(4) > div > div {
           > div > div:not(:nth-child(2)) {
            border: yellow dashed 1px;
          }
        }
      }
    }
  }
  ```
  
![image](https://user-images.githubusercontent.com/29202094/155984825-c72bb7f3-711d-4d22-8d5b-1132795655d2.png)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
