### ISSUE TITLE
Expose the current user's first name in userStore.me

### ISSUE THREAD

**Issue by jfulse** [sanity-io/sanity#3023]
**Is your feature request related to a problem? Please describe.**
It would be nice to know the current user's first name in custom components etc in the studio

**Describe the solution you'd like**
`userStore.me` could expose the first name; at the moment it returns a `CurrentUser` type which doesn't

**Describe alternatives you've considered**
I'm not aware of other means of retrieving the user's first name

**Additional context**
Imported from `import userStore from "part:@sanity/base/user";`

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
