### ISSUE TITLE
Error while run "npm run graphql-deploy"

### ISSUE THREAD

**Issue by 007AMAN007** [sanity-io/sanity#3026]
Hi

I am facing following error while run ```npm run graphql-deploy```.

```lerna ERR! npm run graphql-deploy stderr:
- Checking for deployed API
✔ Checking for deployed API
- Generating GraphQL schema
✖ Generating GraphQL schema

Error: Cannot find module 'react'
```

I noticed that, this error is occurs only when I am using some "npm package" inside schema object for preview, like when I am using "react-share" or "Material UI".

Please let me know what I need to do.

Thanks

**Comment by ricokahler** [comment]
hi @007AMAN007 

could you provide more details about your setup? It'd be best if you could provide a minimal reproduction repo but if you're pressed for time more details and a package.json will help us get further.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
