### ISSUE TITLE
Dependabot alert - Immer

### ISSUE THREAD

**Issue by HarryAdney** [sanity-io/sanity#3028]
Dependabot cannot update immer to a non-vulnerable version
The latest possible version that can be installed is 5.3.6 because of the following conflicting dependency:

@sanity/desk-tool@2.23.1 requires immer@^5.0.0 via a transitive dependency on slate@0.58.4
The earliest fixed version is 9.0.6.

Details
CVE-2021-3757
high severity
Vulnerable versions: < 9.0.6
Patched version: 9.0.6
immer is vulnerable to Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution')

CVE-2021-23436
critical severity
Vulnerable versions: < 9.0.6
Patched version: 9.0.6
This affects the package immer before 9.0.6. A type confusion vulnerability can lead to a bypass of CVE-2020-28477 when the user-provided keys used in the path parameter are arrays. In particular, this bypass is possible because the condition (p === "proto" || p === "constructor") in applyPatches_ returns false if p is ['proto'] (or ['constructor']). The === operator (strict equality operator) returns false if the operands have different type.

CVE-2020-28477
high severity
Vulnerable versions: < 8.0.1
Patched version: 8.0.1
Overview
Affected versions of immer are vulnerable to Prototype Pollution.

**Comment by ricokahler** [comment]
Hi @HarryAdney 👋

We have noticed those CVEs and we are looking to remove those notices. However, it’s important to note that those CVEs should not affect browser environments which is where the affected code runs and does not pose any vulnerabilities to you or your Studio instance users.

The Studio has a very similar set up as to create-react-app so I’d recommend [npm broken: by design by Dan Abramov](https://overreacted.io/npm-audit-broken-by-design/) for more info.

That being said we are working to remove those notices. We rely on a fork of slate and we’re currently working on a sync from upstream which includes using a patched version of immer. This effort has not been easy (see #3014). We expect it to land sometime soon in the new year.
