### ISSUE TITLE
Custom validation should receive currentUser

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#3031]
**Is your feature request related to a problem? Please describe.**

There's an inconsistency when it comes to implementing a custom validation function compared to conditional `hidden` and `readOnly` functions. The custom validation does not receive the `currentUser` in the `context` that is passed into it. 

**Describe the solution you'd like**

Make the `context` argument as consistent as possible.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
