### ISSUE TITLE
TagInput with hidden cursor and first character

### ISSUE THREAD

**Issue by mkv27** [sanity-io/sanity#3038]
**Describe the bug**

When you start typing in an array of strings, the first character and the cursor is hidden in Safari. No cursor in Chrome
https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/form-builder/src/components/tagInput/tagInput.tsx

**To Reproduce**

1. Add this type in a document
```js
{
  name: 'tags',
  title: 'Tags',
  type: 'array',
  of: [{ type: 'string' }],
  options: {
    layout: 'tags',
  },
}
```
2. Add "tags"

**Expected behavior**

After click on the input the cursor shouldn't be hidden

**Screenshots**
https://user-images.githubusercontent.com/8582368/147814809-1af12d26-f1a8-4fdc-ba9e-750cbf9af782.mov

**Which versions of Sanity are you using?**

```sh
@sanity/cli             2.23.2 (up to date)
@sanity/base            2.23.2 (up to date)
@sanity/core            2.23.2 (up to date)
@sanity/default-layout  2.23.2 (up to date)
@sanity/default-login   2.23.2 (up to date)
@sanity/desk-tool       2.23.2 (up to date)
@sanity/vision          2.23.2 (up to date)
```

Safari Versión 15.2

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
