### ISSUE TITLE
Option to disallow editing referenced document from reference field

### ISSUE THREAD

**Issue by jfulse** [sanity-io/sanity#3044]
**Is your feature request related to a problem? Please describe.**
In our case, users that select referenced documents do not necessarily have permissions to edit the same.

**Describe the solution you'd like**
An option, e.g. `disableEdit`, that disables editing the referenced document similarly to how [`disableCreate` ](https://www.sanity.io/docs/reference-type#disableNew-0ab01dd4f50c) disables creation

**Describe alternatives you've considered**
Our only solution at the moment is CSS overwrite hacks

**Comment by bjoerge** [comment]
Just to understand better: when an editor opens a referenced document they don't have write access to, they see it in read-only mode, right?

Is the use case that you don't want editors to be able to open the referenced document at all unless they have write access to it?

**Comment by jfulse** [comment]
Hello! Thanks for you reply.

It's a good point that they cannot write unless they have access. The issue text is a bit unclear about our main goal, which is to make the Studio as simple as possible (many of our users will be very occasional and not power users). Therefore the point is really about UX rather than access. Maybe a better name for the option would be `disableOpen`?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
