### ISSUE TITLE
defined() rule in documentTypeList filter returns all document types

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#3073]
When passing a query to `filter()` of `documentTypeList` that includes any instance of `defined` it will return all documents matching that query instead of filtering the existing list. For example:
```
documentTypeList('request').filter('approved == true')
```
equals `*[_type == 'request' && approved == true]`, but:

```
documentTypeList('request').filter('!defined(approved)')
```
somehow returns the results of `*[!defined(approved)]` forcing to reiterate the _type rule as such:
```
documentTypeList('request').filter('_type == 'request' && !defined(approved)')
```

**Which versions of Sanity are you using?**
@sanity/cli             **2.23.0**
@sanity/base            **2.23.0**
@sanity/core            **2.23.0**
@sanity/default-layout  **2.23.0**
@sanity/default-login   **2.23.0**
@sanity/desk-tool       **2.23.0**
@sanity/vision          **2.23.0** 

**What operating system are you using?**
MacOS **12.1**

**Which versions of Node.js / npm are you running?**
Node **17.3.1.**
Npm **8.3.0.**

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
