### ISSUE TITLE
Improve readability of objects in JSON inspector

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#3076]
Currently the document JSON inspector places the arrow for expandable properties on the same indentation level as regular properties above/below. The result is that all expandable properties appear to be indented one level more than they actually are.

https://user-images.githubusercontent.com/6848068/149850152-00a21b19-fd9a-4394-934e-3271312c7248.mov

**Which versions of Sanity are you using?**
@sanity/cli 2.23.0
@sanity/base 2.23.0
@sanity/core 2.23.0
@sanity/default-layout 2.23.0
@sanity/default-login 2.23.0
@sanity/desk-tool 2.23.0
@sanity/vision 2.23.0

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
