### ISSUE TITLE
Improve functionality and documentation of placeholder text

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#3079]
It goes without saying that placeholder text is an essential feature for guidance and accessibility of form inputs. As far as I know, all primitive input fields in the studio support the `placeholder` property, although it's not documented. Placeholders are obviously not meant to be a replacement for field descriptions and vice-versa but I believe it's a very important aspect of the studio UX in general and leaving it undocumented is a very strange omission overall. 

In addition to better documentation, the usability of the `placeholder` property could be increased by allowing its value to change depending on the current document state like conditional values – a conditional placeholder text of sorts. An example use case could be a `price` number field used alongside a `currency` text field where the input placeholder for `price` could change from `1 000 NOK` to `1,000 USD` according to the currency value.

**Comment by jimmi-joensson** [comment]
Yes the placeholder property is missing in the documentation and should definitely be added.
https://www.sanity.io/docs/string-type#properties

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
