### ISSUE TITLE
Add support for a (visual) slug prefix

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#3080]
**Is your feature request related to a problem? Please describe.**
The slug input field could support an additional string that can be prepended (only visually, not to the actual value) to the input field. This would clarify its practical use more clearly for less experienced editors working in the studio. 
 
![slug](https://user-images.githubusercontent.com/6848068/149944475-a6a746aa-e46c-47df-b787-53a0c464eb01.png)

**Describe alternatives you've considered**
This is a very trivial challenge to solve with custom input components – but portability always becomes a problem with subsequent studio updates.

**Comment by toddpadwick** [comment]
I found this plugin which does this https://www.sanity.io/plugins/better-slug

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
