### ISSUE TITLE
Adding "path" to hidden field's context (ConditionalPropertyCallbackContext)

### ISSUE THREAD

**Issue by tremppu** [sanity-io/sanity#3125]
I have ran into issue where I can't check a specific value down the tree when trying to hide a field (parent is not enough, value I am looking for is something like parent's parent's other child). I am able to handle validation with custom validation context's "path" property (used with document's value) and would hope that same could be done with hidden / conditional. 🤞

**Describe the solution you'd like:**
Adding "path" similar to "[ValidationContext's path](https://github.com/sanity-io/sanity/blob/35b5b594606a50fa2c1d9635317825bca49836e5/packages/%40sanity/types/src/validation/types.ts#L210)" to "[ConditionalPropertyCallbackContext](https://github.com/sanity-io/sanity/blob/9e5a11cb084b22b074ed0f204f9cc640b489529d/packages/%40sanity/types/src/schema/types.ts#L36)"

Thanks!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
