### ISSUE TITLE
Studio portable text field: Occasionally can't update the state of annotations

### ISSUE THREAD

**Issue by d4rekanguok** [sanity-io/sanity#3136]
**Describe the bug**

Occasionally the studio 'undo' the change editors make in portable text field, in the clip below you can see that it's in an annotation but I have occasionally see it happens with text as well.

**To Reproduce**

1. Add an annotation of object type
2. Try changing one of its field value
4. After autosave, the value is reverted back to previous state

**Expected behavior**

Autosave should not revert the latest change

**Screenshots**
In this screencap, you can see that I tried to change the value from 'right' to 'left', but after every save, the value is reverted back to 'right'

![Screen Recording 2022-02-05 at 9 40 51 AM](https://user-images.githubusercontent.com/3383539/152621546-4534840f-2d8b-40c9-b567-92132c14061b.gif)

**Which versions of Sanity are you using?**

```
@sanity/cli             2.23.2 (latest: 2.26.0)
@sanity/base            2.26.0 (up to date)
@sanity/core            2.26.0 (up to date)
@sanity/default-layout  2.26.0 (up to date)
@sanity/default-login   2.26.0 (up to date)
@sanity/desk-tool       2.26.0 (up to date)
@sanity/vision          2.26.0 (up to date)
```

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

```
npm 8.1.2
node v16.13.1
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
