### ISSUE TITLE
Cannot use `documentTypeList` with `child` without `canHandleIntent`

### ISSUE THREAD

**Issue by Brydom** [sanity-io/sanity#3140]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

`documentTypeList` cannot have a `child` without `canHandleIntent`

**To Reproduce**

1. Set up a `documentTypeList` similar to the example code below
2. Remove `canHandleIntent` and see `Pane returned nothing` error

```js
import S from "@sanity/desk-tool/structure-builder";
import { GoListUnordered } from "react-icons/go";

export default (site = {prefix: "1234"}) =>
  S.listItem()
    .title("Pages")
    .icon(GoListUnordered)
    .child(
      S.documentTypeList("page")
        .title("Pages")
        .filter(`_type == "page" && site == "${site.prefix}"`)
        .child((documentId) =>
          S.documentWithInitialValueTemplate("page", {
            site: site.prefix,
          }).documentId(documentId)
        )
        .canHandleIntent(
          (intent, { type }) =>
            ["create", "edit"].includes(intent) && type === "page"
        )
    );

```

**Expected behavior**

If `canHandleIntent` is required, it should be documented as such.

**Which versions of Sanity are you using?**

```
@sanity/cli                 2.25.0 (latest: 2.26.0)
@sanity/base                2.25.0 (latest: 2.26.0)
@sanity/cli                 2.25.0 (latest: 2.26.0)
@sanity/core                2.25.0 (latest: 2.26.0)
@sanity/dashboard           2.25.0 (latest: 2.26.0)
@sanity/default-layout      2.25.0 (latest: 2.26.0)
@sanity/default-login       2.24.1 (latest: 2.26.0)
@sanity/desk-tool           2.25.0 (latest: 2.26.0)
@sanity/production-preview  2.15.0 (up to date)
@sanity/vision              2.25.0 (latest: 2.26.0)
```

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

```
8.3.0
v16.13.1
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
