### ISSUE TITLE
clientless patches fail

### ISSUE THREAD

**Issue by bagrounds** [sanity-io/sanity#3141]
**Describe the bug**

From the documentation on the [npm package page](https://www.npmjs.com/package/@sanity/client):
> Clientless patches & transactions
Transactions and patches can also be built outside the scope of a client:
```ts
const sanityClient = require('@sanity/client')
const client = sanityClient({
  projectId: 'your-project-id',
  dataset: 'bikeshop',
})

// Patches:
const patch = new sanityClient.Patch('<documentId>')
client.mutate(patch.inc({count: 1}).unset(['visits']))
```

But this results in an HTTP 400, with a complaint about unknown keys.

After investigating a bit, it appears that when `patch.commit()` is called, the patch is wrapped in an object with a patch property before passing it to mutate, but the equivalent does not happen when passing a patch object to the mutate method externally.

Because the error message included the JSON body sent by the client, I was able to verify that it also fails when curling the REST API directly, but it succeeds if we wrap the patch operations in the `{ patch: ... }` object.

As a workaround, I'm able to pass the client into the `Patch` constructor and call commit after building up the appropriate operations.

Should be a very easy fix.

**To Reproduce**

Construct a patch object and pass it to `client.mutate`

**Expected behavior**

the patch succceeds

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
