### ISSUE TITLE
Failed to update webhook. URL too long?

### ISSUE THREAD

**Issue by kossowski** [sanity-io/sanity#3151]
**Describe the bug**

Trying to add a webhook with 342 symbols under https://www.sanity.io/manage/personal/project/xxx/api/webhooks/.

Everytime I tried to save I got this output:

> Failed to update webhook
> An internal server error occurred

When I reduced the amount to 255 symbols I was able to save successfully.

I added the same hook, with the same length, on GitHub Webhook without any problems. Are there any reasons why sanity has a limitation?

Unfortunately I have no chance to shorten the Webhook URL, because it's auto-generated.

**To Reproduce**

1. Go to https://www.sanity.io/manage/personal/project/xxx/api/webhooks/
2. Click on 'Create Webhook'
3. Add a 'URL' with at least 256 symbols
4. Scroll down to save

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
