### ISSUE TITLE
HiddenOption & HiddenOptionCallbackContext missing from @sanity/types package

### ISSUE THREAD

**Issue by qauff** [sanity-io/sanity#3153]
Hi there,

When using any version of `@sanity/types` that is greater than `2.22.3`, it seems these two types are missing from the package:

- `HiddenOption`
- `HiddenOptionCallbackContext`

Did these types get renamed or are there an equivalent I should be using now?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
