### ISSUE TITLE
Information on marks seems to disappear when importing HTML into nested structures

### ISSUE THREAD

**Issue by eedahl** [sanity-io/sanity#3163]
**Describe the bug**

Information on marks seems to disappear when importing HTML into nested structures.

**To Reproduce**

If you have a document with portable text fields which allow container blocks which themselves contain (the same) portable text type, and attempt to import different kinds of links, e.g. via
```js
export const link = (url, children) => {
  const key = randomKey(12);
  return ({
    _type: "__annotation",
    markDef: {
      _type: "link",
      _key: key,
      href: url
    },
    children: children
  });
}
```
(with children = `next(el?.childNodes)`) information on what kind of mark it is gets lost leaving errors like:
`Block with _key '7b4aa8751471' contains marks (46c27bfe4b96) not supported by the current content model.`

**Expected behavior**

Text imported from HTML as having an annotation should still have that annotation post import

**Screenshots**

**Which versions of Sanity are you using?**

@sanity/cli                 2.27.0 (up to date)
@sanity/base                2.27.1 (up to date)
@sanity/core                2.27.0 (up to date)
@sanity/default-layout      2.27.1 (up to date)
@sanity/default-login       2.27.0 (up to date)
@sanity/desk-tool           2.27.1 (up to date)
@sanity/production-preview  2.15.0 (up to date)
@sanity/schema              2.27.0 (up to date)
@sanity/vision              2.27.1 (up to date)

**What operating system are you using?**

Ubuntu Linux

**Which versions of Node.js / npm are you running?**

8.3.1
v16.14.0

**Additional context**

Import of links seems to work fine in the "outer" layer of portable text.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
