### ISSUE TITLE
Debounce the input so that it doesn't make too many network request

### ISSUE THREAD

**Issue by naptestdev** [sanity-io/sanity#3165]
**Is your feature request related to a problem? Please describe.**
I see many network request made by sanity every time I type.

**Describe the solution you'd like**
Debounce the input with about 400ms time so that the network isn't flooded when I type.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
