### ISSUE TITLE
Console error when reviewing changes

### ISSUE THREAD

**Issue by straube** [sanity-io/sanity#3188]
**Describe the bug**

An error is showing in the browser console while reviewing changes of a document in the Studio.

```
Diff component resolver is not a function:  undefined 
```

I initially spotted the issue while working on a document that had a custom input. Then I thought it could be related to it. However, I noticed it was happening on every document.

**To Reproduce**

1. Open the **Review changes** view from any document's context menu -- three dots on the upper right.
2. Check the browser console, an error is shown in the console.

**Expected behavior**

No errors should appear in the console.

**Screenshots**

I added a breakpoint to where the error is triggered and took the following screenshot to provide some context.

<img width="656" alt="Screen Shot 2022-03-14 at 15 35 45" src="https://user-images.githubusercontent.com/958870/158239884-619db2ee-9e4e-4e22-bddc-8887503b3082.png">

**Which versions of Sanity are you using?**

```
@sanity/cli                 2.28.0 (up to date)
@sanity/base                2.28.2 (up to date)
@sanity/cli                 2.28.0 (up to date)
@sanity/code-input          2.28.2 (up to date)
@sanity/color-input         2.28.2 (up to date)
@sanity/core                2.28.1 (up to date)
@sanity/dashboard           2.28.2 (up to date)
@sanity/default-layout      2.28.2 (up to date)
@sanity/default-login       2.28.2 (up to date)
@sanity/desk-tool           2.28.2 (up to date)
@sanity/production-preview  2.15.0 (up to date)
@sanity/vision              2.28.2 (up to date)
```

**What operating system are you using?**

macOS Monterey 12.2.1 (21D62)

**Which versions of Node.js / npm are you running?**

8.3.1
v16.14.0

**Additional context**

This is where the error is thrown: https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/field/src/diff/resolve/resolveDiffComponent.ts#L45

**Comment by ansmlc** [comment]
Same here.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
