### ISSUE TITLE
Add `hidden` property support to `<FormBuilderInput>`

### ISSUE THREAD

**Issue by danmichaelo** [sanity-io/sanity#3203]
**Is your feature request related to a problem? Please describe.**

We need to support the `hidden` property when creating our own custom input components. 

**Describe the solution you'd like**

[`FormBuilderInput`](https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/form-builder/src/FormBuilderInput.tsx) already supports the `readOnly` conditional property, so it seems logical to me that it should also support the `hidden` property.

```
<FormBuilderInput
  ...
  readOnly={field.type.readOnly} // This works
  hidden={field.type.hidden} // Would be nice if this also worked
/>
```

**Describe alternatives you've considered**

Our workaround is to wrap `<FormBuilderInput>` with [`<ConditionalHiddenField>`](https://raw.githubusercontent.com/sanity-io/sanity/0b25aee6ff10497c9145a2114a9c9fd08f0873ef/packages/%40sanity/form-builder/src/inputs/common/ConditionalHiddenField.tsx) (which isn't currently exported, so we also had to copy-paste it into our project):

```
<ConditionalHiddenField parent={parent} value={value} hidden={field.hidden}>
  <FormBuilderInput
    ...
    readOnly={field.type.readOnly}
  />
</ConditionalHiddenField>
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
