### ISSUE TITLE
Mocking imports from parts leads to folder with colon in the name

### ISSUE THREAD

**Issue by jfulse** [sanity-io/sanity#3207]
**Describe the bug**
When mocking `import schema from "part:@sanity/base/schema"` for testing, we end up with folders with colon in the filename, which is an issue on Windows. Although it's probably most common to develop in a virtual unix environment etc, it is a future potential issue. 

**To Reproduce**

We use manual mocks in [this style](https://jestjs.io/docs/manual-mocks#mocking-node-modules); I think it's not an option to use [mock functions](https://jestjs.io/docs/mock-functions#mocking-modules) since that requires importing the mocked module in the test file.

**Expected behavior**

It should be possible to mock imports from parts in a way compliant with Windows file structure.

**Which versions of Sanity are you using?**

@sanity/cli             2.19.1 (latest: 2.28.0)
@sanity/base            2.27.1 (latest: 2.29.1)
@sanity/cli             2.27.0 (latest: 2.28.0)
@sanity/client           3.1.0 (latest: 3.2.2)
@sanity/core            2.27.0 (latest: 2.28.1)
@sanity/default-layout  2.27.1 (latest: 2.29.1)
@sanity/default-login   2.27.0 (latest: 2.29.1)
@sanity/desk-tool       2.27.1 (latest: 2.29.1)
@sanity/imagetool       2.23.3 (up to date)
@sanity/react-hooks     2.27.1 (latest: 2.29.1)
@sanity/vision          2.27.1 (latest: 2.29.1)

**What operating system are you using?**

macOS Big Sur (but this issue concerns Windows)

**Which versions of Node.js / npm are you running?**

7.24.2
v16.13.1

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
