### ISSUE TITLE
Customizing CORS Headers Of Assets

### ISSUE THREAD

**Issue by fweth** [sanity-io/sanity#3210]
Hi, this is not directly related to the Sanity Studio, but I couldn't find a repository for the Sanity Content Lake.

I tried to load images hosted by Sanity into a canvas and got the error

`Access to image at PATH from origin ORIGIN has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Setting the image's `crossOrigin` property to `Anonymous`, which sometimes does the trick, didn't work.

I don't think this has something to do with the [CORS settings](https://www.sanity.io/docs/cors), as access is not the problem, a normal HTML image with the given source displays just fine, only working with the canvas (either directly or via e.g. Three.js) causes troubles.

I also tested with assets from another CMS and they worked perfectly fine, even without setting any `crossOrigin` property.

**Comment by BigglesZX** [comment]
I'm also interested if there's a solution to this as my use-case involves fetching GeoJSON files from Sanity for display on the front-end, which I currently can't do cleanly due to the lack of CORS headers. My current workaround is to store the data in a text field which isn't ideal – the next thing I'll try will probably be proxying the request to the Asset API. Any updated info on this question to avoid those would be much appreciated.

**Comment by kmelve** [comment]
Thanks for reporting! This is not currently on our roadmap. My suggestion would be to look into proxying the requests. Closing this for now.

**Comment by BigglesZX** [comment]
@kmelve Thanks for the update. For future readers: I did end up proxying these requests – using Next.js it was a simple matter of including the following in `next.config.js`:

```js
module.exports = {
    // ...
    async rewrites() {
        return [
            {
                source: '/files/:path*',
                destination: 'https://cdn.sanity.io/files/:path*',
            },
        ];
    },
};
```
