### ISSUE TITLE
_createdAt behaves like _firstPublishedAt

### ISSUE THREAD

**Issue by jfulse** [sanity-io/sanity#3232]
**Describe the bug**

The way the `_createdAt` field is updated corresponds, to my mind, to a `_firstPublishedAt` - field. This might be more convenient (in fact it is, in our use), but seems inconsistent with the name. Will this behaviour stay the same so that we can rely on it?

**To Reproduce**

1. Create a new document (draft), observe the `_createdAt`-timestamp (for example using `/vision` and searching for the draft-id)
2. Publish the document. The timestamp now updates to the time of publishing
3. Unpublish the document. Notice that this time the timestamp is not updated; the new draft has the same `_createdAt` as the published did.
4. Publishing again does not change the timestamp; it stays the same as the time of first publish.

**Expected behavior**

From its name I would expect the `_createdAt`-field to correspond to either the time of creation of the first draft, or the time of creation of the current mode of document (i.e. draft or published), so that it would update e.g. when unpublishing.

The current behaviour is useful, but we're wondering if it's stable.

**Which versions of Sanity are you using?**

@sanity/cli             2.19.1 (latest: 2.29.3)
@sanity/base            2.29.1 (latest: 2.29.3)
@sanity/cli             2.28.0 (latest: 2.29.3)
@sanity/client           3.3.0 (up to date)
@sanity/core            2.28.1 (latest: 2.29.3)
@sanity/default-layout  2.29.1 (latest: 2.29.3)
@sanity/default-login   2.29.1 (latest: 2.29.3)
@sanity/desk-tool       2.29.1 (latest: 2.29.4)
@sanity/imagetool       2.23.3 (latest: 2.29.3)
@sanity/react-hooks     2.29.1 (latest: 2.29.3)
@sanity/vision          2.29.1 (latest: 2.29.3)

**What operating system are you using?**

macOS Big Sur

**Which versions of Node.js / npm are you running?**

8.5.5
v16.13.1

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
