### ISSUE TITLE
`sanity build` doesn't respect `sanity.json`'s `basePath`

### ISSUE THREAD

**Issue by tomas-hartman** [sanity-io/sanity#3254]
**Describe the bug**

Studio in `/admin` path created by [How to setup Sanity CMS with Next.js & TailwindCSS](https://www.sanity.io/guides/sanity-nextjs-tailwindcss) tutorial is not working.

The problem seems to be that Sanity does not care about `basePath` value in `sanity.json` and does not append the extra base path to assets paths in generated `index.html`, so I end up with 404s.

![obrazek](https://user-images.githubusercontent.com/44980733/164974963-baabc0c8-09c8-4bac-8117-24a851ac8a46.png)

In other words, I am getting the former instead of the latter:

```js
- http://localhost:3000/static/css/main.css?6e3dd0f78b38193
+ http://localhost:3000/admin/static/css/main.css?6e3dd0f78b38193
```

At this point, I am unable to say if the issue originates in some missing info in the tutorial or whether it depends on wrong/missing configuration in either `sanity` or `next`. Given the fact that sanity documentation says:

> The Studio can now be served from https://example.com/studio. This will also change the base path of static files.
>
> (https://www.sanity.io/docs/deployment#df9e4677bce5)

I assume this is a bug in sanity.

**Relevant info**

```js
// sanity.json

{
  "project": {
    "name": "personal-web",
    "basepath": "/admin"
  },
  // ...
}

// next.config.js

const STUDIO_REWRITE = {
  source: '/admin/:path*',
  destination:
    process.env.NODE_ENV === 'development'
      ? 'http://localhost:3333/admin/:path*'
      : '/admin/index.html',
};

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: ['cdn.sanity.io']
  },
  rewrites: () => [STUDIO_REWRITE],
};

module.exports = nextConfig;
```

```
// Folder structure:

Next.js project
|- admin (sanity studio root)
|- static
|  |- admin (sanity studio build)
|  |- other next.js static files
|- other next.js dirs and files
```

**To Reproduce**

Create a new next js and follow the main config steps from tutorial mentioned above.

**Expected behavior**

I should not be getting 404s when I self host sanity studio on `basePath` configured in `sanity.json` with `next.js`.

**Which versions of Sanity are you using?**

```
@sanity/cli                   2.29.5 (up to date)
@sanity/base                  2.29.5 (up to date)
@sanity/core                  2.29.5 (up to date)
@sanity/default-layout        2.29.5 (up to date)
@sanity/default-login         2.29.5 (up to date)
@sanity/desk-tool             2.29.5 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.29.5 (up to date)
```

**Which versions of Node.js / npm are you running?**

```
npm -v && node -v
8.1.2
v16.13.1
```

**Comment by rexxars** [comment]
We are unlikely to address this in Sanity v2, but with [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) this should already be fixed!

**Comment by azamatsmith** [comment]
I'm currently experiencing this issue with Sanity Studio v3.

**Comment by hazmah0** [comment]
I ran to this problem an hour ago as well while upgrading from v2 to v3. In v2 I used the [reserved env variables](https://www.sanity.io/docs/studio-environment-variables#cc239c4841f0) but that didn't work in v3.

Initially I thought about using the `basePath` property that is passed to the `defineConfig` function in `sanity.config.js` as described in the initial post of this issue but that didn't work when I was building the project, only when I was running the studio in dev mode.

The lead me to read through the build flow in the source code for the internal CLI and I eventually found this https://github.com/sanity-io/sanity/blob/next/packages/sanity/src/_internal/cli/actions/build/buildAction.ts#L85.

As you can see it does handle the basePath correctly when building static files but it uses an different config file. Instead of `sanity.config.js` it uses `sanity.cli.js`. So @azamatsmith you can try to add the following to `sanity.cli.js`

```
import { defineCliConfig } from 'sanity/cli'

export default defineCliConfig({
  api: {
    projectId: 'myId',
    dataset: 'myDataset',
  },
  project: {
    basePath: '/my-base-path',
  },
})
```

**Comment by stipsan** [comment]
@hazmah0 looks like we need to [update that list](https://www.sanity.io/docs/studio-environment-variables#cc239c4841f0). The env var in v3 is called [`SANITY_STUDIO_BASEPATH](https://github.com/sanity-io/sanity/blob/64e97151edb43bfc3a82bc7000e9dad925951efd/packages/sanity/src/_internal/cli/actions/dev/devAction.ts#L62)` instead of `SANITY_STUDIO_PROJECT_BASEPATH`.

If you're using NextJS and Studio on the same git repository we recommend using [`next-sanity/studio`](https://github.com/sanity-io/next-sanity#next-sanitystudio) as with this setup you only have to set the base path in your `sanity.config.js` and assets and the router "just works™".

**Comment by treerunner** [comment]
hazmah0's solution worked for me as well. Sanity Gatsby monorepo on Vercel with sanity basepath at /studio.

**Comment by CodeAdraas** [comment]
@hazmah0's solution also worked for me. However when `basePath` is specified in both config files, both dev server and static studio use the basepath twice in the URL. Why could that be?
