### ISSUE TITLE
Array field menu usability issue

### ISSUE THREAD

**Issue by eghernqvist** [sanity-io/sanity#3256]
**Describe the bug**

The menu for adding an item to an array field gets unusable on specific screen heights.

**To Reproduce**

Change height of window until popover of array item options end up tiny and stuck. Happens more often with array fields inside a dialog.

**Expected behavior**

The menu should grow upwards. In my opinions it should as soon as less than 3 items are visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/10044687/165042488-e617c8e2-a300-439a-b46d-bf8572a8a1d9.png)

**Which versions of Sanity are you using?**

```
@sanity/cli                2.29.3 (latest: 2.29.5)
@sanity/base               2.29.3 (latest: 2.29.5)
@sanity/cli             <missing> (latest: 2.29.5)
@sanity/code-input         2.29.3 (latest: 2.29.5)
@sanity/color-input        2.29.3 (latest: 2.29.5)
@sanity/components         2.14.0 (up to date)
@sanity/core               2.29.3 (latest: 2.29.5)
@sanity/default-layout     2.29.3 (latest: 2.29.5)
@sanity/default-login      2.29.3 (latest: 2.29.5)
@sanity/desk-tool          2.29.4 (latest: 2.29.5)
@sanity/vision             2.29.3 (latest: 2.29.5)
```

**What operating system are you using?**

Windows 10 - WSL2

**Which versions of Node.js / npm are you running?**

```
6.14.14
v14.17.5
```

**Additional context**

https://user-images.githubusercontent.com/10044687/165042976-b9aeb5d0-da67-412e-8827-cfbaa6daa56d.mp4

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
