### ISSUE TITLE
getting current document from custom input component

### ISSUE THREAD

**Issue by jansindl3r** [sanity-io/sanity#3276]
**Is your feature request related to a problem? Please describe.**
I want to access other values in current document, I follow your tutorial https://www.sanity.io/guides/asynchronous-list-options, but the difference is that I the "breeds" are the current document in other field.

**Describe the solution you'd like**
I would like to get the document either in props (currently I only get parent, which is the input field)
or use a hook or context to get to that document or at least id (sorry if something like that already exists but I didn't find it)

**Describe alternatives you've considered**
this is current approach that I temporarily use
```javascript
const {pathname} = window.location
const parts = pathname.split("/").filter(part => part.length)
const partsMapping = parts.reduce((collector, part) => {
  const match = part.match(/(?<key>.*);(?<value>[a-zA-Z0-9._-]+)/)
  if (match) { // extend the logic
    collector[match.groups.key] = match.groups.value
  }
  return collector
}, {})
// and then I see if document's name is in the dictionary and query the current document with Sanity client

```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
