### ISSUE TITLE
Add new type `listItemText` to structure builder

### ISSUE THREAD

**Issue by vincentboiardt** [sanity-io/sanity#3277]
**Is your feature request related to a problem? Please describe.**
Similar to `S.divider()` I would want a purely presentational element in the structure builder

**Describe the solution you'd like**
An additional type to the structure builder, like `S.listItemText().title('My title')`

**Describe alternatives you've considered**
The syntax could be different, like `S.listItemText('My title')` or perhaps the divider could be extended with a title method `S.divider().title('My title')`

**Additional context**
Quick mockup
![Screen Shot 2022-05-05 at 16 50 48](https://user-images.githubusercontent.com/448541/166951356-a6fdaf4c-33a9-407d-ab16-d95b69dbaa17.png)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
