### ISSUE TITLE
Using the duplicate action on a reference within an array doesn't duplicate the ID.

### ISSUE THREAD

**Issue by tonybhz** [sanity-io/sanity#3290]
**Describe the bug**
I have a document type called "page" with a field type array, to multiple other references it all works great, however let's say a user uses the duplicate function to create an additional "Anchor Block", like I have in my code below. Sanity just references the same ref._id instead creating a new one. Is this by design or a bug? Any help would be great.

```
import commonPageFields from '../partials/commonPageFields';

export default {
  name: 'page',
  type: 'document',
  title: 'Page',
  fieldsets: [
    {
      title: 'SEO & metadata',
      name: 'metadata',
    },
  ],
  fields: [
    ...commonPageFields,
    {
      name: 'blocks',
      type: 'array',
      title: 'Content Blocks',
      description: 'The components that make up the page body.',
      of: [
        {
          type: 'reference',
          title: 'Anchor',
          name: 'anchorSection',
          to: {type: 'anchorSection'},
        },
      ],
    },
  ],
  orderings: [
    {
      title: 'Title, A-Z',
      name: 'title',
      by: [{field: 'title', direction: 'asc'}],
    },
    {
      title: 'Title, Z-A',
      name: 'title',
      by: [{field: 'title', direction: 'desc'}],
    },
  ],
  preview: {
    select: {
      title: 'title',
      media: 'openGraphImage',
    },
  },
```

**To Reproduce**
n/a - private code base.

**Expected behavior**
Sanity to create a new _ref id instead of referencing the previous one.

**Screenshots**
Result after running duplicate:
<img width="698" alt="Screen Shot 2022-05-13 at 11 00 31 AM" src="https://user-images.githubusercontent.com/95704707/168323094-f2a1eed6-3efe-4e5a-afec-ed9e2f50593f.png">

Duplicate _ref ids:
<img width="493" alt="Screen Shot 2022-05-13 at 11 01 15 AM" src="https://user-images.githubusercontent.com/95704707/168323098-3dab2530-48e9-4712-8f64-9e0c89b0e366.png">

**Which versions of Sanity are you using?**
@sanity/cli                2.22.3 (latest: 2.30.0)
@sanity/base               2.27.1 (latest: 2.30.0)
@sanity/cli                2.30.0 (up to date)
@sanity/components         2.14.0 (up to date)
@sanity/core               2.27.0 (latest: 2.30.0)
@sanity/default-layout     2.27.1 (latest: 2.30.0)
@sanity/default-login      2.27.0 (latest: 2.30.0)
@sanity/desk-tool          2.27.1 (latest: 2.30.0)
@sanity/generate-help-url     ??? (latest: 3.0.0)
@sanity/vision             2.27.1 (latest: 2.30.0)

**What operating system are you using?**
Mac OS X - Big Sur 11.6.4

**Which versions of Node.js / npm are you running?**
6.14.11
v14.16.0

**Comment by dhruv850** [comment]
I am facing the same issue. did you find any solution around this?

**Comment by mattparisien** [comment]
Would love to see this implemented as a feature

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by campbell-hay** [comment]
Sorry it is an old thread, but I encountered what I believe is the same issue on one of my projects. But in my case, these were big objects that ended up being changed by accident. I have found at least a way of avoiding catastrophes by adding a "unique()" validation on the field. However I was wondering if you found a work around to duplicate the referenced content instead of duplicating the reference itself.

**Comment by jschneider33** [comment]
+1 for me. I have an array of objects that have similarly nested objects that I was hoping I could duplicate and just change the fields that differ, but when I click "Duplicate" it copies the refs and any change is applied to each index in the array, not just the newly duplicated one. 

I realize it's an array of references as @bobinska-dev mentioned above, but I think either adjusting the "duplicate" option to create a new ref instead of copying the existing one, or creating a new menu option to carry out that action would be a beneficial UX improvement for users.
