### ISSUE TITLE
Custom preview using 'withDocument' crashes Studio on search

### ISSUE THREAD

**Issue by Ojay** [sanity-io/sanity#3293]
**Describe the bug**

When implementing a custom preview component for a document type `withDocument` crashes the Studio when a search is made. The preview component works perfectly within the scope of the document (in a reference field to the same doc type for example). The Studio crashes with the following error...

`TypeError: Cannot read properties of undefined (reading 'getDocument')`

...presumably because the document scope isn't available in the search results.

**To Reproduce**

1. Fresh install of Sanity
2. Add a custom preview component as outlined [here](https://www.sanity.io/schemas/sanity-custom-preview-component-to-get-parent-document-e050b543)
3. Search for a document

**Expected behavior**

Studio not to crash.

**Which versions of Sanity are you using?**

@sanity/cli          2.29.8 (latest: 2.30.0)
@sanity/client        3.3.0 (up to date)
@sanity/image-url     1.0.1 (up to date)

**Which versions of Node.js / npm are you running?**
8.3.1
v16.14.0

**Comment by ehuelsda** [comment]
We've got the same issue. 
Versions:
@sanity/cli             2.30.0
@sanity/core         2.30.1

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
