### ISSUE TITLE
Feature suggestion: usePreviewSubscription to support graphql queries

### ISSUE THREAD

**Issue by ollebergkvist** [sanity-io/sanity#3299]
Would be fantastic if the usePreviewSubscription hook could also support graphql queries.

Which would enable a graphql + graphql-codegen stack with Sanity.

**Comment by Knaackee** [comment]
Wondering why this is not already implemented.

**Comment by ollebergkvist** [comment]
I have the feeling it won't be implemented.
We decided to switch to:
https://payloadcms.com/

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
