### ISSUE TITLE
Ability to hide/show group fields based on the value of a field

### ISSUE THREAD

**Issue by quentin-f451** [sanity-io/sanity#3305]
Conditional fields are a really great feature but it seems really odd to me that conditional group fields don't act the same way and that you can't get the value of a field in the hidden function with the `document` property.

It's especially important if you hide/show several fields based on the value of another one and that the group field then become empty. It would then be extremely useful to have the ability to hide/show the group fields here.

### Describe the solution you'd like
It would be really useful to have the very same callback properties (`document`, `parent`, `value`, `currentUser`) for conditional group fields than for conditional fields, as we would probably use them the same way.

### Describe alternatives you've considered
I've tried to get the value of the field I need by passing a GROQ query to client fetch function with the `_id` of the document in the URL of the page, it works OK but only when you arrive on the page. It's not updated as you modify the document, and if the document is not published.

**Comment by nadirabbas** [comment]
Definitely needed, +1

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
