### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by AWAIS97** [sanity-io/sanity#3310]
**New with sanity**
But facing a issue while trying to run with my project. I have latest version of sanity installed globally. but Every time i run my project I am facing this Error message
```
Unhandled Runtime Error
Error: Bad Request
Please upgrade to latest version of the Sanity CLI using `npm install -g @sanity/cli` and run `sanity login` to re-authenticate

Call Stack
Object.eval [as callback]
node_modules/@sanity/client/lib/http/request.js (46:0)
cbOnce
node_modules/@bjoerge/xhr/index.js (62:0)
loadFunc
node_modules/@bjoerge/xhr/index.js (138:0)
XMLHttpRequest.readystatechange
node_modules/@bjoerge/xhr/index.js (68:0)
```
I run this `npm install -g @sanity/cli` command many times but no progress..

My node -v is 16

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
