### ISSUE TITLE
Unexpectable `text` field cursor shift while typing

### ISSUE THREAD

**Issue by ezabelin-getsafe-github** [sanity-io/sanity#3311]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

While writing the text in `text` field the cursor always jumps to the end UNLESS you type one letter very slowly. 

**To Reproduce**

This is pretty unreproducible behaviour, but it occurs more often as we have more complex structure of the schema (e.g. `text` field lies deeper in the hierarchy)

**Expected behaviour**

It's expected that cursor is following your input.

**Which versions of Sanity are you using?**

2.20.0

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
