### ISSUE TITLE
Graphql filter does not resolve nested references.

### ISSUE THREAD

**Issue by KwehDev** [sanity-io/sanity#3312]
Hello, 

I have an `ExerciseTranslation` type, which has a singular reference to an `Exercise`.

That exercise has an array of references to `Audience` type documents.

I am attempting to filter exerciseTranslations where the exercises references a specific audience ID, with the below query;

```
allExerciseTranslation(where: {
  exercise: {
     _: {
       references: AudienceID
     }
   }
  }) {
    exercise {
      audiences {
        _id
      }
    }
  }
```

However, this returns an empty array. If I remove the filter argument, exercise.audiences._id does indeed contain the value passed to the filter.

**Expected behavior**

I would expect to receive an Array of ExerciseTranslations matching my filter.

**Which versions of Sanity are you using?**

@sanity/cli  2.22.0 (latest: 2.30.0)

**What operating system are you using?**

MacOS Monterey

**Security issue?**

N/A

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
