### ISSUE TITLE
Simplify editing of built in image assets

### ISSUE THREAD

**Issue by joaisa17** [sanity-io/sanity#3313]
**Is your feature request related to a problem? Please describe.**
Where users will be uploading images, it is currently not possible to edit image title, alt text etc...
unless you use the desk-tool to make a document list for `sanity.imageAsset`

**Describe the solution you'd like**
Add an option to edit properties of an image upon uploading it, such as in the asset menu. Where you can
select an image, you should also be able to edit the alt text of said image.

**Describe alternatives you've considered**
Making custom objects, with an image field, a title field and an alt text field works. However, this does not seem necessary
if Sanity already has a built in feature for this.

**Additional context**
A screenshot of a working Desk Structure, allowing users to edit the properties:
![Screenshot](https://user-images.githubusercontent.com/89845084/171404005-596e2d17-d3ca-4a86-8cfa-51adefb5f2d9.png)

Structure for a list item containing all images:
```js
S.listItem()
    .title('Images')
    .child(
        S.documentTypeList('sanity.imageAsset')
    )
```

**Comment by Rhym** [comment]
I'd recommend using this: https://www.sanity.io/plugins/sanity-plugin-media

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
