### ISSUE TITLE
editModal: "popover" causes error in development: "flushSync was called from inside a lifecycle method. It cannot be called when React is already rendering"

### ISSUE THREAD

**Issue by steveoaustin** [sanity-io/sanity#3317]
**Describe the bug**

I set the modal style of an array like this:
`options: {
     editModal: "popover"
 }`

**To Reproduce**

1. Set an array field's options to `{ editModal: "popover" }`
2. Run `sanity start`
3. Add a new element to that array, or click an existing element
4. The desk tool has crashed with the error text specified in title (full screenshot of the error below)

**Expected behavior**

Built in settings function without crashing 

**Screenshots**

![image](https://user-images.githubusercontent.com/21183137/172735384-8f404ea0-c6a6-46af-a50a-fc5469dc3788.png)

**Which versions of Sanity are you using?**

`@sanity/cli                   2.30.0 (up to date)
@sanity/base                  2.30.1 (up to date)
@sanity/core                  2.30.1 (up to date)
@sanity/default-layout        2.30.1 (up to date)
@sanity/default-login         2.30.1 (up to date)
@sanity/desk-tool             2.30.1 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.30.1 (up to date)`

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

- npm: 8.12.1
- node: v16.15.1

**Additional context**

The popup modal works as expected when deployed, it only crashes when testing

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
