### ISSUE TITLE
Desk tool crashes on multiple plugins

### ISSUE THREAD

**Issue by milanbabiclibrafire** [sanity-io/sanity#3340]
Desk tool crashes on plugins:

`Error: flushSync was called from inside a lifecycle method. It cannot be called when React is already rendering.`

**@sanity/color-input**
When plugin options->tooltip enabled - clicking on color will cause crash

**media-library**
Selecting any media will cause crash - not happening in detailed mode

---

**Which versions of Sanity are you using?**

"@sanity/base": "^2.30.1",
"@sanity/color-input": "^2.30.1",
"@sanity/core": "^2.30.1",
"@sanity/default-layout": "^2.30.1",
"@sanity/default-login": "^2.30.1",
"@sanity/desk-tool": "^2.30.1",
"@sanity/eslint-config-studio": "^2.0.0",
"@sanity/vision": "^2.30.1",
"eslint": "^8.6.0",
"prop-types": "^15.7",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"sanity-plugin-color-list": "^2.0.2",
"sanity-plugin-media": "^1.4.10",
"styled-components": "^5.2.0"

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

Run npm -v && node -v in the terminal and copy-paste the result here.
8.5.5
v16.15.0

**Comment by sokolenkov** [comment]
Same issue

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
