### ISSUE TITLE
Unhandled error when navigating to project studio on browser

### ISSUE THREAD

**Issue by chrisfaltsetas** [sanity-io/sanity#3383]
When navigating to https://myproject.sanity.studio, I randomly encounter the following error:

> Unhandled error
> Encountered an unhandled error in this Studio.
> 
> Reload page
> 
> l@/static/js/vendor.bundle.js?b6c2a2a9d4166b4a779f:1:405
> @/static/js/app.bundle.js?815a224a89378c3ee8b9:104:969375
> l@/static/js/vendor.bundle.js?b6c2a2a9d4166b4a779f:1:410
> @/static/js/app.bundle.js?815a224a89378c3ee8b9:104:969311
> l@/static/js/vendor.bundle.js?b6c2a2a9d4166b4a779f:1:410
> window.webpackJsonp@/static/js/vendor.bundle.js?b6c2a2a9d4166b4a779f:1:284
> @/static/js/app.bundle.js?815a224a89378c3ee8b9:1:13

It sometimes happens after deploying, sometimes randomly during the day.
First happened today. We upgraded from 2.30.0 to version 2.30.1, but didn't seem to help.

sanity versions
@sanity/cli                            2.30.2 (up to date)
@sanity/base                           2.30.1 (up to date)
@sanity/core                           2.30.2 (up to date)
@sanity/default-layout                 2.30.1 (up to date)
@sanity/default-login                  2.30.1 (up to date)
@sanity/desk-tool                      2.30.1 (up to date)
@sanity/document-internationalization   0.3.2 (up to date)
@sanity/google-maps-input              2.30.1 (up to date)
@sanity/language-filter                2.29.8 (up to date)
@sanity/production-preview             2.29.3 (up to date)
@sanity/vision                         2.30.1 (up to date)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
