### ISSUE TITLE
@sanity/client warning with react-native

### ISSUE THREAD

**Issue by barbogast** [sanity-io/sanity#3384]
**Describe the bug**

Importing `@sanity/client` in a react-native app results in the following warning being printed to the console multiple times:

```
Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue 
on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. 
See https://github.com/facebook/react-native/issues/12981 for more info. (Saw setTimeout with duration 300000ms)
```

We could fix the issue by using `picosanity`, but others might not be so lucky, so I thought this deserves to be reported.

**To Reproduce**

Create a react-native app, install @sanity/client and import it.

**Which versions of Sanity are you using?**

2.30.2

**Additional context**

```
"expo": "^44.0.0",
"react-native": "0.64.3",
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
