### ISSUE TITLE
Image URL when selecting/uploading a new image

### ISSUE THREAD

**Issue by joaisa17** [sanity-io/sanity#3398]
While working with images in Sanity, I noticed how you can only upload images, or browse.

I would like the ability for Sanity to save a URL.
As per now, I have to save the image off the internet first, and then upload it.

**Comment by malewis5** [comment]
Why not use a field with type `string` and store the URL there? The image type is for storing actual image files.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
