### ISSUE TITLE
Sanity studio pops up error after logs in

### ISSUE THREAD

**Issue by bestcodeeditor** [sanity-io/sanity#3420]
Hi  , Currently I am hosting a Next JS site on vercel with a Sanity CMS backend for content editing. we got it configured to run on a single domain, for Example -(https://mysite.com) has the front-end website, where (https://mysite.com/studio) opens the Sanity Studio editor.Frontend website is working fine in vercel without any issue. But once I browse sanity editor via (https://mysite.com/studio) it redirects to(https://mysite.com/studio/desk) after went through login process.The page (https://mysite.com/studio/desk) pops up a "desk tool error". The console error is "No router context provider found".                                                                                          when I browse "https://mysite/studio/index.html" , it gives also an error"The list of tools installed in this Studio does not include index.html"   Now there is no console error in browser regarding "router context". where do  I need to configure this index.html in the sanity code.    I appreciate if sanity team provides any solution.                                                                                         

next.config.js->  
                                                                                                                                                                                                   ```
module.exports = {
  reactStrictMode: true,
  images: {
    domains: ["[cdn.sanity.io](http://cdn.sanity.io/)", "[res.cloudinary.com](http://res.cloudinary.com/)"],
  },  async rewrites() {
    return [
      {
        source: "/studio/:path*",
        destination:
          process.env.NODE_ENV === "development"
            ? "http://localhost:3333/studio/:path*"
            : "/studio/index.html",
      },
    ];
  },
};               
```       
sanity.json -> 

 "basePath": "/studio"

 vercel.json

```
 {
  "version": 2,
  "rewrites": [
    { "source": "/studio/(.*)", "destination": "/studio/index.html" }
  ]
}
```

sanity studio package.json ->

 ```
"scripts": {
    "start": "sanity start",
    "test": "sanity check",
    "build": "sanity build"
  },
  "keywords": [
    "sanity"
  ],
  "dependencies": {
    "@sanity/base": "^2.29.1",
    "@sanity/components": "^2.14.0",
    "@sanity/core": "^2.28.1",
    "@sanity/default-layout": "^2.29.1",
    "@sanity/default-login": "^2.29.1",
    "@sanity/desk-tool": "^2.29.1",
    "@sanity/vision": "^2.29.1",
    "prop-types": "^15.7",
    "react": "^17.0",
    "react-dom": "^17.0",
    "styled-components": "^5.2.0"
  },
```

  nextjs root package.json->

  ```
{
  "name": "example-blog",
  "version": "0.0.0",
  "private": true,
  "description": "Blog",
  "devDependencies": {
   "autoprefixer": "^10.4.7",
    "postcss": "^8.4.13",
    "tailwindcss": "^3.0.24"
  },
  "scripts": {
     "dev": "concurrently \"next dev\" \"cd studio && sanity start\"",
    "prebuild": "echo 'Building Sanity to public/studio' && cd studio && yarn && npx @sanity/cli build ../public/studio -y && echo 'Done'",
      "build": "cross-env NODE_ENV=production next build",
    "start": "concurrently \"next start\" \"cd studio && sanity start\""
    
  },
  "keywords": [],
  "author": "sdev",
  "license": "MIT",
  "dependencies": {
    "@sanity/cli": "^2.0.5",
   "next": "12.1.5",
      ...........
      ..........
  }
}                      
```

**Comment by vassbo** [comment]
I also got had a simular issue in my Gatsby React application. First the studio was working fine, but suddenly I must have messed up something in the dev studio, because I got this error: "No router context provider found". And the studio error popup was looping infinitely. After a long time I found out that the issue must have been in my package-lock.json file. I have no idea what package, but I copied the file and node_modules from a known working studio. And now it works again.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
