### ISSUE TITLE
graphql deployment crashes on dev-preview-15

### ISSUE THREAD

**Issue by eirikeis** [sanity-io/sanity#3543]
Using the `deploy-graphql` script I get:
```
Error: Failed to load configuration file "/[project-path]/sanity.config.ts":
Unexpected token 'export'
```

Am I doing anything wrong or is this a bug in studio version 3?

Sanity studio version: **dev-preview-15**
Operating system: **Mac OS Montery**
Node.js **v16.14.0**

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
