### ISSUE TITLE
In liveEdit, it's not possible to edit a document that has a draft

### ISSUE THREAD

**Issue by VanCoding** [sanity-io/sanity#3563]
**Describe the bug**

It seems like  #886 is still (or again) open:

**To Reproduce**

1. Turn liveEdit off for a document type
2. Edit a document of that type, wihtout saving, so that it gets a draft
3. Turn liveEdit back on
4. Try to edit the document

**Expected behavior**

It should be possible to edit the document

**Which versions of Sanity are you using?**
2.31.0

**What operating system are you using?**
Linux

**Which versions of Node.js / npm are you running?**

14

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
