### ISSUE TITLE
GitHub log in wont work !

### ISSUE THREAD

**Issue by Chanirulk** [sanity-io/sanity#3573]
I tried running npx @sanity/cli init and then I got to choose my login methods, once I decided to choose Github the terminal showed this error...

**You're setting up a Sanity.io project!
We'll make sure you're logged in with Sanity.io.
Then, we'll install a Sanity Studio for your project.

Press ctrl + C at any time to quit.

We can't find any auth credentials in your Sanity config
- log in or create a new account

? Login type Google

Opening browser at https://api.sanity.io/v1/auth/login/google?type=listen&uuid=ffff45f26f3ac37ed6d4f22bda09717b&source=cli

⠋ Waiting for browser login to complete... Press Ctrl + C to cancelnode:events:498
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [
    '/c',
    'start',
    '""',
    '/b',
    'https://api.sanity.io/v1/auth/login/google?type=listen^&uuid=ffff45f26f3ac37ed6d4f22bda09717b^&source=cli'
  ]
}**

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
