### ISSUE TITLE
sanity start linux localhost:3333 issue

### ISSUE THREAD

**Issue by CodeLikeLisa** [sanity-io/sanity#3581]
I have changed browsers (chrome/brave/firefox), changed third-party cookie settings and even checked on ports in my linux private server, nothing has been successful thus far.. I get `Content Studio successfully compiled! Go to http://localhost:3333` success message however when visiting the site on numerous browsers, I receive no errors - it simply is stuck on reload... I was told it is most likely a firewall issue - does anyone have direction on this?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
