### ISSUE TITLE
Image EXIF data not included when uploading multiple images to array type

### ISSUE THREAD

**Issue by jedifunk** [sanity-io/sanity#3598]
**Describe the bug**
When using an array type of image types. Uploading multiple images doesn't include the associated EXIF data for the images. Uploading a single image into the array does include the EXIF data.

**To Reproduce**

1. Add new array to Studio
2. drag and drop multiple images onto array field
3. query uploaded images
4. no EXIF data is returned

**Expected behavior**

Expect EXIF data to be included/attached to each image when using multiple upload on array type.

**Screenshots**

**Which versions of Sanity are you using?**

2.30.2

**Additional context**

Has been pointed out in the past, as was told it was being looked into. Haven't heard anything for months.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
