### ISSUE TITLE
Array of primitive types only results in being able to use one field

### ISSUE THREAD

**Issue by webdevtrev** [sanity-io/sanity#3627]
When using an array of primitive types no matter which I select in the array I can only use the first one.

Here is my code for the array I am trying to create

```
    {
      title: 'Content',
      name: 'content',
      type: 'array',
      of: [
        {
          title: 'Heading',
          name: 'heading',
          type: 'string',
        },
        {
          title: 'Subheading',
          name: 'subheading',
          type: 'string',
        },
        {
          title: 'Paragraph',
          name: 'paragraph',
          type: 'text',
        },
      ],
    },
```

And any selection results in a heading being added to the array like so

![image](https://user-images.githubusercontent.com/66264441/189566805-59ad6abd-bf08-4329-b44a-cb791f7606cf.png)

**Expected behavior**

To be able to pick and choose which field should be added in whichever order

**Which versions of Sanity are you using?**

```
@sanity/cli                      2.30.0 (latest: 2.32.0)
@sanity/base                     2.33.0 (up to date)
@sanity/core                     2.33.0 (up to date)
@sanity/default-layout           2.33.0 (up to date)
@sanity/default-login            2.33.0 (up to date)
@sanity/desk-tool                2.33.0 (up to date)
@sanity/orderable-document-list   0.0.3 (latest: 0.0.10)
@sanity/vision                   2.33.0 (up to date)
```

**What operating system are you using?**
Mac OS

**Which versions of Node.js / npm are you running?**

npm 8.1.0
node v16.13.0

**Comment by rexxars** [comment]
Ideally, this should have been caught and disallowed by schema validation;

This shouldn't actually be allowed, since there is no way to differentiate between these types - they are all just stored as strings:
```json
[
  "this is a heading",
  "this is a subheading",
  "this is a paragraph"
]
```

If you want to do something like this you'll have to wrap these in objects instead, so we can know which type it was expected to be:

```json
[
  {"_type": "heading", "text": "this is a heading"},
  {"_type": "subheading", "text": "this is a subheading"},
  {"_type": "paragraph", "text": "this is a paragraph"},
]
```

At this point you might want to consider using [Portable Text](https://www.sanity.io/guides/introduction-to-portable-text#0dca54b0d56a) though, or making a single object type with a `style` property or similar.

I am closing this and opening a new issue to address the lack of schema validation here.
