### ISSUE TITLE
Styled-component error with next-sanity

### ISSUE THREAD

**Issue by hoggworks** [sanity-io/sanity#3630]
I created a nextjs app, then installed next sanity to try the v3 studio in it. 

I needed to install styled-components to get it to work, but now when I try to use the studio I get the following error:

TypeError: Cannot read properties of undefined (reading 'color')

Call Stack
<unknown>
file:///Users/brianhogg/Documents/Work/jcc-test/node_modules/next-sanity/lib/cjs/studio.js (314:36)

1. Creates Next-js app
2. Install next-sanity
3. Install sanity, styled-components
4. Create route with this code:
5. `import { NextStudio, NextStudioProps } from "next-sanity/studio";
import config from "../../sanity.config";

export default function StudioPage() {
  return <NextStudio config={config} />;
}
`

**Expected behavior**

I was hoping the studio would load.

**Screenshots**

**Which versions of Sanity are you using?**

I'm running sanity/cli 2.26.0
node 16.13.2

Package.json contents:
`"dependencies": {
    "@portabletext/react": "^1.0.6",
    "@sanity/image-url": "^1.0.1",
    "autoprefixer": "^10.4.9",
    "next": "12.3.0",
    "next-sanity": "^0.8.4",
    "postcss": "^8.4.16",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "sanity": "^2.29.3",
    "styled-components": "^5.3.5",
    "tailwindcss": "^3.1.8"
  },
  "devDependencies": {
    "@types/node": "18.7.16",
    "@types/react": "18.0.18",
    "@types/react-dom": "18.0.6",
    "eslint": "8.23.0",
    "eslint-config-next": "12.3.0",
    "typescript": "4.8.3"
  }
}`

Running on an M1 Mac

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

Thanks!

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
