### ISSUE TITLE
Sanity initialisation fails at Resolving dependencies

### ISSUE THREAD

**Issue by jajaperson** [sanity-io/sanity#3695]
**Describe the bug**
Whenever I try to run `sanity init` (see screenshot below) in a new NextJS project it fails at the resolving dependencies stage.

```
✔ Bootstrapping files from template
✔ Resolving latest module versions
✔ Creating default project files
✖ Resolving dependencies

Error: Command failed :(
    at ~/.npm/_npx/97fe0ac6ea3bd86d/node_modules/@sanity/cli/bin/sanity-cli.js:3626:2582
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e.default (~/.npm/_npx/97fe0ac6ea3bd86d/node_modules/@sanity/cli/bin/sanity-cli.js:4896:10725)
```

**To Reproduce**

1. Create a new NextJS project using the default `create-next-app` behaviour.
2. Create a Sanity project using the "Get started" interface.
3. Run the command as instructed by the "Get started interface,4. 
4. Change the name of the output path to `studio`.

**Screenshots**
![Screen Shot 2022-09-29 at 3 06 32 pm](https://user-images.githubusercontent.com/25611007/192964790-7ecf9ad7-7ffa-4e0a-9fa7-6d9d5b87cacf.png)
**What operating system are you using?**
macOS v12.5.1

**Which versions of Node.js / npm are you running?**

```
❯ node --version
v18.9.1
❯ npm --version
8.19.1
```

**Comment by n1xn** [comment]
I am facing the same issue using the same stack without any template

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
