### ISSUE TITLE
Desk tool crashes and throws TypeError when I attempt editing schema content

### ISSUE THREAD

**Issue by Israeltheminer** [sanity-io/sanity#3703]
**Describe the bug**

The sanity studio is deployed to localhost:3333 successfully with the included schemas visible, but on trying to edit the content of the schema it throws this error. TypeError: (0 , _validation2.validation) is not a function
PS.
I have tried reinstalling @sanity/cli multiple times, and even tried using the default e-commerce and blog-post schemas and this still also throws this same error so my schema is of no consequence to the error if the default produced the same error

**Screenshots**
![image](https://user-images.githubusercontent.com/79730986/193361024-513bba18-d52d-45e7-a236-757cd79cdfcf.png)

**Which versions of Sanity are you using?**
@sanity/cli                   2.34.0 (up to date)
@sanity/base                  2.34.0 (up to date)
@sanity/core                  2.34.0 (up to date)
@sanity/default-layout        2.34.0 (up to date)
@sanity/default-login         2.34.0 (up to date)
@sanity/desk-tool             2.34.0 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.34.0 (up to date)

**What operating system are you using?**
Windows 10 || 64bit

**Which versions of Node.js / npm are you running?**
npm - 8.6.0
Node - v18.0.0

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
