### ISSUE TITLE
ServerError (timed out) when using NuxtJS in SSG mode with Sanity

### ISSUE THREAD

**Issue by JonathanDoelan** [sanity-io/sanity#3705]
**Describe the bug**

I have a NuxtJS (Version 2) app running in SSG mode and Sanity.io as CMS. NuxtJS generates/prerenders about 300 pages (data comes from Sanity API), which takes quite some time. The problem is that after a while I get the following error (at build stage):

```ServerError: The operation timed out```

So I guess Sanity is closing the server connection, while NuxtJS is still generating pages. I reduced the amount of pages to about 280 and then it works. So it seems like Sanity closes the connection too early.

**Possible solutions**

1. Is there a way to keep the server connection to Sanity.io longer alive, before the operation is timed out?
2. Is there a way to split up the static site generation with NuxtJS, so that after (let‘s say) 50 pages the current connection to sanity closes and a new one starts for the next 50 pages?

Is there any other solution you can think of?

Or is this a Sanity.io bug?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
