### ISSUE TITLE
Sanity CLI does not run on current directory when invoked with `yarn sanity`

### ISSUE THREAD

**Issue by grikomsn** [sanity-io/sanity#3738]
**Describe the bug**

Sanity CLI binary does not run on current directory if invoked using `yarn exec` or `yarn` which breaks reading `sanity.config.{js,ts}` file. Reason being is that if using `yarn exec`, binary will run on its own directory (`$PROJECT_DIR/node_modules/.bin/sanity`) and attempts to read config file on that directory.

But if Sanity CLI is installed globally and invoked using `sanity`, it'll run the binary on the current directory since it does not require resolving with Yarn.

**To Reproduce**

1. Execute `yarn sanity dataset export [env]` and it can't find the config file ❌
2. Instal CLI package globally and execute `sanity dataset export [env]` ✅

**Expected behavior**

- Sanity CLI binary should run on current directory if invoked using `yarn exec` or `yarn`
- `yarn sanity dataset export [env]` should behave the same as `sanity dataset export [env]`

**Screenshots**

![image](https://user-images.githubusercontent.com/8220954/194625378-7b13ec5c-d382-45ac-af2b-f57fb4e992e4.png)

**Which versions of Sanity are you using?**

`@sanity/cli (global)  3.0.0-dev-preview.20 (latest: 2.34.0)`

**What operating system are you using?**

Windows 11, Linux, macOS

**Which versions of Node.js / npm are you running?**

- Node.js 16 and 18
- npm 8.19.2
- yarn 1.22.19
- pnpm 7.13.2

**Additional context**

\-

**Security issue?**

No.

cc @XanderJL @joshuanatanielnm

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread.
