### ISSUE TITLE
Sometimes my changes doesnt being applied to my project

### ISSUE THREAD

**Issue by Bayramito** [sanity-io/sanity#3749]
Simply sometimes when i change field values in the dashboard, they are not being applied to the project.
My project is built with Next.js and using SSR, it is a very basic app that getting data from the sanity and listing them. 

Another strange behavior is, for example i change the price of an item and its being changed on the listing page, but in detail page it's showing the previous value.

This is the Listing page. Here the price is correct once i changed it.

![Ekran Resmi 2022-10-12 11 53 07](https://user-images.githubusercontent.com/44513402/195297957-4d6a449c-2221-4d9d-b581-d19725e6ab08.png)

And this is the detail page, the price is still previous and not changing.
![Ekran Resmi 2022-10-12 11 53 17](https://user-images.githubusercontent.com/44513402/195298133-33967e06-0a19-46d2-b74c-3c19effca61a.png)

i get both items from the exact same collection.

In detail page i grap the data like below:

```
export const getStaticPaths = async () => {
  const query = `*[_type == "product"] {
        slug{
            current
        }
    }`;

  const products = await client.fetch(query);
  const paths = products.map((product) => ({
    params: {
      slug: product.slug.current,
    },
  }));
  return {
    paths,
    fallback: "blocking",
  };
};

export const getStaticProps = async ({ params: { slug } }) => {
  const query = `*[_type == 'product' && slug.current == "${slug}"][0]`;
  const productsQuery = "*[_type == 'product']";
  const product = await client.fetch(query);
  const products = await client.fetch(productsQuery);
  console.log("product", product);
  return {
    props: {
      products,
      product,
    },
  };
};
```

The reason i grap all the items again is to create similar products kind of thing. The most interesting thing is everyting works fine on development env...  but not on the fly

**Comment by geball** [comment]
Hi @Bayramito. It sounds like you may benefit from using [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration), which will let you regenerate static pages on a per-page basis. Without that, you would need to rebuild your app whenever your content changed (unless you switched to something like getServerSideProps).

getStaticProps [runs on every request in development](https://nextjs.org/docs/basic-features/data-fetching/get-static-props#runs-on-every-request-in-development), which is why this is working for you locally.
