### ISSUE TITLE
V3: swcMinify Causing "React Minified React error #130"

### ISSUE THREAD

**Issue by jndao** [sanity-io/sanity#3763]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**
When `swcMinify` is `true` on NextJS sanity studio embedded in `next.config.ts`, React Minify error # 130 will occur during Vercel deployment.

The studio works correctly locally

**To Reproduce**

1. Add `swcMinify: true` to nextjs
2. Deploy NextJs app via Vercel
3. Go to embedded studio and see minify issues

**Expected behavior**
For there not to be any minify issues when using `swcMinify: true` or update documentation to communicate that is not supported

**Which versions of Sanity are you using?**
"next": "^12.3.1"
"sanity": "3.0.0-purple-unicorn-starter.43"

**What operating system are you using?**
Windows

**Which versions of Node.js / npm are you running?**
Node v16.18.0
Npm v8.19.2
Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional context**

May be related to  #3697 and #3708.

Icons and previews are working correctly after removing `swcMinify: true`. Issue may be related to `next-transpile-modules`.

**Comment by rexxars** [comment]
This is indeed caused by a bug in swc - the next release of next.js will fix it. You can either disable swc with `swcMinify: false` for now, or upgrade to the canary release of next.js: [12.3.2-canary.32](https://www.npmjs.com/package/next/v/12.3.2-canary.32)

The fix will be in a proper release before/on next.js conf on Tuesday, October 25th. Leaving this open until then so others might be able to find the solution in the meantime.

**Comment by steveluscher** [comment]
See https://github.com/vercel/next.js/issues/41527
