### ISSUE TITLE
Custom ordering of documents using custom condition, getting drafts first, then published,

### ISSUE THREAD

**Issue by shikhar13012001** [sanity-io/sanity#3771]
**Is your feature request related to a problem? Please describe.** 
I would like to get all my drafts ordered first and then the published documents. Currently I am unable to order it using any custom method.
**Describe the solution you'd like** 
I would like to get all my drafts ordered first and then the published documents.
**Describe alternatives you've considered** 

**Additional context**

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread.
