### ISSUE TITLE
Long Array Not Editable 

### ISSUE THREAD

**Issue by wicka-aus** [sanity-io/sanity#3785]
Hi 

I pushed a long array of objects to a document via the API, yet I cant edit these values in Sanity. If I 'Add Item' via the studio I can edit it, but not the items I pushed to the API.

Example below of array object push to API.

`
                {
                    "_key": 3360,
                    "postcode": "3360",
                    "fee": 89
                },
`

Any ideas?
TIA

**Comment by rexxars** [comment]
If I were to hazard a guess, they `_key` should be a string - maybe try prefixing it with a `p` or similar? It may be that it now gets confused and tries to use the key as an array index when patching

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread.
