### ISSUE TITLE
Rule min in Array field incorrect work in 3.0.0-dev-preview.22

### ISSUE THREAD

**Issue by lotarbo** [sanity-io/sanity#3808]
**Describe the bug**

I have array field, with rule **Rule.required().min(2).max(5)** , and 2 items in array, and stiil validation error

**To Reproduce**

1. add array field with rule min(2)
2. add 2 items
3. see validation error

**Expected behavior**

no validation error

**Screenshots**
<img width="685" alt="image" src="https://user-images.githubusercontent.com/1766890/198266474-8ea77819-36b1-45fd-9906-ae64c75c3aa5.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/1766890/198266556-169a9e6c-193a-41f5-83bf-cdcdcdff6a53.png">

_edit:_ with 3 items problem too
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1766890/198267099-1e130d05-b7e1-447b-b38a-e5ec39aaf7f5.png">

**Which versions of Sanity are you using?**

3.0.0-dev-preview.22

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
