### ISSUE TITLE
[v3] can't delete invalid item in reference array

### ISSUE THREAD

**Issue by genox** [sanity-io/sanity#4072]
<img width="693" alt="Screenshot 2023-01-11 at 10 38 47" src="https://user-images.githubusercontent.com/5611407/211771259-b29326c8-2cda-493f-a1cf-ced3f1860acd.png">

I accidentally ended up with a wrong object in a reference array while developing. I should be able to delete it with the Remove button / context menu item, which is correctly shown and clickable. I press it, the UI confirms the action ("Saved"), but the invalid object is still there.

workaround: I have to set the references back to a type that is deemed valid in order to be able to delete it.

sanity version: 3.1.4

**Comment by alistairlcc** [comment]
i have the same issue

**Comment by okj579** [comment]
I've done some debugging to see if I can fix it. I don't understand the code well enough to know what it should be doing, but the problem is that the item path is set here:
https://github.com/sanity-io/sanity/blob/5abfeccd0e7d861c4a52eb7e6103d9b3cd710b11/packages/sanity/src/core/form/members/object/fields/ArrayOfObjectsField.tsx#L238

But then the entire path is prepended again here:
https://github.com/sanity-io/sanity/blob/5abfeccd0e7d861c4a52eb7e6103d9b3cd710b11/packages/sanity/src/core/form/members/object/fields/ArrayOfObjectsField.tsx#L93
https://github.com/sanity-io/sanity/blob/5abfeccd0e7d861c4a52eb7e6103d9b3cd710b11/packages/sanity/src/core/form/members/array/items/ArrayOfObjectsItem.tsx#L149

It then generates an unset mutation with an invalid path, for me for example: `navItems[_key=="54f79c4efc7c"].containers.navItems[_key=="54f79c4efc7c"].containers[_key=="c0d6c0041114"]` instead of 
`navItems[_key=="54f79c4efc7c"].containers[_key=="c0d6c0041114"]`

**Comment by binoy14** [comment]
Thanks @okj579 for debugging the issue!
