### ISSUE TITLE
[v3] Array length is `undefined` in previews

### ISSUE THREAD

**Issue by joshuabaker** [sanity-io/sanity#4078]
**Example**

```
  preview: {
    select: {
      count: "images.length",
    },
    prepare({ count }) {
      return {
        title: count, // Is always undefined
      };
    },
  },
```

_Sanity version: 3.2.0_

**Comment by phunanon** [comment]
I have the same issue. I have worked around it for now by selecting the whole collection and using `length` in JavaScript, but this is obviously unfavourable. `collection.length` also isn't mentioned in the [List Previews documentation](https://www.sanity.io/docs/previews-list-views).

**Comment by bjoerge** [comment]
This working in v2 was not by design, and in effect the v2 implementation was equivalent to selecting the whole collection and doing `.length` client side. We don't currently support GROQ in preview selections, but if we did, it would likely be `count(collection)`, not `collection.length`.

So the "fix" is to do it this way in v3:
```
preview: {
    select: {
      images: "images"
    },
    prepare({ images }) {
      return {
        title: images.length
      }
    }
  }
```

**Comment by eivindml** [comment]
`images.length` doesn't work for me. Selection in v3 returns the array as an Object with number based keys. 

So to get the count, do this instead: `Object.keys(images).length`
