### ISSUE TITLE
Uncaught error: process is not defined with update to 3.5.1

### ISSUE THREAD

**Issue by ritesh-kanchi** [sanity-io/sanity#4230]
Upon updating to Sanity 3.5.1, my Studio works perfectly locally - but after deploying it via `sanity deploy,` the following error is displayed:

```
Uncaught error: process is not defined
https://STUDIO.sanity.studio/static/desk-7d0f4bc4-4c87892e.js:53:4510
ReferenceError: process is not defined
    at https://STUDIO.sanity.studio/static/desk-7d0f4bc4-4c87892e.js:53:4510
```

Not sure what the problem here is, but it occurred after updating my Studio from 3.5.0 to 3.5.1.

![Screenshot](https://user-images.githubusercontent.com/29787649/222331655-ae140058-e810-41ef-98ea-79f9484fdb7a.png)

**Which versions of Sanity are you using?**
Sanity 3.5.1

**What operating system are you using?**
macOS Ventura 13.2.1

**Which versions of Node.js / npm are you running?**
npm 9.1.1
node v18.12.1

**Comment by rexxars** [comment]
Looks like this is an issue with certain versions of the styled-components dependency. In your `package.json` file, under `dependencies`, try and set `styled-components to `^5.3.8`, then reinstalling dependencies:

```
{
  // ...
  "dependencies": {
    // ...
    "styled-components": "^5.3.8"
  },
  // ...
}
```

**Comment by TobCar** [comment]
Hi! I'm encountering this bug on Sanity 3.8.2. 

Here's what I've attempted that did not fix the issue:

- Downgrading all Sanity packages to 3.5.0.
- Downgrading all Sanity packages to 3.5.1
- Bumping to newer versions of `styled-components`
- Downgrading `styled-components`
- Using `npm` instead of `yarn`
 
I deleted `node_modules` and `yarn.lock` in between each fix attempt.

Here is my current `package.json` that's experiencing the bug:

```
"scripts": {
    "start": "sanity start",
    "build": "sanity build",
    "dev": "sanity dev"
},
"dependencies": {
    "@sanity/dashboard": "^3.1.3",
    "eslint": "^8.6.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-is": "^18.2.0",
    "sanity": "^3.8.2",
    "sanity-plugin-dashboard-widget-netlify": "^2.0.1",
    "styled-components": "^5.3.8"
  },
"devDependencies": {
  "@sanity/cli": "^3.8.2",
  "@sanity/vision": "^3.8.2",
  "typescript": "^4.0.0"
},
```

Do you have any other ideas for how to fix this?
