### ISSUE TITLE
Validate field names in schema validator

### ISSUE THREAD

**Issue by simen** [sanity-io/sanity#434]
Someone did this:

```
{
    title: "Product Variant",
    name: "product-variant",
    type: "array",
    of: [
        { type: 'productVariant' }
    ]
}
```

Sanity does not like (i.e. support) dashes in field names. The schema validator should validate field names according to the rules of the backend.

**Comment by knupska** [comment]
I'm just giving Sanity a test at the moment (trying to wrap my head around it) and I also made this same silly mistake.

In my case I had entered:

```
{
  title: 'First Name',
  name: 'first-name',
  type: 'string'
},
{
  title: 'Middle Name',
  name: 'middle-name',
  type: 'string'
},
{
  title: 'Last Name',
  name: 'last-name',
  type: 'string'
},
```

Since Sanity kept working (albeit a bit broken), it took me a while to realise there was an error.

Luckily I was able to guess at what was likely causing it, but the message in the console was:

```
Uncaught ClientError: message "Expected '}' following object body"
```

**Comment by evenwestvang** [comment]
Thanks for letting us know! We’ve set aside a bunch of schema validation issues to do all at once. This one does seem a bit more pressing though and should perhaps be given priority.

**Comment by evenwestvang** [comment]
We should also check for other characters that can make their way into labels like spaces.
