### ISSUE TITLE
Items dissapear from Array fields, only when viewed via a tab, since upgrading to latest Sanity studio

### ISSUE THREAD

**Issue by toddpadwick** [sanity-io/sanity#4687]
A very weird bug here. I have upgraded to the latest sanity: + sanity@3.14.1
and now, my array fields lose some of the items, temporarily when viewing via a tab. When I open a modal, or create a new array item, the missing items appear behind again, but then re-dissapear when the modal is closed. When i view, via the 'all it
I have recorded a video to explain this better as its very strange, but really annoying.
I can confirm there is no custom publish actions or anything like that on this project. 

https://github.com/sanity-io/sanity/assets/36191462/2e355836-a06d-4bfc-acdb-9628dbb03f78

I have looked in the console, and can confirm they are missing from the dom, not just from view somehow. as you can see, there are only two nodes here, not four.
![Screenshot 2023-07-11 at 15 46 35](https://github.com/sanity-io/sanity/assets/36191462/f1ac0c31-94e4-47a0-acfe-fdf9e69bc32f)

**Comment by bibby** [comment]
I've found that the missing items will *appear* if you are able to coerce a vertical scroll event. This might unblock someone in a pinch.

**Comment by bibby** [comment]
The described behavior begins in version [3.9.0](https://github.com/sanity-io/sanity/releases/tag/v3.9.0) with the introduction of "virtualized lists".

**Comment by wellermiranda** [comment]
Same problem here 😢

**Comment by binoy14** [comment]
Hey all, sorry for the inconvenience! Could @toddpadwick or someone else confirm if this is fixed in the latest version of studio which is`3.18.0`

**Comment by thobas-dnvgl** [comment]
@binoy14 Not completely unfortunately. I am using 3.18.1 in this video:

https://github.com/sanity-io/sanity/assets/66472571/8fb83d21-8ebe-49b1-9226-c111691eaa0e

In the video I go to the "Variants" group, showing an array of variants. It has 3 as expected (it used to have only 2 until I resized the window because of this very bug). However if I dive deeper into a variant and then go to the "Price plans" group, the bug is still there. Only 2 plans are displayed until I trigger a re-render one way or another.
