### ISSUE TITLE
Comments API CORS Error After update

### ISSUE THREAD

**Issue by stevenprinsloo** [sanity-io/sanity#5697]
After updating Sanity Studio to `3.28.0` I am getting a CORS error.

The error is happening in my local enviromnet for an API call being made to `https://pyrmmpch.apicdn.sanity.io/v2023-11-13/data/query/upsell-public-production...`.

My CORS settings are correct on the Sanity, with http://localhost:3000/ being added as a allowed origin.

It appears to be related from the comments API.

**Expected behavior**

No CORS errors as my local dev url (`localhost:3000`) has been added as an allowed origin.

**Screenshots**

![image](https://github.com/sanity-io/sanity/assets/23172449/075ae0f9-63dc-4fe9-bd06-31397e6ecf55)

**Which versions of Sanity are you using?**

`3.28.0`

**What operating system are you using?**

`Ubuntu 23.04 | Linux`

**Which versions of Node.js / npm are you running?**

`v20.11.0`

**Comment by th-km** [comment]
I'm experiencing the same problem with the latest update to Sanity `^3.28.0`. My CORS settings are correct, but there may be unresolved comments from a live demo I did with a client. As the project is now on a free plan while in staging, I suspect that the warnings are because Sanity Studio is trying to access something we no longer have access to?
