### ISSUE TITLE
Problem with document actions in v3.33.0

### ISSUE THREAD

**Issue by WebShapedBiz** [sanity-io/sanity#5991]
**Describe the bug**

After upgrading my Studio to v3.33.0 my custom document action, placed inside the document actions menu is now overriding my Publish button. What you see in the screenshot is my custom document action to trigger a Cloudflare deployment of my SSG website. Fortunately, I haven't deployed it yet so you can see how it works on the "old" v3.32.0 version on sanity.studio domain.

**Screenshots**

v3.33.0 on localhost:
![Slika zaslona s 2024-03-13 16-28-56](https://github.com/sanity-io/sanity/assets/6765137/5c6e42f7-c9d4-49f1-8456-7435e2ea77cf)

v3.32.0 on sanity.studio domain:

![Slika zaslona s 2024-03-13 16-34-17](https://github.com/sanity-io/sanity/assets/6765137/86538a25-5436-422e-8a29-a08814d5003f)

I've seen that you changed Document actions bits in the latest release but your docs are showing that the "Document actions" page was last updated on 13th February.

Thank you for your help.

EDIT:
I used this as the way to do custom action:
https://www.sanity.io/schemas/hacking-custom-document-actions-6fb9f258

**Comment by pedrobonamin** [comment]
Hi @WebShapedBiz 
We have introduced a new action which is added at the start of the actions array.
When the actions array is processed, you are inserting elements at an specific position by doing the following, which assumes that the first action is the publish.

```
  actions: (prev, context) => {
      prev.splice(1, 0, CustomAction);
      prev.splice(2, 0, Divider);
      return prev;
    },

```

Quick fix will be to update the splice function to insert from position 2 instead of 1. 

So it will be:

```
  actions: (prev, context) => {
      prev.splice(2, 0, CustomAction);
      prev.splice(3, 0, Divider);
      return prev;
    }
```

We will look into fixing it so the publish action to the first position, will let you know here once the fix is introduced.

Thanks for reporting! 

Let us know if theres some other way we can help you.

**Comment by WebShapedBiz** [comment]
Both versions worked @pedrobonamin, pre and post-editing :-)
Thank you for your time and effort, you've been very helpful.

Cheers.
