### ISSUE TITLE
Prepare data in schema orderings?

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#624]
It would be handy if we could order documents based on manipulation/calculations from various field data. This could work similarly to the `prepare()` function in preview.

Example where the prepare-function would return a accumulated number from an array field.

```
orderings: [
  {
    title: 'Most visited',
    name: 'mostVisited',
	  by: [
		{
		  direction: 'desc',
		  select: {
			field: 'pageStats',
		  },
		  prepare({ pageStats = [] }) {
			return pageStats.reduce((acc, { pageLoads }) => pageLoads + acc, 0)
		  } 
		}
	  ]
	}
  ]
```

**Comment by bjoerge** [comment]
Super useful, but I'm afraid that's not something we can support easily at the moment as the `prepare` function will have to be run browser side. In order to support this, we will need both the ability to specify GROQ queries in sort config and support for aggregate functions like you describe in #623.

**Comment by jaredshaunsmith** [comment]
@rexxars curious if there was a solve for this, or did it just get closed due to inactivity? I would also very much like the same functionality (or some way to custom sort after preparing data)
