### ISSUE TITLE
Total attribute/datatype count 4002 exceeds limit of 4000'

### ISSUE THREAD

**Issue by sanjay-20896** [sanity-io/sanity#6453]
We are currently on a legacy plan. We have reached the content attribute limit to 4k. We have been building a multilanguage commerce website content. Could you please suggest us certain steps

Does removing unnecessary schemas help in reducing attribute values

Legacy plan for smaller teams or agencies with pay-as-you-go for higher usage.
$99

![Screenshot 2024-04-23 at 4 06 40 PM](https://uploads.linear.app/ab8cdfe4-f7af-4de6-9d57-3cdb72dc9155/55fccf80-e6fc-4b27-91b6-65e1a4f6c194/d8e8696f-059f-4beb-bebd-f2fff661f676?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FiOGNkZmU0LWY3YWYtNGRlNi05ZDU3LTNjZGI3MmRjOTE1NS81NWZjY2Y4MC1lNmZjLTRiMjctOTFiNi02NWUxYTRmNmMxOTQvZDhlODY5NmYtMDU5Zi00YmViLWJlYmQtZjJmZmY2NjFmNjc2IiwiaWF0IjoxNzEzOTYxOTI2LCJleHAiOjMzMjg0NTIxOTI2fQ.AIfcV_1C61f-tXTjwI56nigSl3QC_YwCigNfEo74MVs "=848x")

**Comment by cngonzalez** [comment]
Hello @sanjay-20896 ! Yes, it looks like you have reached the attribute limit for your particular plan. 

@largis21 's link also has strategies for reducing it. Since this is not a bug or issue with studio, I'm going to close your comment. If you have further questions (that are not bugs) please do feel free to check out our community's Slack: https://slack.sanity.io/
