### ISSUE TITLE
Typegen: Can't generate types with conditional values in slice and ordering operations even when the it doesn't effect the type.

### ISSUE THREAD

**Issue by filipjohnsen** [sanity-io/sanity#6678]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Not sure if this is a bug or intended feature. 
Can't generate types with conditional values in slice and ordering operations even when the it doesn't effect the type.

The example below will result in a `Unsupported expression type: ConditionalExpression` error
```js
const start = 0
const limit = start + 12

const order = orderBy == "desc" ? "| order(_createdAt desc)" : "| order(_createdAt asc)"
const slice = `[${start}...${limit}]`

groq`*[_type == "document"]${order}${slice}`
```

Is there a reason why the type generator should include the slicing and/or ordering as part of the type generation?

**To Reproduce**

Clone [https://github.com/filipjohnsen/sanity-conditional-query](https://github.com/filipjohnsen/sanity-conditional-query/) this repo if you want to test it yourself

**Expected behavior**

Discard slicing and ordering of query in type generation

I have made a hacky workaround where I add a `GROQ comment` to the query and then find and replace the query at runtime

```js
export function addConditionalFilterToQuery(query: string, filter: string) {
  return query.replace("//CONDITIONAL_FILTER", filter);
}
```

**Which versions of Sanity are you using?**

@sanity/cli (global)                   3.42.0 (up to date)
@sanity/document-internationalization   3.0.0 (up to date)
@sanity/language-filter                 4.0.2 (up to date)
@sanity/preview-url-secret             1.6.12 (latest: 1.6.13)
@sanity/vision                         3.41.1 (latest: 3.42.0)
sanity                                 3.42.0 (up to date)

**What operating system are you using?**

MacOS 14.4.1

**Which versions of Node.js / npm are you running?**

Node v18.18.0

**Comment by sgulseth** [comment]
Hi!

This is not a bug in typegen per se, but rather how we discover queries. Since your query references a variable that contains a conditional expression we are unable to determine it. We would need to create a matrix of different query node types, with your example it would be "easy" since both would be the same, but we would also need to handle cases where they weren't

I think in your case however, this should work:

```
const start = 0
const limit = start + 12

const order = `| order(_createdAt ${orderBy})`
const slice = `[${start}...${limit}]`

groq`*[_type == "document"]${order}${slice}`
```

**Comment by filipjohnsen** [comment]
Thanks for the response and the explanation, partly fixed the problem!

Ran into a different problem where TypeGen threw a `BinaryExpression` error, fixed it by first declaring the variable with a static value and then mutating it with the dynamic values. 

```js
let start = page;
start = (page - 1) * POST_PER_PAGE;

let limit = POST_PER_PAGE;
limit = POST_PER_PAGE + start;
```

Not sure if this is the intended behaviour or not, could be useful to have some docs around the various errors 😃  Completely understand that TypeGen is experimental feature, been really enjoying it so far!

**Comment by sgulseth** [comment]
No problem at all! 

You are running into a similar problem, but with a different expression. It's not typegen, but how we utilize babel to traverse your code and piece together the different javascript expressions. I _think_ we could add support for binary expressions as long as both sides resolves to a literal value. However, I don't think this is the case for you here? I assume you're using this to paginate? You could instead of using javascript parameter use groq parameters? https://www.sanity.io/docs/groq-parameters#

We also have a guide for doing more efficient pagination [here](https://www.sanity.io/docs/paginating-with-groq), but it depends on your use case 🙂
