### ISSUE TITLE
Type generation incompatible with Astro

### ISSUE THREAD

**Issue by ivyrze** [sanity-io/sanity#6965]
**Describe the bug**

I'm trying to use GROQ typegen in my Astro project, but it doesn't recognize the JSX-in-frontmatter syntax and mistakenly thinks its all errors, for example:

```
src/pages/about.astro: `import` can only be used in `import()` or `import.meta`. (2:0)

  1 | ---
> 2 | import Layout from '../layouts/BlogPost.astro';
```

Using the same code in a standard JSX format produces expected results.

**To Reproduce**

1. Follow [Astro + Sanity getting started guide](https://www.sanity.io/guides/sanity-astro-blog).
2. Create `sanity-typegen.json` to include `.astro` files in the `path` search glob.
3. Run `sanity schema extract && sanity typegen generate`.

**Expected behavior**

The types should generate without error.

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

```
@sanity/cli (global)  3.46.1 (up to date)
@sanity/astro          3.1.3 (up to date)
@sanity/image-url      1.0.2 (up to date)
@sanity/types         3.46.1 (up to date)
@sanity/vision        3.46.1 (up to date)
sanity                3.46.1 (up to date)
```

**What operating system are you using?**

macOS 14.5

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

```
10.2.4
v18.19.1
```

**Comment by AdamGEmerson** [comment]
Any ideas where to start on this one?  I'd like to see this working and am happy to help where I can.

**Comment by sgulseth** [comment]
Hi! Sorry for this taking some time. The challenge here is that we are using babel to parse source files, but astro isn't supported by babel or any plugin afaik. 
I _think_, without having looked very much into it yet, we would have to intercept `.astro` files and parse them with the [astro-compiler](https://github.com/withastro/compiler). Then we should be able to have a typescript version which we could use to pick up the queries.

**Comment by rusbers** [comment]
Hi there! Is there any progress on this issue?

A straighforward workaround I’ve found so far is to define the GROQ queries in a separate .ts file instead of directly inside the .astro file. After that, I run `npx sanity typegen generate` to ensure the types are generated. Finally, In the .astro frontmatter, I manually infer the type for the query result. 

**sanityQueries.ts:**
```typescript
import { defineQuery } from "groq";
export const heroSectionQuery = defineQuery(`*[_type == "heroSection"][0]`);
```

**hero.astro:**
```astro
---
import { loadQuery } from "@/lib/loadQuery"
import { heroSectionQuery } from "@/lib/sanityQueries"
import { type HeroSectionQueryResult } from "@/lib/sanity.types"

const { data } = await loadQuery<HeroSectionQueryResult>({ query: heroSectionQuery })
---
```

**Why This Works:**

- Moving the queries into a .ts file allows sanity typegen to pick up and process the GROQ queries.
- Using a generic type argument for the loadQuery function ensures TypeScript knows the exact structure of the data.
- The HeroSection type is imported from the generated sanity.types.ts file, ensuring type safety.

While this workaround works for now, it would be great to see native support for detecting and type-generating queries directly inside .astro files.

**Comment by sgulseth** [comment]
Hi! Took some time because of the holidays, but this is now released in the [latest version](https://github.com/sanity-io/sanity/releases/tag/v3.69.0)

**Comment by aldo-roman** [comment]
For anyone wondering why does didn't work, the `.astro` files are now processable, but not read by default.

Create `sanity-typegen.json`

```json
{
  "path": "src/**/*.{ts,astro}",
}

```
