### ISSUE TITLE
Facing type error in sanity package while running yarn build

### ISSUE THREAD

**Issue by jawadaligohar** [sanity-io/sanity#7153]
![WhatsApp Image 2024-07-15 at 05 34 47_5a674ac6](https://github.com/user-attachments/assets/a5f08e8a-8596-4e7e-b7aa-c918185f4bb3)

When i do yarn build it gives me this error in the sanity package. The project was working fine and suddenly it started giving this error,

I have also tried updating the package but all the versions are giving this error.

My tech stack:
Next.js + Typescript

**Comment by RitaDias** [comment]
👋 @jawadaligohar can you clarify what version you're running? 

I know you mentioned all versions but if changing versions doesn't make a difference I'm wondering if it could be anything in your project config. When creating a new sanity project does this happen?

When did the error start? :)

**Comment by jawadaligohar** [comment]
I have just updated my sanity package to 3.50.0. The error started two days ago suddenly. I can give you my config files if you want to look at them, just let me know which code do you need?

**Comment by jawadaligohar** [comment]
@RitaDias  
I have just updated my sanity package to 3.50.0. The error started two days ago suddenly. I can give you my config files if you want to look at them, just let me know which code do you need?

**Comment by RitaDias** [comment]
That would be useful @jawadaligohar thank you :)

**Comment by ricokahler** [comment]
Looking at the build error being related to typescript, this issue may be more related to typescript rather than yarn. it seems like your typescript compiler does not understand the newer ts syntax we use to provide more help typings. I suggest updating your project's version of typescript, deleting your lockfile, and trying the build again. You can also add the compiler option, skipLibCheck.

Closing this one to clean up our triage queue. If this is still an issue for you please do reach out and we'll open this back up!
