### ISSUE TITLE
Schedule date picker - month shows the minutes value!

### ISSUE THREAD

**Issue by haider-evident** [sanity-io/sanity#7249]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

**To Reproduce**

1. Go to a page
2. Click on "Schedule"
3. Change the minutes in the time picker
4. See how the month of the date is using the value of the minute 

**Expected behavior**

The month in the date format should show the month, not the minutes!

**Screenshots**
<img width="624" alt="Screenshot 2024-07-25 at 21 17 51" src="https://github.com/user-attachments/assets/ce6b3ba0-76a8-43b9-969b-c1f0a982baa0">

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.52.2 (up to date)
@sanity/dashboard      3.1.6 (latest: 4.0.0)
@sanity/demo           1.0.2 (latest: 2.0.0)
@sanity/image-url      1.0.2 (up to date)
@sanity/table          1.1.2 (up to date)
@sanity/types         3.49.0 (latest: 3.52.2)
@sanity/ui             2.8.8 (up to date)
@sanity/vision        3.20.2 (latest: 3.52.2)
sanity                3.52.2 (up to date)

**What operating system are you using?**
MAC OS

**Which versions of Node.js / npm are you running?**

10.2.4
v20.11.1

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by ricokahler** [comment]
Hi there!

Thank you for reporting this issue however I am having trouble reproducing it.

Do you think this issue may be caused by a misconfiguration of the option [`inputDateTimeFormat `](https://github.com/sanity-io/sanity/tree/cec7b12249633f887a6bc84101a78538506b052d/packages/sanity/src/core/scheduledPublishing#customize-input-date-formatting) on your end?

We have a [default configuration](https://github.com/sanity-io/sanity/blob/cec7b12249633f887a6bc84101a78538506b052d/packages/sanity/src/core/scheduledPublishing/constants.tsx#L88) for this value which seems to be correct as `dd/MM/yyyy HH:mm`  where `MM` denotes the correct notation for month as specified by [the date-fns docs](https://date-fns.org/docs/format).

Let me know if that's not the case and we can reopen this one!
