### ISSUE TITLE
Ability to sequence documents

### ISSUE THREAD

**Issue by agolden** [sanity-io/sanity#732]
Feature request: Provide the ability to sequence documents (e.g., through drag-and-drop in Sanity Studio).  Provide the sequence as a parameter on the document (e.g. '_order').

This would allow non-technical users to quickly and easily set an order of items without having to manually set (and maintain) an additional order field within each document.

**Comment by evenwestvang** [comment]
This is one of the tasks that are next in line on the [roadmap](https://www.sanity.io/docs/misc/roadmap). We need for people to easily add documents to ordered collections such as lists and hierarchies. We're thinking though that this should be a separate structure so that documents can be part of multiple sets.

**Comment by peterbartels** [comment]
Any progress on this? The link to the roadmap is not working anymore.

**Comment by evenwestvang** [comment]
We think so too – both list and hierarchical ordering are definitely on our medium term list of editing improvements.

**Comment by AryanJ-NYC** [comment]
For those that stumble upon this looking for a quick workaround that allows non-technical users to set the order of documents: add a priority:

```javascript
// sanity/schema.js
{
  name: 'priority',
  title: 'Priority',
  type: 'number',
  validation: (Rule: any) => Rule.min(0).integer().positive(),
},
```

in any document.

**Comment by abdulrauf11** [comment]
Desperately need this functionality as so many clients ask for it :(

**Comment by mellson** [comment]
I also have a client asking for this, since we moved away from Umbraco which have it 😊

**Comment by Jfree64** [comment]
I, too, would be interested in this feature. Any word on this?

**Comment by jdrever** [comment]
This would be really useful - again, I am used to this functionality from Umbraco.  Thanks!

**Comment by BretCameron** [comment]
I also have a client who would like this.

**Comment by LorenzoDossi** [comment]
pls I need it too

**Comment by nboliver** [comment]
+1

**Comment by BretCameron** [comment]
I pulled together an MVP plugin for ordering documents in Sanity: [sanity-plugin-order-documents](https://www.npmjs.com/package/sanity-plugin-order-documents).

I'd welcome any feedback or contributions.

**Comment by mornir** [comment]
@BretCameron Really Nice! Thank you!
In my case, it does the job until a native solution is implemented, which I hope the Sanity team will do soon now that they're done with Presence and Review Changes. Time for less exciting, but important features like this one and creating new document directly in reference selector. 😉

But I know that such features are not easy to implement UI/UX wise.

In Craft CMS, for example, there are three document types:
- channels (normal Sanity document)
- singles (can be achieved with Sanity Structure builder)
- structures (manually sortable documents)

As @evenwestvang mentioned, I also think that a separate structure makes more sense for Sanity (like this plugin does), instead of adding a new document type.

**Comment by ryanbagwell** [comment]
lifesaver

**Comment by j2is** [comment]
While Bret's plugin is a nice workaround it still desperately needs to be native in Sanity. Just like we have ordering in the array type. You can't easily:

- sort by manual order in the desk
- drag the 500th document to the beginning
- see the status of a document while you are rearranging eg. a "isLive" boolean for a document to toggle the frontend visibility, not reflected in the plugin view only the desk
- load documents to rearrange on scroll you have to click "load more". If you rearrange on a regular basis you have to click this many times it's not nice

**Comment by shajidhasan** [comment]
Still waiting on this.

**Comment by j2is** [comment]
Is this in the pipeline? :)

**Comment by abdulrauf11** [comment]
This plugin looks pretty good and should do the job, in my opinion:

https://www.sanity.io/plugins/orderable-document-list

**Comment by SimeonGriggs** [comment]
Closing as [Orderable Document List](https://www.sanity.io/plugins/orderable-document-list) solves this with drag-and-drop from inside the Desk Structure.
