### ISSUE TITLE
Feature request: Add Facebook to list of default auth Providers

### ISSUE THREAD

**Issue by ryami333** [sanity-io/sanity#739]
Hey there, I really love Sanity and it has become my default go-to for new CMS projects. However, I'm having trouble selling it to clients who are not particularly savvy and do not have Github accounts (or a Google account). Would it be possible to add a generic auth Provider like Facebook's? This would make it much easier to sell Sanity to my clients :+1:

**Comment by skogsmaskin** [comment]
Hi @ryami333, thank you for your report! I do see that Facebook would be a great option to let  clients log in with, but it also bring some complexity to the table. Users don't only log into the studio, but also into Sanity globally in order to manage different projects, invite users to a project etc. In manage.sanity.io you log in with a Sanity global user, and in the Studio you log in with a project user. Both global and project users are created from the the provider you logged in with when creating a project or accepting an invitation to a project.

If we were to support Facebook, users must also be able to log into manage.sanity.io with their Facebook user (in order to manage their account and projects connected to that user). We are, as for now, not willing to add this complexity out of the box. We will however consider this next time we iterate on the login aspects of our service.

That said, we do however have an enterprise feature where we allow third party logins into a project, in which you could support any form of login. These users are only limited to the studio and project itself, and got nothing to do with the global Sanity users. You can create fine grade access control for what they should be able to do within your project as well. These users a typically users which is only going to write and edit your data, but not manage the project, invite users etc.

You can read more about this feature here:

https://www.sanity.io/docs/third-party-login

A reference implementation of such a login server could be found here:

https://github.com/sanity-io/3rd-party-auth-example

**Comment by skogsmaskin** [comment]
(Keeping this issue open so we can get back to it later, and others could come with input on this as well)
