### ISSUE TITLE
Slow input keystroke lag in Studio

### ISSUE THREAD

**Issue by eldoy** [sanity-io/sanity#7456]
**Describe the bug**

Every keystroke is slow and laggy in Sanity Studio. I'm quite a fast typist, and this totally makes the user experience terrible. It seems like every keystroke is synced to the cloud?

**To Reproduce**

Type fast in any text input field and it lags.

**Expected behavior**

Absolutely no lag.

**Which versions of Sanity are you using?**

@sanity/cli (global)          3.56.0 (up to date)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/vision                3.56.0 (up to date)
sanity                        3.56.0 (up to date)

**What operating system are you using?**

Darwin v2.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64

**Which versions of Node.js / npm are you running?**

10.8.2
v20.17.0

**Comment by FancyJeff** [comment]
Experiencing this also, this issue is particularly bad when interacting with an object nested within the portable text editor.

**Comment by thomasm** [comment]
Same here. The keystroke lag is very noticeable, especially when typing in text fields within items in my page builder array.

**Comment by jordanl17** [comment]
Hi, @eldoy - thanks for highlighting this issue.

Are you experiencing this only when running the studio locally, or also on a deployed studio?

**Comment by eldoy** [comment]
@jordanl17 It's just as bad for both. Keep holding backspace and it's even more evident. I'm having a hard time recommending Sanity to my clients when such a basic annoyance exists. Are you not seeing it?

**Comment by jordanl17** [comment]
> @jordanl17 It's just as bad for both. Keep holding backspace and it's even more evident. I'm having a hard time recommending Sanity to my clients when such a basic annoyance exists. Are you not seeing it?

@eldoy apologies you are experience such poor performance. We are aware of some rendering issues and are continually trying to work through these. We have some high priority improvements in the works right now, which it looks like will directly help mitigate the issues you've encountered. These should be released shortly in the coming week/s. Please ensure you are always on the latest studio to capture these improvements when they drop. 

[We recently released v3.37.0 which includes an upto x10 speed improvement](https://github.com/sanity-io/sanity/releases/tag/v3.57.0) although this change only affects when running in dev mode. For prod slowness, our team are actively pursuing improvements. Apologies again for the frustrating experience you've seen- hopefully the fixes will rectify this for you.

**Comment by runeb** [comment]
@eldoy @FancyJeff @thomasm As Jordan said; sorry that you are experiencing this and we are currently working on improvements which specifically target increased typing performance. We have other reports that echo your findings, that in certain Studios there can be very noticeable lag when typing quickly or holding backspace.

Would you mind letting us know whether you have any plugins installed in your Studio? If so, which are they and are they custom input components? Are they also used/registered for fields within portable text?

**Comment by eldoy** [comment]
@runeb It's a very basic studio based on your templates with zero plugins.

**Comment by FancyJeff** [comment]
> @eldoy @FancyJeff @thomasm As Jordan said; sorry that you are experiencing this and we are currently working on improvements which specifically target increased typing performance. We have other reports that echo your findings, that in certain Studios there can be very noticeable lag when typing quickly or holding backspace.
> 
> Would you mind letting us know whether you have any plugins installed in your Studio? If so, which are they and are they custom input components? Are they also used/registered for fields within portable text?

Happens in both deployed and local studios for me. I have the presentation, media and assist plugins enabled. All of the inputs are out of the box sanity inputs.

The issue outside of portable text is slow but objects within the portable text its almost unusable to the point I am waiting for the text to catch up to me.

**Comment by runeb** [comment]
@eldoy @FancyJeff Thanks for confirming! If you are blocked on this peformance regression, downgrading to `3.50.0` should improve performance for you while we work on fixing this issue

**Comment by runeb** [comment]
@eldoy @thomasm @FancyJeff  Please see https://github.com/sanity-io/sanity/releases/tag/v3.57.1 for a version that addresses this

**Comment by FancyJeff** [comment]
> @eldoy @thomasm @FancyJeff Please see https://github.com/sanity-io/sanity/releases/tag/v3.57.1 for a version that addresses this

Thanks, this has definitely improved the input speed a bunch. I am still seeing some (much less) lag of an string input inside an object in a portable text. Might be worth including this in the bench marking.

Also to note its much worse in firefox than it is in chrome so for people who have this issue make sure you are using chrome.

Thanks for the quick release :)

**Comment by runeb** [comment]
@FancyJeff Thanks for confirming! And yes, there are still performance challenges to tackle and that work continues

**Comment by josh-padnick** [comment]
This comment from @FancyJeff exactly matches our experience:

> Thanks, this has definitely improved the input speed a bunch. I am still seeing some (much less) lag of an string input inside an object in a portable text.

In fact, making a trivial string edit takes a full 3 seconds to finish saving and propagating to the page, and I'm on a MacBook M1 Pro.

Just to highlight the criticality here, we were starting to question our choice of CMS given this editing experience and wondering why there weren't more complaints online. We assumed the UX would be real-time editing where as you type, you see the updates instantly, so the multi-second delay is pretty jarring.

Thanks for taking this seriously. ('cc @panzacoder)

**Comment by eldoy** [comment]
Tried the 3.57.1 update, didn't see any difference... Still border-line unusable. I mean, if there's anything at all you should fix, it would be this. Editing, the core of your product, is basically broken imho.

I would be fine with an option to disable the sync while typing, I just don't want to be annoyed by this when I'm in the process of creating content.

**Comment by thomasm** [comment]
> @eldoy @thomasm @FancyJeff Please see https://github.com/sanity-io/sanity/releases/tag/v3.57.1 for a version that addresses this

Thank you for looking into it. It seems to have improved slightly now for me at least. There's still a small delay with each keystroke, but it's now manageable to write and delete text in the fields without too much frustration. :)

**Comment by panzacoder** [comment]
Pulled iin the `3.57.1` update and has improved the local dev experience significantly. I think there is improvement to be made still but this has made it much more workable.

Additionally we did some testing of our prod studio (we are still very much in development, so this hadn't been used yet) and the experience was fine even without the update. 

Will keep an eye on the performance and report back if we experience issues again or identify specific pain points.

CC: @josh-padnick

**Comment by runeb** [comment]
@josh-padnick @eldoy Sorry to hear you are still having latency issues!

I want to clarify that our recent release and my comments above address poor responsiveness of the form fields themselves, meaning lag from typing till seeing your typed characters in the field. This is unrelated to live preview of a website.

The live preview feature is called visual editing and there is a separate latency involved from editing content and till seeing it in the website preview.

If you are still having issues with the first scenario - laggy field inputs - then this is the best thread to provide more information. A Loom or reproduction description on latest version would be very helpful.

For the second scenario, I suggest that the https://github.com/sanity-io/visual-editing repository is a great place to discuss any latency issues regarding the website preview feature.

**Comment by HarunIO5** [comment]
Hi, I am having this slow input lag in my dev studio, I have tried sanity@3.57.1 and @3.60.0, it didn't help at all. I have used Sanity for a previous client recently and it worked fine, but now it's totally unusable.

**Comment by eldoy** [comment]
@runeb Are you not seeing the issue though? It's obviously not just me, just type in any field and it's laggy, should be visible immediately. As long as I'm paying for this product, I'm not spending time recording a video, I'll just use another CMS instead.

**Comment by HumidBrains** [comment]
How come this issue is closed when it never got solved? My problem is the same as described by others and in fact, this problem has existed now for at least a year.  We are building a commercial product on top of Sanity, but if the most basic core functionality (inputting and editing text) doesn't work, we're not able to launch. @runeb your many tries to fix this have not been very successful so far, what do you suggest your users/customers do meanwhile your team is (hopefully) working on a solution?

**Comment by lukepearce** [comment]
I'm also experiencing this painful UX running a very basic studio inside a Next.js app. I can see it's due to the client sending a network request on every keystroke.

**Comment by eldoy** [comment]
@runeb @jordanl17 Since you won't even do testing yourself, here's your video proof:

https://github.com/user-attachments/assets/bc19fd59-aa0b-4f1f-b60b-619d1249e533

Now please fix this. My customers are going to sue me if I deliver what you have right now.

**Comment by HumidBrains** [comment]
@eldoy it is very odd such a core issue isn't getting any attention, but if you get any response that isn't published here, please let me know. For sure customers can never accept such a poor UX. However, since there isn't that much noise around this issue as it deserves, I wonder if there is a remedy we haven't gotten aware of. @runeb @jordanl17 If there is any work done on this, it would be very helpful to know.

**Comment by eldoy** [comment]
@HumidBrains Sanity is generally too complex for them to handle, there's bugs all over which they don't have time to fix. I think this issue is a network issue regarding their content lake, and maybe not just a studio issue, it's generally just about usable about 50% of the time.

**Comment by dklanac** [comment]
Confirming that this issue is still present in localhost on v3.76.3.

**Comment by piscopancer** [comment]
Reopen this issue, input still lag

**Comment by kmelve** [comment]
Reopening this. The auto-lock was a poor end to a thread where people were still experiencing problems.

**Where we are now**

We've shipped several performance improvements since this thread went quiet:

- **React Compiler adoption**: We've been shipping React Compiler-optimized code on npm for close to a year. Internal benchmarks show 20-30% improvement in editing frame rates. Technical deep-dive: [React Conf talk](https://www.youtube.com/watch?v=zyVRg2QR6LA&t=9518s)

- **styled-components fork**: We identified styled-components as a major bottleneck. The library never implemented React 18's `useInsertionEffect`, causing styles to inject during render instead of between render and layout. We forked it, fixed it, and open-sourced it. Linear tested our fork and saw up to 40% faster initial component rendering. Details: [Blog post](https://www.sanity.io/blog/cut-styled-components-into-pieces-this-is-our-last-resort) / [Repo](https://github.com/sanity-io/styled-components-last-resort)

- **React 19.2 baseline**: Sanity v5 now requires React 19.2, which unblocks further optimization work including our migration to vanilla-extract. Details: [Blog post](https://www.sanity.io/blog/sanity-studio-v5)

**What we know from this thread**

The worst cases seem to involve:
- Dev mode (profiling/instrumentation adds overhead, but it still needs to be usable)
- Nested objects inside portable text
- Modal contexts
- Larger/more complex schemas

**If you're still experiencing lag on the latest version**

Please comment with:
1. Sanity version (`npm list sanity`)
2. Dev mode or production build?
3. Schema complexity (simple, moderate, page-builder-style nesting)
4. Plugins installed
5. Browser and machine specs

We want to nail down what's triggering the worst cases.

**Comment by annez** [comment]
@eldoy is this something you can test with the latest versions? We want to help with this as much as possible
