### ISSUE TITLE
Score function not behaving as expected when using Sanity Client, vision, or sanity-cli

### ISSUE THREAD

**Issue by matt-koevort** [sanity-io/sanity#7496]
**Describe the bug**

I'm running into an issue where I am frequently getting the following error:
```
score() function received unexpected expression
```
When using the score function. 

As mentioned in the title, this error occurs in Sanity Studio Vision, the Sanity CLI using `sanity documents query`, as well as the Sanity Client in `@sanity/client` (obviously being the biggest issue).

What's interesting, is that `groq-js` evaluate produces correct results without errors.

Additionally, I would expect that running score against a regular array (not a document filter) should work. The following query:
```
[{ "title": "hello" }] | score(title match "hello")
```
produces the error
```
score() function cannot be used in its current position
```
(again, this works using groq-js)

**To Reproduce**

There are a number of combinations in which I have found this to be the case:
1. When the value of the field being matched is `null` or an empty string:
```
*[]{
  "title": null,
  _score,
} | score(title match "hello")
```

2. When the result doesn't match at all
```
*[]{
  "title": "no match",
  _score,
} | score(title match "hello")
```

3. When there is a match, but the `_score` field is excluded from the projection.
```
*[]{
  "title": "hello",
} | score(title match "hello")
```

**Expected behavior**

The score function should not be erroring with simple, valid expressions passed to it.

**Screenshots**

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.56.0 (latest: 3.57.2)
@sanity/assist                 3.0.6 (up to date)
@sanity/dashboard              3.1.6 (latest: 4.0.0)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/vision                3.56.0 (latest: 3.57.2)
sanity                        3.56.0 (latest: 3.57.2)
```

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

```
10.7.0
v20.14.0
```

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by atombender** [comment]
Hi! This is actually by design and explained somewhat in the [documentation](https://www.sanity.io/docs/groq-functions#4798b2cba8df):

> score() cannot take a complex expression, including the use of functions (besides boost()), dereferencing, or subqueries.

In your case you are trying to score using an attribute which isn't on the document being filtered/sorted. Only expressions on attributes that are on the document can be scored. I agree that it would be nice to score on other expressions, but we have decided not to do this at this time.

groq-js intentionally does not implement proper scoring. Scoring requires a full-text indexing implementation that implements the same scoring algorithm we provide on the backend, and we have so far chosen not to implement this. It's not necessarily difficult, but it would be hard or impossible to keep in perfect sync with the backend's scoring system.
