### ISSUE TITLE
Potential issues with asset field identification

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#869]
According to this method
https://github.com/sanity-io/sanity/blob/32e8383cdea0e851b1376c627075a3bc6155e0ea/packages/%40sanity/export/src/AssetHandler.js#L181-L183

we identify fields with assets as a field that has a field named `asset` that is a reference. This could potentially cause breakage, e.g. if someone adds a reference to something that's not an asset, and names the field `asset` (I assume that would be a rare case, but still). Would it be better to lookup the referenced document and assert that it's of either of our asset types? (`sanity.imageAsset`/`sanity.fileAsset`)?

Another potential issue with this is also that the name of the field is by convention, and nothing prevents you from creating a custom data type that has a reference to `sanity.fileAsset` on a field named something else. This will currently not be treated as an asset under export.

In theory, the field could be named anything and nothing prevents you from defining a type like this:

```js
{
  name: 'somefile',
  type: 'reference',
  to: {type: 'sanity.fileAsset'}
}
```

As far as I understand this will not be exported as an asset as it is now.

**Comment by rexxars** [comment]
> Would it be better to lookup the referenced document and assert that it's of either of our asset types?

That would (potentially) require quite a lot more queries to run the export and would certainly slow down the export significantly since it would have to check every single reference.

> Another potential issue with this is also that the name of the field is by convention, and nothing prevents you from creating a custom data type that has a reference to sanity.fileAsset on a field named something else. This will currently not be treated as an asset under export.

Partly true. The asset will still be exported and will still work unless the asset is modified locally (which would change the asset ID). The `--no-assets` flag will not be respected, however.

The streaming nature of the exporter makes a bunch of these things harder than it needs to be, unfortunately, but one option would be to stream through the dataset twice, first recording the document IDs of all assets and then looking for `_ref` properties that match those assets. That would lead to a possible race condition though.

**Comment by rexxars** [comment]
This has since been addressed by also asserting on the document ID shape.
