### ISSUE TITLE
Client doesn't work with Node / Ember FastBoot

### ISSUE THREAD

**Issue by mhluska** [sanity-io/sanity#877]
I'm using [ember-auto-import](https://github.com/ef4/ember-auto-import) to import the JS client. The way it works is it looks at the `browser` key in `package.json` to determine the entry point which this library sets as [this](https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/client/package.json#L20):

```
  "browser": {
    "./src/http/nodeMiddleware.js": "./src/http/browserMiddleware.js",
    "./lib/http/nodeMiddleware.js": "./lib/http/browserMiddleware.js"
  },
```

[ember-auto-import seems broken](https://github.com/ef4/ember-auto-import/issues/20) because it can't handle POJOs for `browser` but I've patched it to work for the sake of this issue.

If I force ember-auto-import to instead use the sanity client UMD build which is found at `node_modules/@sanity/client/umd/sanityClient.js`, Node/FastBoot complains about xhr.open being used:

```
TypeError: xhr.open is not a function
```

This happens when my app runs `client.fetch('...')`. My app tries to run this in both Node/FastBoot and browser. It works fine in browser but fails in Node/FastBoot.

I've dug into this a bit and my theory is this happens because the `@sanity/get-it` package doesn't distinguish between browser vs. node at run time. It does it at build time again using the `browser` key. And since I've forcefully pointed ember-auto-import to the UMD build, which was built using browserify, it just uses the browser code in Node.

I'm too stupid to know how to fix this.

---

Edit: This is how ember-auto-import determines the entry point: 

```
let localEntrypoint = pkg.module || pkg.browser || pkg.main || 'index.js';
```

Maybe a convenient solution would involve setting a `module` key in package.json that points to a build that correctly runs in both environments?

**Comment by rexxars** [comment]
I'm not too familiar with Ember, but the `package.json` field works as it should in both browserify and webpack. The "[spec](https://github.com/defunctzombie/package-browser-field-spec)" allows setting an object in order to override only certain modules, which we use to keep the bundle size down. In node, we add debug, retry and a user agent middleware, but there are not needed in the browser.

I'm not sure if it would work as expected if the embed-auto-import package fixed the bug in question - would you be able to provide a minimal sample repo using this module? I have very little experience with ember, unfortunately.

If you just need to run queries (not do any mutations, listening, asset uploading or similar), you _could_  use an [alternative client](https://github.com/rexxars/picosanity).

**Comment by mhluska** [comment]
@rexxars thanks for the feedback.

If any Ember users end up reading this, I wrote a hacky service to just fetch the data I needed: https://gist.github.com/mhluska/c3dc927b46657f09eab77d8e0871e75f
