### ISSUE TITLE
Provide a way of removing references before delete

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#963]
When displaying the delete confirmation for a document that other documents refer to, we should support a way of removing the references from the documents that refers to it.

**Comment by simen** [comment]
This can easily lead to disappointment and unintended consequences since references can be many places, even as inline links in portable text. To implement this responsibly we would have to make a proper way to review incoming references. This is a good idea, but it will be some time before we get to it.

**Comment by 12ian34** [comment]
How have others worked around this problem? I am having issues deleting documents with hard references, and also issues with deleting the references

**Comment by sebbean** [comment]
would love to be able to delete records via cli

even weak references are blocking me

**Comment by felixhagspiel** [comment]
any update on this?
